### ISSUE TITLE
UX: Users change the version of Servlet API when using our wizard to add it to the project

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#1006]
We currently only support 2.5.  We should make that very explicit if we can't disable them changing it entirely.

Ideally there would be no dialog UIs to import the selected libraries.

**Comment by etanshaul** [comment]
I can disable the UI dialog for this if that's really what we want. I think it does make sense.

**Comment by patflynn** [comment]
@ludoch 
One gotcha is that when vm true, env flex, or runtime java8 servlet 3.1 is also valid.
