### ISSUE TITLE
Update new app engine project wizard wording

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/google-cloud-intellij#1014]
Currently the wizard says "Google App Engine"

<img width="741" alt="screen shot 2016-10-13 at 1 57 14 pm" src="https://cloud.githubusercontent.com/assets/1735744/19360542/059f722c-914d-11e6-814f-8e110e629506.png">

If it said "Google App Engine Standard" instead, it might be clearer to the user.

**Comment by patflynn** [comment]
Yeah, this needs to be done.
