### ISSUE TITLE
Unselect Web Application option if Google App Engine is unselected in the New Project dialog

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/google-cloud-intellij#1017]
Currently, Web Application is automatically checked if Google App Engine is.
But Google App Engine isn't automatically unchecked if Web Application is.
This can lead to issues, like artifacts lacking the Web facet and not being discovered as a valid deployable (other than with Filesystem JAR or WAR).

**Comment by etanshaul** [comment]
Some notes on this:

See `AppEngineSupportProvider#getDepenenciesFramworkIds`. this is how 'web' is marked as a dependency of Google App Engine, and consequently how web gets automatically checked.

For the the automatic selection to go the other way around, the web framework (provided by the platform) would need to mark App Engine as its dependency. I'm not sure if this is possible (perhaps by overriding the platform provided web framework) or even desireable if its possible.

Another option could be to have App Engine as a nested dependency of 'web', like Struts is in the following screenshot:

![image](https://cloud.githubusercontent.com/assets/1735744/19496645/63daa69c-9556-11e6-98a1-0b6e8c17faee.png)

**Comment by joaoandremartins** [comment]
App Engine as a nested dependency of Web makes a lot of sense to me. The problem is that it wouldn't work for IC. It already doesn't, although I'm thinking we want to change that?
Could this be solved by adding Google App Engine to the left-hand side menu? We would always enable Web application and there would be no way to disable it. Locating GAE New Project on the dialog also seemed to be a recurrent topic on all user studies.

**Comment by etanshaul** [comment]
irrelevant due to #1065
