### ISSUE TITLE
Add "Google " before every run config name, so every config type shows up together

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/google-cloud-intellij#1021]

**Comment by patflynn** [comment]
I'm not sure about this. I agree there's a problem.  But adding 'Google..' makes all of our run config type names too l ong.

**Comment by joaoandremartins** [comment]
Yeah, Google Stackdriver Debugger is also not the name of the product. GCP also doesn't go very well...

**Comment by etanshaul** [comment]
Here is what the run configs look like with the Google prefix (as well as an update to the local dev server name):

<img width="1055" alt="screen shot 2016-10-13 at 3 48 34 pm" src="https://cloud.githubusercontent.com/assets/1735744/19364538/9452ee9a-915c-11e6-84fd-8840abd322db.png">

**Comment by patflynn** [comment]
Anybody want to take a stab at getting this in for today's release?

**Comment by etanshaul** [comment]
Sure, I'll start as soon as I finish my current PR.
