### ISSUE TITLE
ConflictingAppEnginePluginCheck only happening when a project is opened

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#1038]
For users who don't currently have a project opened, they will not see the notification to disable the old appengine plugin. This means that when using the new project wizard they'll see the old app engine tech.

I think this is because it's configured as a 'StartupActivity', when it should probably go in the CloudToolsPluginInitializationComponent.

**Comment by aslo** [comment]
Makes sense. I think it may just make sense to make this its own `ApplicationComponent`, so we don't bloat the `CloudToolsPluginInitializationComponent` too much.
