### ISSUE TITLE
Investigate migrating run configs and libraries brought in by the old plugin

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/google-cloud-intellij#1040]
If you create an AE standard project using the old plugin, there will be a local dev server run config created for the user.

Then, when switching to our new tooling and opening the above project, the run config will be in an invalid state: it will have a legacy name (referencing the app engine sdk) and the sdk path will be empty. 

Similarly, the module's libaries will have a provided dependency on the App Engine SDK.

**Comment by aslo** [comment]
We may want to look into modifying `AppEngineStandardFacetMigrationConversionProcessor` to handle this as well. This may also warrant a rename of that class, to convey that it now handles broader project-level migration to our plugin.

**Comment by etanshaul** [comment]
I've created a doc with a bunch of screenshots to make the current process explicit and help expose what friction there currently may be:

https://docs.google.com/document/d/1QXzD8n_YA14hpZLlu0aGVvtXxORFsMkwV2u7StxiVls/edit

From this exercise I see two areas we can improve:
1) Migrate the local dev run config -> rename it to something less confusing
2) Fix the migration of the deployment run config. After migrating to the new plugin, the deployment config was in a broken unrecoverable state

**Comment by joaoandremartins** [comment]
This is the kind of stuff I'm not sure is worth spending too much time on fixing by automating vs documenting what the users should manually do, i.e., deleting the old run configs and creating new ones manually.

**Comment by etanshaul** [comment]
For things like the naming of the local dev run config I agree its less important.

But I do think making the process smoother for the deploy run config is a good idea. For a user switching to our plugin its not the best experience if the first then they see is a broken / unrecoverable run configuration.

**Comment by joaoandremartins** [comment]
Before going knee deep on this, I'd just take a look at the OKRs and see if there's anything on the way more urgent.

I'd agree more with you if, previously, deployment run configs held a lot of data that would be inconvenient for the user to reproduce, by creating new ones. Since this isn't the case, quite on the contrary, I'm not too sure if this warrants a lot of effort. Just my 2 cents :)

**Comment by etanshaul** [comment]
I think having working run configs is a bigger deal to have a smooth transition and good first experience with the new plugin. Either way, I don't think this a huge effort - I'm investigating what a solution would involve.
