### ISSUE TITLE
Local development runs of google-cloud-intellij don't always seem to re-deploy the 'google account' plugin

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#1050]
I frequently see the 'Google Plugin Compatibility Problem' when running our 'Cloud Tools on IntelliJ' run configuration for local development.  This shouldn't be possible as both plugins should be on the same version and deployed together.

**Comment by patflynn** [comment]
This is driving me nuts.

**Comment by etanshaul** [comment]
if you run a gradle clean this should fix the problem. I agree though that we should figure out why it happens in the first place though

**Comment by patflynn** [comment]
obsolete.
