### ISSUE TITLE
Warn the user if they're using an incompatible version of the Cloud SDK

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#1051]
Today, Cloud SDK 131.0.0 is required for a smooth experience using our plugin. We should have a way of specifying the minimal required version for the Cloud SDK to work with our plugin.

**Comment by joaoandremartins** [comment]
We should also be checking for the app-engine-java component version, for dev_appserver. I think it's possible to only update one and not the other.

**Comment by patflynn** [comment]
Are you sure?  I got the impression the last discussion on this seemed to
indicate otherwise.

**Comment by joaoandremartins** [comment]
Actually, you're right, it's not possible to just update app-engine-java. I just tried and was unable to.

**Comment by aslo** [comment]
Has anyone started work on this one? I'm happy to take this.

**Comment by aslo** [comment]
This will depend on https://github.com/GoogleCloudPlatform/appengine-plugins-core/issues/241
