### ISSUE TITLE
Library UI heading is missing from the library selector

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/google-cloud-intellij#1058]
Somehow it got lost in refactoring. Here is what it looks like (notice the "library" header is missing). Its also missing from the facet display since it uses the same UI component.

![image](https://cloud.githubusercontent.com/assets/1735744/19659072/6f86234e-99f8-11e6-9ce5-6dc665ef17bf.png)

**Comment by patflynn** [comment]
ah so you mean like having a section header for the checkboxes?  Sounds reasonable.

**Comment by etanshaul** [comment]
yeah, it was there previously but I must have removed it accidentally when refactoring the UI classes.
