### ISSUE TITLE
Auto-create all relevant run configs for a given module type

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#1063]
For instance:

If we detect that a module is an appengine standard module, we should create the 'local dev server' (we already do this), the 'app engine deployment', and the 'stackdriver debug' run configs by default.

When we have flex and stackdriver facets we should do the same.

**Comment by etanshaul** [comment]
Note that for project imports (as opposed to new project wizard) the local dev server is not auto created.

I'll fix this in here too.

**Comment by etanshaul** [comment]
Regarding my last comment, I actually want to fix that separately: https://github.com/GoogleCloudPlatform/google-cloud-intellij/issues/1089

**Comment by etanshaul** [comment]
Closed via https://github.com/GoogleCloudPlatform/google-cloud-intellij/pull/1090
