### ISSUE TITLE
Stackdriver Debug run configuration should include links to documentation

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#1066]

**Comment by joaoandremartins** [comment]
How does this look?

![screenshot from 2016-11-28 16 17 04](https://cloud.githubusercontent.com/assets/3290856/20686304/24400dce-b586-11e6-9e90-a986e634f974.png)

**Comment by joaoandremartins** [comment]
One issue is that the bigger label text won't wrap or shrink, so it isn't possible to resize the window to a size less than the width of that label...

**Comment by patflynn** [comment]
So there's no way to make the label wrap?  I'm wondering how that would
look on a laptop screen or during a demo on a low res projector.

I'd use this link: https://cloud.google.com/debugger/

Also, resource bundle for the text.
