### ISSUE TITLE
App Engine Flexible deployments should support exploded war directories

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#1069]
Steps to reproduce:

1) Create a web java project in ultimate
2) create an exploded war artifact from your project module
2.5) build the exploded war artifact
3) create an App Engine deployment 

observe:
1) the exploded war artifact is not an available deployment source.
2) If you select filesystem jar/war and navigate to ../out/artifacts/exploded-war/  you will get a validation errors that it's not a .jar or .war. 
3) change teh directory name to .war and it works.

fixes:
1) accept exploded war artifact
2) allow specifying an arbitrary directory as the project output?

**Comment by etanshaul** [comment]
It looks like the runtimes do not support deployment of exploded war directories. I implemented all the plumbing needed to allow this path for the user, but instead of the application being served, it just serves the directory/source.

Here is what the updated Dockerfile I used looks like:
```
FROM gcr.io/google_appengine/jetty9
ADD target $JETTY_BASE/webapps/root
```

@meltsufin is this something we want to consider supporting?

**Comment by meltsufin** [comment]
Yes, we want to support exploded WARs for vanilla flex. However, this is more of a problem of generating the correct Dockerfile in gcloud. I'll create a bug there.

**Comment by chanseokoh** [comment]
One thing that bugs me is that Jetty failed to recognize the `root/` directory as a servlet web app, but instead serving it as a static directory. (I also think I hit this before when I tried to push an exploaded war 5 months ago or so.)

There might be a need to change the Jetty configuration in the flex image too: 
http://www.eclipse.org/jetty/documentation/current/configuring-specific-webapp-deployment.html

**Comment by meltsufin** [comment]
@gregw Is this something that can be easily fixed with some configuration in the jetty-runtime?

**Comment by gregw** [comment]
It should not need a config change. It should just work. 
So either a bug in jetty deployer or how we set it up.  I'll take this and investigate.

**Comment by meltsufin** [comment]
I wonder if nginx is stepping in or something.

**Comment by gregw** [comment]
@meltsufin The directory listing looks like a jetty style sheet has been applied, so I doubt it is nginx.

**Comment by gregw** [comment]
Actually, depending on the webapp, a directory listing may be valid content!  If there is no servlet mapped to / or /* then Jetty will list the root directory by default.  

Try click into WEB-INF and see if it blocks that content - if so, then this is a webapp with no servlet at root.

Can you attach the web.xml?
