### ISSUE TITLE
Local dev run configuration not properly validating artifact selection

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/google-cloud-intellij#1092]
`AppEngineRunConfigurationEditor#resetEditorFrom` has logic to automatically pre-select an artifact if there is only 1 available. This causes timing issues with the validation of the panel causing the panel to appear to not be in an error state, but still prevent the user from running the dev server.

**Comment by joaoandremartins** [comment]
I'm not able to reproduce this error.

@etanshaul do you remember how it could be reproduced?

**Comment by etanshaul** [comment]
@joaoandremartins this bug is tightly coupled to https://github.com/GoogleCloudPlatform/google-cloud-intellij/pull/1090 so I can take this one. (I need to come up with a solution to this before I merge in that PR).

**Comment by joaoandremartins** [comment]
I'm familiar with this issue since I've had to fix it before. I can either patch that PR and take a look, or I can put myself at your service for any questions you might have. Up to you.

**Comment by etanshaul** [comment]
Essentially I do not think its correct to populate the artifact combobox from within the editor form itself. 

Rather, I think the artifact should be set on creation of the run configuration (which I am doing a lot of in #1090 and therefore this issue is surfacing).

**Comment by joaoandremartins** [comment]
As long as the artifact gets preselected when there is only one, I'm good.
The way things are now was actually carried over from the former IJ GAE plugin.

**Comment by etanshaul** [comment]
Yea. The goal is that if there exists and artifact on creation of the run config, it will be selected.

The problem with selecting it from within the resetEditorFrom method is that this doesn't persist the selection. So, depending on the flow, even though its selected running the config can error out.

**Comment by etanshaul** [comment]
closed via https://github.com/GoogleCloudPlatform/google-cloud-intellij/pull/1090
