### ISSUE TITLE
Shared run configurations include Java SDK path

### ISSUE THREAD

**Issue by sparhomenko** [GoogleCloudPlatform/google-cloud-intellij#1094]
We are using Google Cloud Tools plugin with latest Intellij IDEA (2016.2.5) and Java (1.8.0_112) to create "Google App Engine Local Development Server" run configurations used in our local development environment. The run configurations are shared, i.e. the "Share" checkbox is enabled and the resulting XML files are version controlled.

Inside the XML the `/component/configuration/server-settings/java_home_directory` element contains the path to Java SDK used in the IntelliJ IDEA project. When the run configuration is used, the plugin automatically adjusts the path in the XML file. Since Java SDK directory can differ from a developer to developer, this behaviour results in occasional version control commits and unnecessary conflicts.

We tried aligning the Java SDK location, but this is not realistic for most developer teams since the path depends on OS and Java version used. Most other Java-based plugins (e.g. Maven) do not include Java SDK path into the XML file and just use the one defined in IntelliJ IDEA project settings. It would be helpful if Google Cloud Tools would follow the same behaviour.

**Comment by patflynn** [comment]
We'll check this out. Thanks for the report.
