### ISSUE TITLE
Rename Google App Engine to Google Cloud Platform, under Clouds

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/google-cloud-intellij#1100]
It sounds a bit weird that under a Google App Engine Cloud, the only thing we specify is a Cloud SDK.

We also support other GCP products, like Stackdriver and Stackdriver Debugger, and will possibly support more in the future, so a new naming sounds warranted to me.

**Comment by patflynn** [comment]
Not sure about this.  Clouds for IJ purposes appears to map to deployment
targets.

**Comment by joaoandremartins** [comment]
It just feels weird that the Stackdriver facet asks users to specify a Cloud SDK by going to Clouds and adding an App Engine one..

**Comment by patflynn** [comment]
That's a good point. I thought we had that config under google -> settings

**Comment by joaoandremartins** [comment]
Actually, I can ask users to go there instead. I just thought it would make more sense to have them go to Clouds. But you're probably right, Clouds is tied to deployments... I'll make that change
