### ISSUE TITLE
Cloud SDK validation messages shown incorrectly

### ISSUE THREAD

**Issue by aslo** [GoogleCloudPlatform/google-cloud-intellij#1111]
When creating a new App Engine project, if a valid cloud sdk path is selected in the Cloud SDK panel, a validation error will flash briefly before disappearing. That validation error should never be shown.

**Comment by patflynn** [comment]
This is a dupe of #1109. Sorry Alex, I was referring to the way that the stacked messages have inconsistent formatting.

**Comment by aslo** [comment]
👍
