### ISSUE TITLE
CSR integration seems to use out-dated credentials

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#1117]
Observed issue:

1. I'm logged in as user A
2. I'm  doing file -> new project from version control -> google cloud
3. Picking one of user A's projects
4. Getting error 'remote error: Access denied to user B'

Hypothesis:
I've been logged in as User B before and the credentials it's using for the git credential helper are cached somehow.

**Comment by nkibler** [comment]
Could this be related to #1174?
