### ISSUE TITLE
Analytics pings should include platform data

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#1124]
As far as I know we originally included this but lost it when moving over to the new property and implementation.
Ideally:
1. ct4ij plugin version
1. IntelliJ version (including CE vs UE)
1. Java version
1. OS

**Comment by patflynn** [comment]
@chanseokoh @elharo you'll need this on the Eclipse side as well.

**Comment by chanseokoh** [comment]
For 2,3 and 4, I guess we could to send them as another metadata key-value pairs.

To do so, we need to extend the current ping API and implementation. Currently, we can send only one metadata key-value pair as a virtual page title (as "label=value"), but we can actually send multiple pairs, e.g., "label1=value2&label2=value2&...". Properly escaping might be necessary.

Eclipse issues:
https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/548
https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/741
