### ISSUE TITLE
Checking out from Google Cloud Repositories errors out

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/google-cloud-intellij#1142]
Not a lot of detail in the error message.

We're either not sending the correct scope in the credential, or something else wacky is going on. I'm only getting this from my Windows VM, Linux is working fine.

![screenshot from 2016-12-06 15 34 23](https://cloud.githubusercontent.com/assets/3290856/20942535/b2882000-bbc9-11e6-9230-2f54631cf389.png)

![screenshot from 2016-12-06 15 33 55](https://cloud.githubusercontent.com/assets/3290856/20942548/c388eefc-bbc9-11e6-9900-5d952df1c08e.png)

**Comment by joaoandremartins** [comment]
Hopefully this isn't because my GCE VM doesn't have that specific scope enabled... It shouldn't be, because I'm authenticating with my corp account.

Also, this used to work before, stopped all of a sudden.

**Comment by patflynn** [comment]
random possibility: it could be that the credential helper is storing the
access token, that it's expired, and that we don't have a mechanism for
refreshing it.

**Comment by joaoandremartins** [comment]
I mistook the given URL in the error message for a scope.

It appears that GCR now requires a git identifier in order to clone.

Following the given link, https://source.developers.google.com/auth/start?scopes=https://www.googleapis.com/auth/cloud-platform, and creating the .netrc file as suggested seems to resolve the issue.

We should parse the error message and show users the URL if they get this error.

**Comment by joaoandremartins** [comment]
Just adding the output stream to the error message looks like this:

![screenshot from 2016-12-14 14 38 07](https://cloud.githubusercontent.com/assets/3290856/21197866/0619add2-c20b-11e6-95f1-1af1d06b9c34.png)

It's unfortunate that the URL isn't clickable, but I can't find a way to make it so. I verified that using a HTML "a" element doesn't work either.
