### ISSUE TITLE
appengine-web.xml dtd is not registered.

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#1156]
Ideally if the plugin is installed this would just work somehow.

**Comment by briandealwis** [comment]
I had wired this up for Eclipse but @elharo [had some reservations](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/150#issuecomment-218287945) so we backed it out.

**Comment by patflynn** [comment]
Whatever the definition doc that's available, it can be pretty handy to get
the editor completion.

@elharo what's the reservation?

**Comment by elharo** [comment]
I'm not sure what the problem you're trying to solve in IntelliJ is. First, are you talking about a DTD or schema? DTDs have some security issues. 

Most schemas make code more rigid and brittle, for little benefit; but if there's a specific need for it, we could discuss.

**Comment by patflynn** [comment]
Wouldn't the security concerns be mitigated by the fact that we're
providing the schema files? I'm not sure I follow about
rigidity/brittleness. Perhaps you're talking about when you're developing a
new xml format?

Either of the descriptor file types properly configured enables validation,
auto-completion, and quick docs for the file type.  All super-useful.

In any case, I'm noticing that we've actually already implemented this in
IntelliJ for modules with App Engine framework support. So I'm going to
close this for now.
