### ISSUE TITLE
Cloud SDK path doesn't get updated from the devappserver run config UI, with more than one Application Server

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/google-cloud-intellij#1158]
Steps to reproduce:
- Add two Application servers from the "Configure" popup,
- Set an incorrect Cloud SDK path in the second one and save.
- Click Configure again, set a valid Cloud SDK path and save.
- Verify that the invalid Cloud SDK warning hasn't gone away yet.
- Clicking Configure will show that the Cloud SDK path wasn't updated.

**Comment by patflynn** [comment]
This is not release blocking but it should be looked at soon.

**Comment by joaoandremartins** [comment]
When there are multiple application servers, the last one's update crushes the rest, and we're allowing invalid SDKs to be stored from that dialog.

As mitigation, I suggest that the last valid SDK is persisted. There could be issues on the very specific situation where a user adds two application servers from that window and sets 2 valid paths on each. But we don't really support multiple application servers, so there isn't a lot more we can do here.

**Comment by etanshaul** [comment]
Is it correct that we should be allowing the user to persist invalid SDKs in the first place?

**Comment by joaoandremartins** [comment]
It's not. But as I said, there is still an issue if we only allow valid SDKs.
