### ISSUE TITLE
Standard local app server option is shown for projects without Standard facet

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/google-cloud-intellij#1168]
Checking out https://github.com/GoogleCloudPlatform/getting-started-java and creating an IJ project from helloworld-servlet results in "Run on a local App Engine Standard dev server" appearing in the Tools -> Google Cloud Tools menu.

![screenshot from 2016-12-12 11 27 50](https://cloud.githubusercontent.com/assets/3290856/21106984/16eb5b64-c05e-11e6-87e5-392fdf3a5e6f.png)

![screenshot from 2016-12-12 11 28 05](https://cloud.githubusercontent.com/assets/3290856/21106991/1a54f864-c05e-11e6-8e59-8fc31d3106bc.png)

**Comment by etanshaul** [comment]
@joaoandremartins the condition for determining if the local dev server shortcut should appear is actually the existance of an appengine-web.xml, not an appengine standard facet, which I think is the correct behavior.

Similarly, the user can deploy to AE standard without an AE standard facet.

Leaving open for discussion.

**Comment by joaoandremartins** [comment]
Are you saying that, currently, existence of an appengine-web.xml file is what shows/hides that option from the menu? I thought it was never hiding.

Not totally sure if it makes sense to allow users to deploy to App Engine Standard if there isn't any Standard facet in the module. But I don't feel strongly about that, it might actually help feature/plugin discoverability.

Do you think we should keep showing that button to any user with the plugin installed, regardless of the project/module and whether it has Standard support?

**Comment by patflynn** [comment]
I'm kind of thinking that our App Engine functionality should probably only
support modules with our facets.

The reason I see it that way is that we notify the user to add our facet if
we detected the appengine-web.xml, and I'm thinking maybe if the user opts
not to add the facet we should take that as an indicator that they don't
want our app engine integration showing up..

Not super principled on this yet so happy to discuss.

**Comment by etanshaul** [comment]
We used to require the app engine standard facet for deployment. We then got rid of it. The reason, if I recall correctly, was for consistency with Flex deployment which does not yet have a facet. Also, at the time we were not auto creating all of the run configurations, which we are now.

I'm fine requiring the facet. I'm trying to dig up my old PR where I removed this requirement for more context in case I'm forgetting something.

**Comment by etanshaul** [comment]
@joaoandremartins 

actually the current state is that if an appengine-web.xml is missing, we don't hide the local dev server menu item. instead we show this:

![image](https://cloud.githubusercontent.com/assets/1735744/22485558/1de84a92-e7d4-11e6-9c58-a5c8637d9ed0.png)


I believe this was due to a technical limitation where we couldn't make the determination early enough (before the menu action is set up).

**Comment by patflynn** [comment]
the dev server is also showing up in the server list for new Java EE projects, even if they haven't selected App Engine.  Not sure how fixable that is.
