### ISSUE TITLE
New AE standard project wizard should generate web.xml with servlet 2.5

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/google-cloud-intellij#1194]
It's currently generating one with servlet 3.1 which causes staging failures.

**Comment by patflynn** [comment]
I thought we had it configured to pre-select 2.5.

**Comment by patflynn** [comment]
ah on second thought I think this was because we weren't a child of web in the wizard.  I wonder if there's even a way to fix this.
