### ISSUE TITLE
flex and mvm label in standard deployment UIs are mixed up

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#1199]
if my appengine-web.xml contains
`<env>flex</env>`

the label at deployment is:
"App Engine Managed VM"

if it's 
`<vm>true</vm>`

the label is:
"App Engine Flexible Environment"

I think this is a regression because the labels should be swapped and I think this was correct at an earlier date.

**Comment by etanshaul** [comment]
A couple things I noticed:

When deploying with `<vm>true</vm>` I get the following message:
`ERROR: (gcloud.app.deploy) INVALID_ARGUMENT: Deployments to App Engine Flexible require `env: flex` in app.yaml.  The `vm:true` setting has been deprecated. To learn more, please visit https://cloud.google.com/appengine/docs/flexible/python/upgrading.
`

When deploying with `<env>flex</env>` without adding any custom libs I get the following:
`Unable to stage app: GAE Flex compat applications need to depend on the GAE API jar, but it was not found in the WEB-INF/lib directory.
`

Upon adding the App Engine API jar (via our managed lib support within IntelliJ) deployment succeeds.

These are side points - the messaging for `<env>flex</env>` needs to be updated as mentioned in the original issue.
