### ISSUE TITLE
Not able to create / debug Google AppEngine project

### ISSUE THREAD

**Issue by bezysoftware** [GoogleCloudPlatform/google-cloud-intellij#1200]
I'm trying to create a new Google AppEngine project, but failing. Here's my setup:

    Windows 10, x64
    Intellij Community Edition, 2016.3.3
    JDK 1.7.67 & 1.8.121
    JAVA_HOME set to C:\Program Files\Java\jdk1.7.0_67 (I also tried the 1.8 version)
    Google Cloud SDK 141 (from "gcloud info")
    Google Cloud Tools plugin in Intellij v16.11.6 - see screenshot 1

Despite all this I am unable to create new AppEngine project / debug existing one. In the "New Project" dialog I don't have the option for Google AppEngine (screenshot 2). As for the debugging I don't have the "AppEngine Dev" option among debuggers - I only have gradle / groovy / some others / and Google AppEngine Deployment (screenshot 3). But no option to debug locally.

Any ideas what's wrong with my setup? Anything I missed?

1) https://i.stack.imgur.com/TnHvH.png
2) https://i.stack.imgur.com/yubHq.png
3) https://i.stack.imgur.com/P6xde.png

Note that I just tried on a fresh Ubuntu 16.04 in VirtualBox with the exact same results

**Comment by patflynn** [comment]
Hi Tomas, your problem is that you're using IntelliJ CE which doesn't have
any built in support for locally running web apps.

One option for local run if you're using gradle is to use our
https://github.com/GoogleCloudPlatform/app-gradle-plugin plugin.  You can
configure a remote debug session to run using the jvmArgs config params.

https://github.com/GoogleCloudPlatform/app-gradle-plugin/issues/96

**Comment by bezysoftware** [comment]
But there is no local debug option with CE? Maybe time to look at Eclipse

**Comment by patflynn** [comment]
You can debug with CE, you just have to create a 'remote debug' run config
and connect after starting the local run with the right jvm flags (which
are displayed in the remote debug run config UI).

That being said, if you're doing web development, don't own Ultimate
Edition, and you're willing to use Eclipse, than our plugin for Eclipse is
a better choice.

https://cloud.google.com/eclipse/docs/
https://github.com/GoogleCloudPlatform/google-cloud-eclipse
