### ISSUE TITLE
Automatically generated run configs for Standard facet are hidden

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/google-cloud-intellij#1207]
I checked out a project from GCR, added it as Maven project and added GAE Standard support. The dev_appserver run config was selected by default, but in the dropdown, the Deployment and Stackdriver Debugger run configs were visible.

However, when the Run Configs main window is opened, I can only see the dev_appserver run config there.

![screenshot from 2017-02-07 11 10 29](https://cloud.githubusercontent.com/assets/3290856/22699776/7cea10dc-ed26-11e6-8047-35f072aa7619.png)

Then, I leave the window and select one of the other two hidden run configs and try to reopen the Run Configs window. Now, the run configs are visible.

![screenshot from 2017-02-07 11 10 47](https://cloud.githubusercontent.com/assets/3290856/22699800/91c322fa-ed26-11e6-82b5-c7cd683a7b6c.png)

**Comment by joaoandremartins** [comment]
If the dev_appserver run config is chosen again afterwards, then the other two run configs are still hidden.

**Comment by joaoandremartins** [comment]
If the project is created as a normal IJ project and Standard support is added afterwards, the same happens.

Also, for a project created this way, I noticed that no Web artifacts are automatically generated, leaving us with no selectable deployables. (unrelated to this issue, though)

**Comment by etanshaul** [comment]
Regarding your last comment. Do you mean creating a 'web' project, then later adding an appengine-web.xml + standard framework support?

**Comment by joaoandremartins** [comment]
I think this only happens on the IJ instance spawned by gradle runIdea.
Trying this on a normal IJ run doesn't produce the same issue. I think it's safe to close.
