### ISSUE TITLE
warning txt too small for app engine app resource creation

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#1212]
<img width="397" alt="smalltxt" src="https://cloud.githubusercontent.com/assets/7862557/22707923/58ca3396-ed42-11e6-9325-a1eab48041d5.PNG">

**Comment by etanshaul** [comment]
doesn't look like an issue anymore

@joaoandremartins was this fixed in your facet change because of swapping to use hyperlink labels instead of html?

**Comment by joaoandremartins** [comment]
Yes, I did some work around this. It should be good.

**Comment by etanshaul** [comment]
cool. closing
