### ISSUE TITLE
Deployment source not found

### ISSUE THREAD

**Issue by grembek** [GoogleCloudPlatform/google-cloud-intellij#1220]
I am encountering an issue deploying my application to App Engine using IntelliJ (Google Cloud Tools Plugin 16.11.16)

Every time I deploy I receive the following message:
Deploying '[2017-02-08 12:22:11] Maven build: TestApp. Project: my-server. Version: auto'...
Failed to deploy '[2017-02-08 12:22:11] Maven build: TestApp. Project: my-server. Version: auto': Deployment source not found: /Users/../TestApp/target/Test-App-1.0-SNAPSHOT.

Can you please advise?

**Comment by patflynn** [comment]
@grembek 

Hi thanks for the report.

Could you take a screenshot of your deployment run config?  I'm wondering if for some reason your 'maven build' before launch task is missing for some reason.

**Comment by joaoandremartins** [comment]
Does Build -> Rebuild Project, then reattempting to deploy help?

Have you mvn or gradle cleaned your project recently?

**Comment by grembek** [comment]
I cannot find a way to reproduce it, sorry... Closing the issue

**Comment by mservidio** [comment]
I'm experiencing the same issue, did anyone find a solution?

**Comment by patflynn** [comment]
@mservidio we'll need more information. 

Could you include:
- whether you're on intellij community or ultimate
- version of intellij
- version of our plugin
- screenshot of your deployment configuration


thanks!

**Comment by lleiguo** [comment]
I have the same issue, I'm on intellij ultimate 2017.2.3, plugin version 17.8.2

![image](https://user-images.githubusercontent.com/552341/30200489-0138ccdc-942c-11e7-868f-4033f0747338.png)

**Comment by patflynn** [comment]
@lleiguo could you include the error you're seeing?

**Comment by karikalankumaresan** [comment]
I have the same error. The error is,

Failed to deploy '[2017-09-09 18:53:28] Maven build: demo-test1. Project: xxx. Version: auto': Deployment source not found: D:\Projects\demo-test1\target\demo-test1-0.0.1-SNAPSHOT.

**Comment by lleiguo** [comment]
@patflynn Yes, the error I got is:

Deploying '[2017-09-09 14:07:28] Maven build: shylock. Project: xm-555. Version: auto'...
Failed to deploy '[2017-09-09 14:07:28] Maven build: shylock. Project: xm-555. Version: auto': Deployment source not found: /Users/leiguo/playground/gcp/shylock/target/shylock-0.1.

I think the problem is it's looking for the file without the jar, e.g. in my example, it suppose to look for "/Users/leiguo/playground/gcp/shylock/target/shylock-0.1.**jar**" but instead it's looking for "/Users/leiguo/playground/gcp/shylock/target/shylock-0.1."

**Comment by karikalankumaresan** [comment]
@lleiguo Yep, when I changed to the "filesystem JAR" deployment, the requests (from app engine) were returning 502 errors. Yep, it works in command line, but it is an inconvenience to use both IDE and command line. Thanks.

I suspect that it could be due to the plugin mix up, but I am not sure though. @patflynn any help would be greatly appreciated. Thanks.

**Comment by patflynn** [comment]
@etanshaul 
@nkibler 

I think this was broken by https://github.com/GoogleCloudPlatform/google-cloud-intellij/commit/5020c8c6b91925daa3c58cd4f05e62231d6147d2

Seems to only set the extension if environment is null.

**Comment by patflynn** [comment]
@karikalankumaresan 
@lleiguo 

You may want to either build from source or check our nightly build tomorrow to see if this fixes the issue for you.

**Comment by patflynn** [comment]
To download the nightly you can use the instructions for trying out the alpha channel but use the following url instead:

https://plugins.jetbrains.com/plugins/nightly/8078

**Comment by patflynn** [comment]
@karikalankumaresan 
@lleiguo 
@mservidio 

17.9.1 which was just released should have fixed this issues.  Please update your plugins and let us know if there are any problems.

Thanks again for reporting this!

**Comment by karikalankumaresan** [comment]
@patflynn Tried it and it works. Thanks loads.

**Comment by joaoandremartins** [comment]
I'm running 17.9.2 ands I just saw this happening.

**Comment by nkibler** [comment]
@joaoandremartins could you post a stacktrace?

**Comment by joaoandremartins** [comment]
Strangely enough, can't reproduce anymore..

**Comment by k4dima** [comment]
Had this issue. Resolved by deleting and adding artifact.

**Comment by jwusch** [comment]
Happening to me again, k4dima, what artifact did you delete then re-add?  I tried doing most of my GCP config over from scratch, but same error

**Comment by etanshaul** [comment]
@jwusch are you using Maven or Gradle?

Some things to check:

1) Do you have appengine standard framework support added to your module? (Tools -> Google Cloud Tools -> Add App Engine support -> app engine standard..)
2) Is the app engine facet added to the correct module that you are attempting to deploy? (File -> Project Structure -> Modules). If you are using Gradle, its possible you are running into this: https://github.com/GoogleCloudPlatform/google-cloud-intellij/issues/2162. If so, follow the steps on that issue)
3) Just to make sure everything is synced with your build, re-sync with Maven/Gradle by hitting the refresh button in the Maven/Gradle panel

**Comment by jwusch** [comment]
I was able to fix it by deleting my Application Server Definition under File->Settings->Clouds and re-adding it.  It was same issue of missing .jar on the filename.  It was basically working exact same config, and one run it just stopped, literally didn't seem to be any root cause.

**Comment by ashb2612** [comment]
Same issue here.
IntelliJ Community 2018.2.1 (just updated from v2017, same issue)
Plugin version 18.7.1

![image](https://user-images.githubusercontent.com/42252788/43982795-7b62d238-9cef-11e8-8a5e-485d4fc3c200.png)

Log:
Deploying '[2018-08-10 22:24:50] Maven build: *PROJECTNAME*. Project: *PROJECTNAME*. Version: auto'...
Failed to deploy '[2018-08-10 22:24:50] Maven build: *PROJECTNAME*. Project:*PROJECTNAME*. Version: auto': Deployment source not found: C:\Users\*PROJECT_PATH*\target\SimonSays3-1.0-SNAPSHOT.

**Comment by etanshaul** [comment]
Hi @ashb2612 

A couple things to check:
- First ensure that your project is synced with Maven (in the maven tool window, click the refresh button)
- When you run a `maven package`, does that artifact in the path specified in error in the log exist (`...1.0-SNAPSHOT...`)?

**Comment by ashb2612** [comment]
- I have run "Reimport All Maven Projects": 

![image](https://user-images.githubusercontent.com/42252788/44055422-3da2a022-9f3d-11e8-9b8c-51b7ea899f10.png)


- The log indicates is trying to locate a file with no file extension. If it was looking for a .jar, it would find it.

`Failed to deploy '[2018-08-13 21:21:01] Maven build: SimonSays3. Project: simonsays3-discord-212822. Version: auto': Deployment source not found: C:\Users\Ash\IdeaProjects\SimonSays3\target\SimonSays-1.0.`

![image](https://user-images.githubusercontent.com/42252788/44056157-4e46c0e6-9f3f-11e8-92f1-ced664df0046.png)

**Comment by etanshaul** [comment]
aha. Sorry missed the part about the missing `.jar` the first time around.

Basically App Engine standard does not support jar deployments, only exploded wars. Is this something that is possible for you to refactor? If not, you could consider deploying the jar to [App Engine flexible](https://cloud.google.com/appengine/docs/flexible/) instead of App Engine standard.

**Comment by TheEndernaut** [comment]
>     * When you run a `maven package`, does that artifact in the path specified in error in the log exist (`...1.0-SNAPSHOT...`)?

I'm getting this error. What was the fix?

**Comment by etanshaul** [comment]
hi @TheEndernaut . Could you elaborate a bit more one what you are trying to do and the details of the error? When you say you are getting the error too, is this when running a deployment, or doing a `mvn package`? Thanks.

**Comment by gbouras** [comment]
I think this is is still an issue:
Deploying '[2020-05-21 23:11:08] Maven build: test. Project: demo. Version: auto'...
Failed to deploy '[2020-05-21 23:11:08] Maven build: test. Project: demo. Version: auto': Deployment source not found: /Users/.../test-0.0.1-SNAPSHOT.
