### ISSUE TITLE
No web artifacts created for project "created from existing sources" by default

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/google-cloud-intellij#1225]
This is a bit confusing for users who might want to create the project with the discovered Web and GAE Standard support and run dev_appserver.

The run configuration is in error state because there is no artifact selected, or available for selection.

![screenshot from 2017-02-08 12 00 15](https://cloud.githubusercontent.com/assets/3290856/22747848/2a058a06-edf6-11e6-8435-42df0e87539c.png)

The workaround is to go to Module Settings -> Facets -> Web and press the Create Artifact button. Or, alternatively, manually create the artifact in the Artifacts menu, which is even less unintuitive for non-expert IJ users.

It's an unclear whether this is our issue, but something worth looking into to see if we can do anything on our side.

**Comment by etanshaul** [comment]
obsolete (we have helper tools menu items for this now to automatically create the framework support)
