### ISSUE TITLE
Clone button enabled in "existing directory" error state

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/google-cloud-intellij#1226]
Errors out gracefully, but button should probably be disabled in the first place, similarly to the other error states.

![screenshot from 2017-02-08 12 04 54](https://cloud.githubusercontent.com/assets/3290856/22748066/dd0bca02-edf6-11e6-9eee-2e75a3b6324a.png)

**Comment by etanshaul** [comment]
turns out its also a bug with the parent directory field.
