### ISSUE TITLE
Class file is Java 8 but max supported is Java 7

### ISSUE THREAD

**Issue by grembek** [GoogleCloudPlatform/google-cloud-intellij#1230]
Hi,

I am struggling for two days to deploy my code to Google App Engine and I am unable to do so because of the error "Class file is Java 8 but max supported is Java 7". I tried everything I could find on the web and it is very frustrating that I cannot do so. The App can run locally, but fails I deploy it to the remote server. Can you please advise.

I did everything advised in the IntlliJ guide: https://intellij-support.jetbrains.com/hc/en-us/articles/206544879-Selecting-the-JDK-version-the-IDE-will-run-under

I have the sane problem in Eclipse: https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/1365

![screen shot 2017-02-09 at 10 50 17](https://cloud.githubusercontent.com/assets/1566285/22775832/0bb876ce-eeb6-11e6-84e2-22929bb3ab6f.png)
![screen shot 2017-02-09 at 10 46 49](https://cloud.githubusercontent.com/assets/1566285/22775835/0bb9ba34-eeb6-11e6-8cb8-b22da2839c67.png)
![screen shot 2017-02-09 at 10 47 58](https://cloud.githubusercontent.com/assets/1566285/22775834/0bb91cc8-eeb6-11e6-8976-1e657a085c6d.png)
![screen shot 2017-02-09 at 10 49 18](https://cloud.githubusercontent.com/assets/1566285/22775833/0bb926e6-eeb6-11e6-8a6a-594b6b359d3d.png)
![screen shot 2017-02-09 at 10 51 16](https://cloud.githubusercontent.com/assets/1566285/22775831/0bb83632-eeb6-11e6-8702-3f653224377c.png)

Beginning interaction for module default...
0% Scanning for jsp files.
0% Compiling jsp files.
Unable to stage app: Class file is Java 8 but max supported is Java 7: org/eclipse/jetty/apache/jsp/JettyJasperInitializer$1.class in /Users/.../google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/apache-jsp/org.eclipse.jetty.apache-jsp-9.3.14.v20161028-nolog.jar
Please see the logs [/var/folders/24/1d9xwv3536xf_z483zhs_n300000gn/T/appcfg585555938498236650.log] for further information.
Failed to deploy '[2017-02-09 10:45:20] Maven build: replies. Project: replies-server-production. Version: auto': Deployment failed due to an unexpected error while staging the project.

**Comment by patflynn** [comment]
Hi @grembek,

Thanks for reporting this issue in such detail.

My first guess is that you're seeing an open bug we have right now with the App Engine SDK where a misleading error message is provided when you use a Java 7 app with a web.xml configured to servlet 3.1 (which doesn't support Java 7).

Can you check your web.xml?

If your web.xml looks like this:
```
<web-app xmlns="http://xmlns.jcp.org/xml/ns/javaee"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/web-app_3_1.xsd"
         version="3.1">
```
Then you'll have a problem. 

It needs to be updated to:
```
<web-app xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         version="2.5"
  xmlns="http://java.sun.com/xml/ns/javaee"
         xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_2_5.xsd">
```

If that's not your problem, the other thing I'm noting is that you're showing us the IDEA **boot** JDK, which is not the same as the one used by IntelliJ to build your project.

Have you checked your project settings (⌘;) and verify that your project JDK and module JDKs are set to Java 7 language level?

**Comment by chanseokoh** [comment]
Cross-ref: https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/1365

**Comment by grembek** [comment]
The workaround worked by specifying the version of the xml as 2.5

**Comment by patflynn** [comment]
#1231 
#1193

**Comment by atulchavan10000** [comment]
i am using Eclipse neon. in my case it was already 2.5, but when i changed the whole text as suggested by patflynn it worked.

**Comment by narbigcito** [comment]
i am using eclipse Oxigen and my web-app version is 2.5, but is not working, i have the same error "Class file is Java 8 but max supported is Java 7" i am using java 8 but i can't chage to java 7

**Comment by etanshaul** [comment]
@narbigcito is your goal to use java 7, or java 8?

You _can_ use the [Java 8 runtime](https://cloud.google.com/appengine/docs/standard/java/runtime-java8) on app engine standard if you choose.

Could you perhaps post the contents of your appengine-web.xml (stripping out sensitive data)?

**Comment by narbigcito** [comment]
Thanks @etanshaul , adding the following worked:

<runtime>java8</runtime>

**Comment by etanshaul** [comment]
great! thanks for the update

**Comment by elich11** [comment]
Just to be more clear, what fixed it for me is adding the <runtime>java8</runtime> to appengine-web.xml:
Here is the full xml:
<?xml version="1.0" encoding="utf-8"?>
<appengine-web-app xmlns="http://appengine.google.com/ns/1.0">
    <application>myApplicationId</application>
    <version>1</version>
    <threadsafe>true</threadsafe>
    <runtime>java8</runtime>
    <system-properties>
        <property name="java.util.logging.config.file" value="WEB-INF/logging.properties" />
    </system-properties>
</appengine-web-app>
