### ISSUE TITLE
Label color BLACK contrasts with Darkula theme

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/google-cloud-intellij#1237]
When a field gets in an error state, then on a good state, the label foreground colour is set to BLACK, which doesn't play nice with non-default themes.

![screenshot from 2017-02-09 13 39 32](https://cloud.githubusercontent.com/assets/3290856/22798170/f7c05a4c-eece-11e6-86f2-988ee95a86b6.png)

Same thing happens for the Directory Name label. And we're possibly doing it elsewhere in the plugin.

**Comment by patflynn** [comment]
Let's not change label styling to indicate a problem with a field.  I do like highlighting which field is causing problems, but I'm struggling to find examples in the IJ UIs that do this.
