### ISSUE TITLE
The project id must be specified for every Google App Engine deployment

### ISSUE THREAD

**Issue by grembek** [GoogleCloudPlatform/google-cloud-intellij#1238]
Hi,

This is not a big issue, but it is little annoying that every time I deploy a new version of my App in App Engine, I need to specify the "project id" and it is not saved from last deployment nor it is taken from the appengine-web.xml (Where I specified the project id).

Thank you in advance
Shachar

<img width="505" alt="screen shot 2017-02-10 at 17 35 28" src="https://cloud.githubusercontent.com/assets/1566285/22833433/a046390c-efba-11e6-8747-44109cd7b5d8.png">
![Uploading Screen Shot 2017-02-10 at 17.51.24.png…]()

**Comment by etanshaul** [comment]
Thanks for the feedback.

When you are deploying a new version, are you selecting Tools -> Google Cloud Tools -> Deploy to App Engine ?

If so, this creates a new deployment run configuration each time forcing you to re-select the Cloud Project.

If instead, you edit you existing deployment run configuration, you won't have to update the project id again:

![image](https://cloud.githubusercontent.com/assets/1735744/22833930/92ea0830-ef81-11e6-9c8f-57875c012419.png)

**Comment by patflynn** [comment]
It'd like us to improve this.  We should have a module or project level default project that we seed into the project selector.

**Comment by grembek** [comment]
Perfect, thank you so much. I thought the way you expected the developers to deploy is by "Tools -> Google Cloud Tools -> Deploy to App Engine"
