### ISSUE TITLE
Opening our project locally creates VCS changes

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/google-cloud-intellij#1239]
for example, just opening the project and doing nothing causes a local change in `compiler.xml`

We should figure out why and fix it (either commit the change or change the project somehow).

**Comment by etanshaul** [comment]
I think this is related to the addition of error prone:

![image](https://cloud.githubusercontent.com/assets/1735744/22834771/48b3ab7e-ef84-11e6-97e7-d3adc9b08f10.png)

**Comment by patflynn** [comment]
Yeah I've had this flip on me a couple of times.  i.e. I committed the
compiler.xml change, and then reopened the project and it went back to the
way it was before.

**Comment by etanshaul** [comment]
also, the .idea/.name file gets deleted
