### ISSUE TITLE
High rates of user reported deployment failure.

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#1241]
Over half of app engine standard deployment failures are reporting:

"Deployment failed due to an unexpected error while staging the project."

as the cause.   Staging should very rarely fail. 

We're also seeing a consistently high rate of:

"Deployment failed with exit code: 1 Please make sure that you are using the latest version of the Google Cloud SDK. Run ''gcloud components update'' to update the SDK. (See: https://cloud.google.com/sdk/gcloud/reference/components/update.)"

This requires some digging since I would expect the rate of this error to go down over time.

**Comment by etanshaul** [comment]
@patflynn to check analytics again

**Comment by nkibler** [comment]
Duplicate of #1509.

**Comment by AdamSHurwitz** [comment]
I'm receiving this error "**Deployment failed with exit code: 1...**" How do I identify the root of the issue?

**Comment by patflynn** [comment]
Hi @AdamSHurwitz, could you file a [new issue](https://github.com/GoogleCloudPlatform/google-cloud-java/issues/new) including the information mentioned in the template?

thx.
