### ISSUE TITLE
test failure on windows

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#1250]
testSetupWithGoogleSettingSdkConfigured()

```
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
Unexpected exception thrown.
org.gradle.messaging.remote.internal.MessageIOException: Could not write message [EndOfStream] to '/127.0.0.1:55726'.
	at org.gradle.messaging.remote.internal.inet.SocketConnection.dispatch(SocketConnection.java:111)
	at org.gradle.messaging.remote.internal.hub.MessageHub$ConnectionDispatch.run(MessageHub.java:284)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:51)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:51)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
	at org.gradle.messaging.remote.internal.inet.SocketConnection$SocketOutputStream.writeWithNonBlockingRetry(SocketConnection.java:248)
	at org.gradle.messaging.remote.internal.inet.SocketConnection$SocketOutputStream.writeBufferToChannel(SocketConnection.java:236)
	at org.gradle.messaging.remote.internal.inet.SocketConnection$SocketOutputStream.flush(SocketConnection.java:230)
	at org.gradle.messaging.remote.internal.inet.SocketConnection.dispatch(SocketConnection.java:109)
	... 6 more
:google-cloud-tools-plugin:test FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':google-cloud-tools-plugin:test'.
> Process 'Gradle Test Executor 3' finished with non-zero exit value -1073740791
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED
Total time: 1 mins 15.399 secs
Process 'Gradle Test Executor 3' finished with non-zero exit value -1073740791
```

**Comment by joaoandremartins** [comment]
Are you still getting this? Reliably?

**Comment by patflynn** [comment]
I'll have to test this when I get back in front of a windows machine. this
weekend hopefully.

**Comment by patflynn** [comment]
These tests are still failing:

AppEngineFlexibleDeploymentEditorTest. testDockerfileOverride
AppEngineFlexibleDeploymentEditorTest. testDockerfileSectionToggle
AppEngineFlexibleDeploymentEditorTest. testDockerfileStartsDisabledAndWithModuleSetting
AppEngineFlexibleDeploymentEditorTest. testModuleSelector
AppEngineFlexibleDeploymentEditorTest. testPromote_StopPreviousVersion_Flexible
AppEngineFlexibleDeploymentEditorTest. testUpdateServiceName
AppEngineFlexibleDeploymentEditorTest. testValidateConfiguration
AppEngineFlexibleDeploymentEditorTest. testValidateConfiguration_blankDockerfile
AppEngineFlexibleDeploymentEditorTest. testValidateConfiguration_blankProjectSelector
AppEngineFlexibleDeploymentEditorTest. testValidateConfiguration_blankYaml
AppEngineFlexibleDeploymentEditorTest. testValidateConfiguration_directoryDockerfile
AppEngineFlexibleDeploymentEditorTest. testValidateConfiguration_directoryYaml
AppEngineFlexibleDeploymentEditorTest. testValidateConfiguration_emptyUserSpecified
AppEngineFlexibleDeploymentEditorTest. testValidateConfiguration_invalidApplication
AppEngineFlexibleDeploymentEditorTest. testValidateConfiguration_invalidArtifact
AppEngineFlexibleDeploymentEditorTest. testValidateConfiguration_invalidCloudSdk
AppEngineFlexibleDeploymentEditorTest. testValidateConfiguration_notJarOrWarUserSpecified
AppEngineFlexibleDeploymentEditorTest. testValidateConfiguration_nullDockerfile
AppEngineFlexibleDeploymentEditorTest. testValidateConfiguration_nullProjectSelector
AppEngineFlexibleDeploymentEditorTest. testValidateConfiguration_nullUserSpecified
AppEngineFlexibleDeploymentEditorTest. testValidateConfiguration_nullYaml
AppEngineFlexibleDeploymentEditorTest. testValidateConfiguration_unexistingDockerfile
AppEngineFlexibleDeploymentEditorTest. testValidateConfiguration_unexistingYaml
AppEngineFlexibleDeploymentEditorTest. testValidateConfiguration_validJar
AppEngineFlexibleDeploymentEditorTest. testValidateConfiguration_validWar
AppEngineFlexibleStageTest. testStage_customRuntime
AppEngineFlexibleStageTest. testStage_javaRuntime
AppEngineFlexibleStageTest. testStage_noDockerfile
AppEngineStandardDeploymentEditorTest. testValidateConfiguration
AppEngineStandardDeploymentEditorTest. testValidateConfiguration_blankProjectSelector
AppEngineStandardDeploymentEditorTest. testValidateConfiguration_invalidApplication
AppEngineStandardDeploymentEditorTest. testValidateConfiguration_invalidCloudSdk
FlexibleFacetEditorTest. testToggleDockerfileSection
FlexibleFacetEditorTest. testValidateConfiguration_customRuntime
FlexibleFacetEditorTest. testValidateConfiguration_customRuntimeDockerfileIsDirectory
FlexibleFacetEditorTest. testValidateConfiguration_customRuntimeNoDockerfile
FlexibleFacetEditorTest. testValidateConfiguration_customRuntimeNullDockerfile
FlexibleFacetEditorTest. testValidateConfiguration_javaRuntime
FlexibleFacetEditorTest. testValidateConfiguration_malformedYAML
FlexibleFacetEditorTest. testValidateConfiguration_nullYAML
DefaultAppEngineProjectServiceTest. testGetFlexibleRuntimeFromAppYaml_irregularFormatButValid
DefaultAppEngineProjectServiceTest. testGetFlexibleRuntimeFromAppYaml_malformedYaml

**Comment by joaoandremartins** [comment]
Yeah, I'm aware there are a lot of tests failing on Windows. I didn't have time to get to the bottom of it last week, but it's on my radar. I was just wondering if this specific test was still failing, since I don't recall seeing it on my IJ Windows runs.

**Comment by etanshaul** [comment]
@joaoandremartins are you working on this now? If you are tied up with something else I can pick this up.

**Comment by joaoandremartins** [comment]
This is very high on my priority list. I would like to look into the ToolProvider issue before, so you're welcome to take a stab here.

On my first go, I actually had a hard time cracking this and needed to file https://youtrack.jetbrains.com/issue/IDEA-169953. It would be interesting to see if you can make further progress.

**Comment by etanshaul** [comment]
ok - I'll give it a go
