### ISSUE TITLE
Adding GAE support to new module resets existing GAE run configurations

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/google-cloud-intellij#1272]
This was tested with deployment run configs, but it should also happen with local run and debugger for Standard.

To reproduce, just add Standard support to a module, fill in a run config and add another one. The existing run config will be reset.

When the Flex facet lands, this will also happen when Flex support is added, then removed, and added again.

**Comment by etanshaul** [comment]
this doesn't happen for local dev run configs as it checks for existing configurations.

I'm going to take the approach of having a single run config (1 deploy, 1 local run etc.) per project, and not having multiple of each for each module. Within a single run config artifacts can be selected from different modules so it would be unnecessary.
