### ISSUE TITLE
Considering implementing UX improvements

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/google-cloud-intellij#1275]
https://docs.google.com/a/google.com/document/d/15dXu1982AErNTPsqimZcI_urWNDZN0Hjypc44F8aFCs/edit?usp=sharing

**Comment by joaoandremartins** [comment]
Relevant stuff at the bottom of the document.

**Comment by etanshaul** [comment]
using #1477 to track this
