### ISSUE TITLE
Cloud Debugger: Multiple 'Targets' showing up with the same name and no version. 

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#1278]
I'm trying to test the cloud debugger for a project and seeing the target field populated by a bunch of duplicate elements called 'projectName' with no version info.

Unclear if this is an error on our side or the CDB side.

![img_20170228_120714](https://cloud.githubusercontent.com/assets/7862557/23415871/a3a6a8fa-fdae-11e6-949b-cb2fa5e82564.jpg)
(yeah that's a photo of my screen. Don't ask)

**Comment by patflynn** [comment]
I've confirmed the backend is not returning the expected labels here.  On our side the issue is that if the 'description' field only contains the project name, we just display that.  Some kind of 'unknown..' might make more sense.

**Comment by joaoandremartins** [comment]
CDB has been returning an entry only with the name of the project for a while. I'd noticed before, but never got a chance to dig into it.

Loving the picture of your screen.

**Comment by patflynn** [comment]
this was fixed on the backend
