### ISSUE TITLE
Allow Java 8 language level for Standard if runtime in appengine-web.xml is java8

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/google-cloud-intellij#1291]
We should disable the suggestion to enforce language level 7.

We should remove blacklist.

We should allow servlet 3.1, along with 2.5, and expression language 2.2.

**Comment by patflynn** [comment]
java 7 is already only enforced for != runtime java 8.

I'm not sure about the whitelist.  I thought java8 kept some sandbox constraints but we should check with @ludoch 

+1 to not enforcing servlet 2.5 for runtime java 8.  Ideally an inspection/quickfix that checks for this.  I think we may have an issue open already. Probably worth opening an issue specifically for that. @etanshaul talked about this before, so it may already exist.

**Comment by joaoandremartins** [comment]
Just realised the common library uses AppEngineDescriptor. https://github.com/GoogleCloudPlatform/appengine-plugins-core/blob/b36e2b313c332d2664f8f8c715e1e94172d60eb2/src/main/java/com/google/cloud/tools/appengine/AppEngineDescriptor.java

We should probably start making use of it.

**Comment by joaoandremartins** [comment]
@ludoch is telling me there aren't constraints, and it should be removed

**Comment by ludoch** [comment]
I am at the desk next to João. Where are you? :-)

**Comment by etanshaul** [comment]
related: https://github.com/GoogleCloudPlatform/google-cloud-intellij/issues/1231

**Comment by etanshaul** [comment]
and yes, as @patflynn it is on my radar (but not yet started) to enhance support for the servlet version + java runtime version compatibility.

**Comment by patflynn** [comment]
Just as a note that we should prefer our IJ native AppEngineStandardWebApp
descriptor over the common library unless there's some issue that makes it
inadequate.

**Comment by joaoandremartins** [comment]
Is the blacklist removed for Java 8?

**Comment by patflynn** [comment]
I'm not sure. I think it may be gone or at least different. Did you on Ludo have a chance to discuss  it?
