### ISSUE TITLE
Clicking on _ah/admin link causes DevAppServer2Delegate to ApiProxyLocal cast exception

### ISSUE THREAD

**Issue by branflake2267** [GoogleCloudPlatform/google-cloud-intellij#1294]
After running the App Engine server, clicking on admin link causes exception. 
```
com.google.appengine.tools.development.devappserver2.DevAppServer2Delegate cannot be cast to com.google.appengine.tools.development.ApiProxyLocal
```

I filed the full details of the issue here: https://github.com/GoogleCloudPlatform/appengine-maven-archetypes-java/issues/61

It might be a classpath issue related to how it's configured in the archetype.

**Comment by branflake2267** [comment]
It appears that the admin is located on: http://localhost:8000/instances. I didn't expect the admin dashboard to be located on this link. I'm not sure what to do with this now.

**Comment by chanseokoh** [comment]
This is a known issue in dev appserver2. The admin console is by default at http://localhost:8000/, which is shown in the server start log. It's a bug that the log also shows a link with _ah/admin.

https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/236

**Comment by branflake2267** [comment]
Ah ha, and it's obvious stated too. :)

**Comment by patflynn** [comment]
Yeah, this should be fixed by the move back to devappserver1

**Comment by khulan8824** [comment]
I was getting the same error today. But apparently, you can check it from the adminserver localhost:8000/datastore
