### ISSUE TITLE
Need a way to support EAP IntelliJ releases

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#1302]
our plugin is broken on 2017.1 EAP right now due to a breaking API change: com.intellij.ide.ui.laf.darcula.DarculaUIUtil.paintFocusRing(Ljava/awt/Graphics;IIII)V

Ideally we'd be able to release versions of our plugin which support the EAP.  One potential way is to have an EAP branch with CI and do releases from it that target only the EAP version and up.

**Comment by etanshaul** [comment]
Its worth investigating too if we can implement a fix that is also backwards compatible so we don't have to maintain multiple release branches. I'll look.

**Comment by etanshaul** [comment]
I'm thinking your suggestion makes sense and we should create a new protected `2017` branch, based off the point where we last released master. We can then do a release from there and have 2017 covered. Once we decide to have our releases target only 2017 we can then migrate this branch to master. (there may be some overlap where we'd want to push releases for both 2016 and 2017 until adoption picks).

**Comment by etanshaul** [comment]
How does that sound to you guys? @joaoandremartins I'd then change the target branch of your PR (https://github.com/GoogleCloudPlatform/google-cloud-intellij/pull/1296) and merge it into 2017 and do a release from there.

**Comment by patflynn** [comment]
SGTM.

**Comment by joaoandremartins** [comment]
SGTM

**Comment by etanshaul** [comment]
fixed: see https://github.com/GoogleCloudPlatform/google-cloud-intellij/pull/1313

we now have a protected 2017 branch from which we can release 2017+ versions. We can use a similar mechanism anytime we need to support >1 release versions of our plugin.
