### ISSUE TITLE
App Engine Flex custom runtime should allow the user to specify the Docker directory instead of Dockerfile path

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#1304]
@meltsufin 
@loosebazooka 
@nbashirbello 
@joaoandremartins 

I believe the build tools now use a directory as the input to the docker part of staging.

**Comment by loosebazooka** [comment]
Yeah for pure flex deployments. This is not true for compat style deployments.

**Comment by joaoandremartins** [comment]
What to do in case the provided directory doesn't contain a Dockerfile? Allow its creation like we've been doing til now and error if the provided directory doesn't contain one? Or if it doesn't, use gcloud gen-config to generate one?

**Comment by joaoandremartins** [comment]
It would also be good in the future to provide the rationale for this decision, just so I'm not running in the dark. What's the motivation? Get more files required by Docker from that same directory?

**Comment by patflynn** [comment]
yep. People may want to include more than just their archive in the final
image.

gen-config runtime detection won't work on source, so that's not a good
option unless we can tell the command exactly what kind of runtime we want
it to generate. (which would be nice)

**Comment by nbashirbello** [comment]
Wanted to confirm the behavior of the Flex facet UI when we only save the dockerfile directory as opposed to the dockerfile path. I am leaning towards leaving the Flex facet UI the same, i.e having the Dockerfile textbox and the generate button that generates a new dockerfile. But on save, we only save the directory of the selected or newly generated Dockerfile and when we open the Flex facet UI, we populate the dockerfile textbox with the dockerfile directory and append “/Dockerfile” to it. Thoughts?

**Comment by chanseokoh** [comment]
@nbashirbello that approach needs the assumption that the filename should always be `Dockerfile`. Do we have such a guarantee? (I'm thinking maybe yes in our App Engine story.) If yes, the current `Dockerfile` path field should be preventing manually entering or selecting a file whose name is not `Dockerfile`. Is it the case?

**Comment by patflynn** [comment]
I think that sounds a little weird.  I wouldn't understand that all the
files in the directory would be copied in to the staging folder if I just
saw the full Dockerfile path.

**Comment by nbashirbello** [comment]
@patflynn Are you talking about the deployment dialog?
<img width="1082" alt="screen shot 2017-05-05 at 2 30 53 pm" src="https://cloud.githubusercontent.com/assets/6805942/25759230/8a6deed2-319f-11e7-9356-6467fd7a6b08.png">
Ignore the actual text in the Dockerfile textbox

**Comment by patflynn** [comment]
I'm talking about both the deployment run config and the facet.

**Comment by nbashirbello** [comment]
@patflynn 

So you want both the deployment run config and facet ui to have a dockerfile directory textbox? If yes, what would you like to happen to the generate button in the facet ui?

**Comment by patflynn** [comment]
This is basically the UX that Etan is mocking up for review.  In the
meantime you could rename the button to 'generate Dockerfile' or hide the
button all together?

**Comment by etanshaul** [comment]
closed by #1443
