### ISSUE TITLE
CloudSdk Path resolution throws exception when sdk < min version

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/google-cloud-intellij#1325]
If the CloudSdk on the path is < the required minimum version, then an exception is thrown (on boot):

![image](https://cloud.githubusercontent.com/assets/1735744/24511838/ce978d24-153a-11e7-9565-0abe7b481074.png)

**Comment by etanshaul** [comment]
May not be related to minimum version. I am getting this error regardless of if the SDK is updated or not. Possible regression in updated version of core lib.

**Comment by etanshaul** [comment]
This was fixed in a later release of core lib:
https://github.com/GoogleCloudPlatform/appengine-plugins-core/commit/dc16ffaf5890a5b3414861a6c45a7c72a3bfe6ac

Since the version bump hasn't yet happened in master (but has in 17.2 and 2017), keeping open for tracking.

**Comment by patflynn** [comment]
@etanshaul ready to close?

**Comment by etanshaul** [comment]
Yes it's fixed
