### ISSUE TITLE
Add a Checkbox to allow deploying all App Engine configs at deployment

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#1329]
This is a workaround until we have better tooling for deploying individual service configs.

related to: #1171

**Comment by patflynn** [comment]
@etanshaul 
@joaoandremartins 

what do you guys think about getting this into the maintenance release?

**Comment by joaoandremartins** [comment]
All existing configs? And show which ones exist in the appengine folder?
Why the maintenance folder?
When are we planning to release 2017.3?

**Comment by patflynn** [comment]
> All existing configs?
yep
> And show which ones exist in the appengine folder?
no
> When are we planning to release 2017.3?
we can talk about versioning offline.

**Comment by etanshaul** [comment]
do you mean deploying these separately from the artifact?

**Comment by patflynn** [comment]
I mean deploying them with the artifact. At the moment we only deploy
app.yaml as far as I know.

**Comment by etanshaul** [comment]
@patflynn is this really not a dup of #1346? I'm trying to figure out if this should be closed.

**Comment by patflynn** [comment]
@etanshaul yeah. We just need to merge this into master.

**Comment by etanshaul** [comment]
ok, I think we can close it then since 17.2 / 2017 is what is released. So its technically fixed.
