### ISSUE TITLE
Deployment Run Config: Service name can be stale.

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#1331]
steps to reproduce:

1) add a backend.yaml to an app engine flex project with `service: backend`
2) create a flex deployment run config
3) check 'use a different app.yaml' and select backend.yaml.
4) observe that the 'remote configuration: service' UI continues to name the service 'backend'.

if click apply and close and reopen the configuration the service name displays correctly.

**Comment by joaoandremartins** [comment]
I can't reproduce on Linux.
To be clear, 1) you had an app.yaml file with service default, 2) generated a backend.yaml with service: backend and 3) used app.yaml override to point to that new file.
Whenever I do this, the service gets correctly updated..

**Comment by joaoandremartins** [comment]
Actually, I do see that when I uncheck the override button, the service isn't updating. That needs to be fixed.
