### ISSUE TITLE
Suggestions for tweaking the App Engine deployment UI

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#1333]
Here's the current UI layout for Flex deployment for reference:

![screenshot from 2017-03-31 13 11 26](https://cloud.githubusercontent.com/assets/7862557/24561124/a09f288a-1613-11e7-9302-a2d4ce050746.png)

I've sketched a couple of mocks that I think would be closer to the underlying ontology of the app engine flex plaftorm.

For `runtime: java`:
![flex - runtime java](https://cloud.githubusercontent.com/assets/7862557/24560538/2c02ecc0-1611-11e7-8689-b1aa671cb1f2.png)

for `runtime: custom`:
![flex - runtime custom](https://cloud.githubusercontent.com/assets/7862557/24560571/4ada148e-1611-11e7-8c27-993c712fda1d.png)

for user provided app.yaml with `runtime: custom`: 
![flex - custom app yaml](https://cloud.githubusercontent.com/assets/7862557/24560818/3f41d4ee-1612-11e7-919f-d25f364bcc16.png)

Tweaks

- Move env as a child of deployment source, since that's the field that drives the env value.
- Move region under Project for the same reason
- Rename 'Remote configuration' to 'Deployment Parameters' to more closely resemble the underlying platform model. e.g. things that are passed as parameters to the deployment vs configured in app.yaml.
- Rename 'Configuration files' to 'Service configuration' ..  this name can probably be improved, but it's confused because of the platform model being murky more than anything. 
- move app.yaml configuration above the deployment config, as it feels a bit more 'primary'. If you were doing this as a wizard with steps, I think that first you would ask about what you're deploying, and you would wait to ask them about the parameters to deployment for the last step. 

LMKWYT.

**Comment by patflynn** [comment]
Another thing of note is that if the user is using the facet flex configuration, i.e. 'use a different app.yaml is not checked', then they do not have the option of overriding the Dockerfile.

**Comment by etanshaul** [comment]
Regarding you last comment, I think you can. Are you sure you have a runtime: custom app.yaml? I just tested it.

**Comment by elharo** [comment]
FWIW, Eclipse uses a combo box rather than a pop for the project name/ID because we believe some users will have access to >= 100 of these, at which point a popup becomes annoying.

**Comment by patflynn** [comment]
@etanshaul yes you can in the current implementation.  I should have been more clear.  In the proposed changes it would not be possible.

**Comment by patflynn** [comment]
@elharo I believe our project selector qualifies as a combobox.

**Comment by etanshaul** [comment]
yes it is a combobox (a pop up combobox). its fixed max-height so if there are 100s of projects it just scrolls

**Comment by joaoandremartins** [comment]
I'm not sure about Dockerfile's indentation to the right.
I think it'd be more fluent at the same level as app.yaml.

Where do we stand regarding Rui's suggestions? Should your suggestions replace hers?

**Comment by etanshaul** [comment]
I'm in favor of these UX updates. I like how it hides the module / facet concept from the user (e.g. currently we have "use app.yaml from module..").

I think that not being able to override the Dockerfile unless the app.yaml is overriden seems a bit arbitrary. But we can work that into these changes if we decide it is useful.

Does app.yaml & Dockerfile really belong under "Service Configuration" and not "Deployment Parameters"?

**Comment by patflynn** [comment]
On Mon, Apr 3, 2017 at 10:58 AM, Etan Shaul <notifications@github.com>
wrote:

> I'm in favor of these UX updates. I like how it hides the module / facet
> concept from the user (e.g. currently we have "use app.yaml from module..").
>
> I think that not being able to override the Dockerfile unless the app.yaml
> is overriden seems a bit arbitrary. But we can work that into these changes
> if we decide it is useful.
>
> Does app.yaml & Dockerfile really belong under "Service Configuration" and
> not "Deployment Parameters"?
>
It's a good question. I'm not delighted with the naming, but I want to draw
a distinction between the parameters to deployment, e.g. flags to gcloud,
and configuration that are part of the application's source, e.g. things
that would show up in the facet.

**Comment by etanshaul** [comment]
using #1477 to track this
