### ISSUE TITLE
AE Flex Facet UI: Should we hide Dockerfile config when runtime  != custom

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#1334]
I may have forgotten or missed a conversation about this, but I initially thought we wanted to hide the 'Dockerfile' configuration in the Flex facet unless the runtime was set to 'custom'.  Flex tries to hard to hide docker from the user for non-custom scenarios, so ideally the user wouldn't see this field unless they had explicitly decided to go down that path.

Another thing that looks like a bug is that the Dockerfile shows up as configured except greyed out when the app.yaml is set to custom and the project has a Dockefile under ../src/main/docker.  This is confusing because it could give the impression that the Dockerfile is being used, but just can't be changed.  Hiding the configuration completely would also fix this bug.

Doing something similar to what's proposed for the deployment configuration here: #1333  could be nice. So that the runtime is displayed, and if it's custom, the dockerfile selection UI is displayed as a child of that UI element.

**Comment by joaoandremartins** [comment]
The decision was to hide Dockerfile on runtime != custom from the deployment UI, but not from the facet, so as to decrease the amount of "magic" to the users. i.e., why was Dockerfile there before and why is not there now? What do I need to do to get it back there?

Why do you say that Flex "tries hard to hide docker" for non-custom scenarios?

Dockerfile will always be set to something, even if grayed out, unless the user sets it to an empty value. The caption underneath the Dockerfile textbox, when it's disabled, attempts to explain the state of things:

![screenshot from 2017-03-31 14 27 05](https://cloud.githubusercontent.com/assets/3290856/24563927/2d9689c2-161e-11e7-90c4-20b8653c9346.png)

There might be something I'm missing, but #1333 seems to only focus on the deployment UI.

All in all, I still think Dockerfile being always there in facet for the purposes of reducing mysticism is still a valid decision.

**Comment by patflynn** [comment]
On Fri, Mar 31, 2017 at 2:28 PM, João Martins <notifications@github.com>
wrote:

> The decision was to hide Dockerfile on runtime != custom from the
> deployment UI, but not from the facet, so as to decrease the amount of
> "magic" to the users. i.e., why was Dockerfile there before and why is not
> there now? What do I need to do to get it back there?
>
> Why do you say that Flex "tries hard to hide docker" for non-custom
> scenarios?
>
App Engine Flex does not require docker or Dockerfiles and emphasizes their
standard runtimes.  It's weird and can be confusing to have a configuration
element visible which doesn't apply to the use-case.

> Dockerfile will always be set to something, even if grayed out, unless the
> user sets it to an empty value. The caption underneath the Dockerfile
> textbox, when it's disabled, attempts to explain the state of things:
>
[image: screenshot from 2017-03-31 14 27 05]
> <https://cloud.githubusercontent.com/assets/3290856/24563927/2d9689c2-161e-11e7-90c4-20b8653c9346.png>
>
> In the above example a user could still misconstrue this to indicate that
the path is being used but they simply can't change it.  Many user's will
have a lot less complete understanding of how the platform works.

> There might be something I'm missing, but #1333
> <https://github.com/GoogleCloudPlatform/google-cloud-intellij/issues/1333>
> seems to only focus on the deployment UI.
>
Yes it is about the deployment UI, but the service configuration widget
treats the same subject as the facet.

> All in all, I still think Dockerfile being always there in facet for the
> purposes of reducing mysticism is still a valid decision.
>
Look this is clearly a subjective thing. I think we could make it work
either way with some UX dexterity, but I prefer tailoring the visible UI to
the use-case instead of displaying all possible configuration elements
regardless of their applicability.  This is one of the key benefits of a
dynamic UI vs a CLI.

**Comment by joaoandremartins** [comment]
Whenever Dockerfile is grayed out, its value should never be used.
If it is being used anywhere, then it's a bug.
