### ISSUE TITLE
Dockerfile generation always generates a war compatible file

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/google-cloud-intellij#1339]
Since our ae flexible updates it appears as though war is hardcoded always for Dockerfile generation regardless of the type of artifact produced.

**Comment by joaoandremartins** [comment]
Yes, because the facet doesn't know about run configuration specific data, therefore, it doesn't know about the archive the user is trying to deploy.
All artifacts that aren't "Filesystem WAR or JAR" should be WAR.

**Comment by etanshaul** [comment]
I'm with you on the first sentence - that the facet may not know (although its still a problem worth trying to solve).

But its not true that all artifacts that arent filesystem war/jar should be war.

Prior to the flexible refactoring since we were generating the Dockerfile from the deployment config we didn't have this problem, so we did lose some functionality.

**Comment by joaoandremartins** [comment]
A light fix could be to add a combo box or so, with JAR or WAR, for the artifact for which to generate a Dockerfile to.

**Comment by etanshaul** [comment]
yeah, I agree. if we can't quickly figure out how to do it automatically that's an acceptable alternative.

**Comment by patflynn** [comment]
Ah, this was easier to do at deploy time when we knew what the deployment artifact was.
