### ISSUE TITLE
Add option to deploy all configs with App Engine Standard deployment

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#1346]
When a user is deploying a standard app, they should be able to have us automatically deploy all the cron.xml, dos.xml, etc files during deployment.

**Comment by chanseokoh** [comment]
Dup of #1329?

**Comment by patflynn** [comment]
nah, not dupe, this is just to match current Eclipse behavior.  The other
bug is to give user granular control over deployments of each service type.

**Comment by etanshaul** [comment]
fixed via #1353
