### ISSUE TITLE
Label for deploying all standard assets (cron, indexes etc.) is not hidden for flex

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/google-cloud-intellij#1362]
The checkbox is properly hidden, but the label is not.

**Comment by etanshaul** [comment]
![image](https://cloud.githubusercontent.com/assets/1735744/25018986/fd8d3878-2056-11e7-898b-b8320609ac23.png)

**Comment by chanseokoh** [comment]
Question: is deploying such config files not applicable for flex? I have been speculating that people could have, e.g., `cron.yaml` and other config files under `src/main/appengine`, and I could just list those files as deployables along with the deploy artifact when running `gcloud app deploy`.

**Comment by etanshaul** [comment]
good question. we need to check this.

**Comment by patflynn** [comment]
@loosebazooka I think they're supporting that model for flex in the build plugins.

**Comment by etanshaul** [comment]
should we also support this in the IDEs (deploying these assets for flex projects)?

**Comment by patflynn** [comment]
I think this sounds reasonable.

**Comment by etanshaul** [comment]
Yea - if its supported then theres no reason to exclude flex I guess.

Do you know off hand if all of the above (dos, dispatch, cron, queues, indexes) is applicable for flex as well?

**Comment by etanshaul** [comment]
closing - this was fixed (although we are reverting this since it is applicable to flex)
