### ISSUE TITLE
Environment variables are ignored

### ISSUE THREAD

**Issue by sparhomenko** [GoogleCloudPlatform/google-cloud-intellij#1364]
Our application has several environment variables defined in `appengine-web.xml`, eg. `ENDPOINTS_SERVICE_NAME` [required](https://cloud.google.com/endpoints/docs/frameworks/java/required_files#appengine-webxml) by Google Cloud Endpoints Framework. After Google Cloud Tools switched to Dev App Server 1 in #1345 the application startup started failing with:
>com.google.appengine.tools.development.EnvironmentVariableChecker$IncorrectEnvironmentVariableException: One or more environment variables have been configured in appengine-web.xml that have missing or different values in your local environment. We recommend you use system properties instead, but if you are interacting with legacy code that requires specific environment variables to have specific values, please set these environment variables in your environment before running.
>[Mismatch environmentVariableName=ENDPOINTS_SERVICE_NAME environmentVariableValue=null appEngineWebXmlValue=_value_ appEngineWebXmlFile=_path_/WEB-INF/appengine-web.xml]

Defining environment variables in the run configuration settings ("Startup/Connection" tab, "Run" configuration, "Environment Variables" section) had no impact. Since IntelliJ IDEA is a GUI app `~/.bash_profile` is also ignored. We ended up configuring them in `~/Library/LaunchAgents/environment.plist` as recommended [here](https://stackoverflow.com/a/26586170).

Two questions:
1. Google Cloud Tools with Dev App Server 2 did not require any additional environment configuration, why is it now required with Dev App Server 1? It does add a certain maintenance overhead as all developers now need to adjust their environment when `appengine-web.xml` changes.
2. Why are the environment variables defined in run configuration settings ignored?

**Comment by etanshaul** [comment]
@sparhomenko we are looking into this

**Comment by patflynn** [comment]
@etanshaul I'm thinking we should also wire the environment tab variables into the run config for now.

**Comment by etanshaul** [comment]
agree. I'll get to this soon. I'll file an issue if there isn't one.

**Comment by etanshaul** [comment]
actually, this can be the issue to track that effort

**Comment by patflynn** [comment]
I think you can just use this issue

**Comment by patflynn** [comment]
:)
