### ISSUE TITLE
Flex migration - run config is lost

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/google-cloud-intellij#1366]
Start with a flex project on a build before the flex updates. Create a deployment run config with a bunch of settings.

Swap over to master, reopen the same project.

1) The run config is empty and no deployment sources are available yet -> this is OK because framework support has not been added yet. Add framework support (either manually, or via the detection if you had an app.yaml). 
_Update: on second thought, some guidance here would be nice - the user wouldn't necessarily know to add framework support, especially if there is no automatic detection. Perhaps some wording on the deployment config, or through documentation._

2) Re-open the run config. Its empty. 

Ideally, the run config that was created earlier with the old build should be restored.

**Comment by patflynn** [comment]
@etanshaul could we automatically add a flex facet as part of the migration?

**Comment by etanshaul** [comment]
Yes, good idea. I'll do this on a separate PR.
