### ISSUE TITLE
In IC, generating the app.yaml from the flex framework or facet dialog fails

### ISSUE THREAD

**Issue by nbashirbello** [GoogleCloudPlatform/google-cloud-intellij#1378]
- Occurs on the master branch

**Comment by etanshaul** [comment]
ah so this is in community. May be due to how the code locates the appropriate directory via the content roots. Although I would have expected that to work in IC too.

**Comment by nbashirbello** [comment]
It looks like DefaultAppEngineProjectService#generateFromTemplate is always generating the app.yaml in src/main/appengine regardless of what the user specifies the app.yaml directory to be.

**Comment by etanshaul** [comment]
oh wow, you're right. This should be its own bug. I'll open one.

**Comment by nbashirbello** [comment]
Open a bug or open an issue? Are those different?

**Comment by etanshaul** [comment]
same thing

**Comment by nbashirbello** [comment]
[Issue 1387](https://github.com/GoogleCloudPlatform/google-cloud-intellij/issues/1387) is the cause of this bug

**Comment by nbashirbello** [comment]
Fixed by #1420
