### ISSUE TITLE
Template generation forces a directory regardless of selection

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/google-cloud-intellij#1387]
It looks like DefaultAppEngineProjectService#generateFromTemplate is always generating the app.yaml in src/main/appengine and the dockerfile in src/main/docker regardless of what the user specifies the app.yaml and docker directory to be.

**Comment by etanshaul** [comment]
this applies to both Dockerfile and app.yaml

**Comment by nbashirbello** [comment]
Fixed by #1420
