### ISSUE TITLE
Google Account Login on HIDPI screen to small

### ISSUE THREAD

**Issue by bravous** [GoogleCloudPlatform/google-cloud-intellij#1391]
When on a HiDPI screen on fedora (25) the google avatar is shown too small (should be 2x), see image:

![image](https://cloud.githubusercontent.com/assets/1059812/25621187/e2192ecc-2f50-11e7-9dd8-c1ddf093d4e6.png)

**Comment by patflynn** [comment]
@bravous thanks for the report! We'll check it out.

**Comment by etanshaul** [comment]
interestingly im not able to reproduce the original problem on my macbook
