### ISSUE TITLE
Cannot apply changes in deployment run configuration if there is a validation error

### ISSUE THREAD

**Issue by chashnikov** [GoogleCloudPlatform/google-cloud-intellij#1407]
If I create a 'Google App Engine Deployment' run configuration in 'Run/Debug Configuration' dialog I cannot apply the changes and close the dialog if some validation error is reported (e.g. if project isn't specified or there is some problem in the Cloud SDK). So I need to either fix the problem (but it may be not trivial, e.g. in order to specify a project I may need to firstly create it) or press 'Cancel' in the dialog losing all other changes I did in it. It's very inconvenient. 

It's better to use a different approach, look like it's done for Application run configurations for example: if you don't specify Main class for an Application run configuration IDEA will show an error message, but it'll allow you to apply the changes and close the dialog. However you try to run such a configuration, an error will be shown.

**Comment by chashnikov** [comment]
The problem is that you throw an exception from com.google.cloud.tools.intellij.appengine.cloud.AppEngineDeploymentRunConfigurationEditor#applyEditorTo method. You should do this only in very rare cases when it is indeed not possible to **save** the entered data. In order to validate configuration you need to implement checkConfiguration method in com.google.cloud.tools.intellij.appengine.cloud.AppEngineDeploymentConfiguration and throw exception from it.

**Comment by patflynn** [comment]
Let's make this bug about making sure we do this consistently across all editors.
