### ISSUE TITLE
Deployment configurations created in old App Engine plugin are shown as Unknown in Cloud Tools plugin

### ISSUE THREAD

**Issue by chashnikov** [GoogleCloudPlatform/google-cloud-intellij#1409]
I created an App Engine project using the old Google App Engine plugin bundled with IntelliJ IDEA 2017.1. After that I installed Google Cloud Tools plugin (17.2.4_2017), disabled the old plugin as it suggested and opened that project. IDEA suggests me to convert the project, but after that my 'Google App Engine Deployment' run configurations are shown as Unknown in 'Run/Debug Configurations' dialog, so I need to recreate them.

**Comment by chashnikov** [comment]
This happens because old configurations are of 'google-app-engine-deploy' type ('type' attribute of 'configuration' element the run configuration xml file), but the new has 'gcp-app-engine-deploy' type. Maybe you can automatically convert them to the new type. There is a special com.intellij.conversion.ProjectConverter#createRunConfigurationsConverter method for that in IntelliJ API, you can override it in AppEngineFacetMigrationConverterProvider (it makes sense to renamed this class and update its description then).

**Comment by etanshaul** [comment]
Probably already fixed by #1280 which is in master (not yet released). Will confirm today.

**Comment by etanshaul** [comment]
This is the identical issue (#1040, see https://github.com/GoogleCloudPlatform/google-cloud-intellij/issues/1040#issuecomment-283084055 for the comment about the deployment config) and same fix as suggested (#1280). Will be available in next master release. Closing.

**Comment by patflynn** [comment]
can we cherry pick this into the maintenance branches?  It'd be nice to
have this fixed in the next release.

**Comment by etanshaul** [comment]
yeah. I can do that.
