### ISSUE TITLE
Deployment list gets wiped out if an IDE window is opened or closed

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/google-cloud-intellij#1432]
This is especially frustrating with long-running deployments like Flex, that disappear from the list and there is no indication of when they're finished, or the exit status. There is also no exception thrown or error logged anywhere. The Application Servers window only goes green for a bit. This is happening on Linux.

To reproduce, open or close an IDE window in another project with a populated deployment list. I only tried to open projects in the same window, although it might also be reproducible by opening in a new window.

**Comment by etanshaul** [comment]
I'm able to reproduce this on window close. It _may_ be related to the logic we have that we have that cleans up running deployments when the IDE is closed and it not being smart enough to know that there is still another IDE window open (and the deployments created with window A get wiped out even if a new window B is closed).

**Comment by patflynn** [comment]
Just reproduced this. We really need to fix it.
