### ISSUE TITLE
The App Engine Flex create new wizard fails when creating a project with app.yaml

### ISSUE THREAD

**Issue by nbashirbello** [GoogleCloudPlatform/google-cloud-intellij#1442]
In the create new project wizard, selecting GAE flex and then “Create app.yaml” causes an error in DefaultAppEngineProjectService#generateFromTemplate that the app.yaml already exists and fails the new project creation

**Comment by etanshaul** [comment]
Looks like this happens because of:

"Assertion failed: Access to psi files should be performed only after startup activity"
