### ISSUE TITLE
New web project has Google App Engine Stnadard Local Server run config even though App Engine was not one of the selected frameworks

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#1444]
found in 17.2.5_2017

steps to reproduce:
1) use new project wizard to create a new project from java enterprise -> web.
2) observe the newly created project has a ae standard local run config.

**Comment by etanshaul** [comment]
@patflynn could you please try this again? Making sure to first do a clean.

Also, make sure you don't have Google App Engine selected under the App Server dropdown:

No app server selected:
![image](https://cloud.githubusercontent.com/assets/1735744/26314966/9e420f7e-3edd-11e7-8f46-1f87301aa41d.png)

App Engine app server selected:
![image](https://cloud.githubusercontent.com/assets/1735744/26314990/b3a3ce98-3edd-11e7-83b6-c033201130ac.png)

If you do have it selected like the last screenshot, it will create the dev server (as expected).

**Comment by patflynn** [comment]
Is there a way to filter out the App Engine local server for non app engine
based projects?

**Comment by etanshaul** [comment]
do you mean filter it from appearing in that dropdown? I can check.

**Comment by patflynn** [comment]
yeah.  It wouldn't make sense to select the app engine standard server for
a non app engine standard app.

**Comment by etanshaul** [comment]
agreed. ill check to see what determines which app server is allowed to appear in that dropdown, and if we have control over it.

**Comment by etanshaul** [comment]
Just noting that some of the other app server options that appear here also don't make sense in isolation (with a plain java ee app); spring dm server for instance. Its still configurable, and will create the server run config, but won't work until the project is properly set up.

Another way to think about this is as another avenue towards setting up App Engine support via our plugin (though less user friendly).

wdyt about just leaving it?

**Comment by patflynn** [comment]
I'm not crazy about it.  Can we control if it's selected?

**Comment by etanshaul** [comment]
Looks like we cannot control it from appearing as an option:

`AppServerIntegrationManager.getInstance().getAllIntegrations()`

will return all of the configured app servers (including our app engine server). The platform will then take all of these and add them to the dropdown as configurable options.

**Comment by etanshaul** [comment]
@patflynn given my last comment I'll go ahead and close this. Unless you can think of a workaround and want to keep this open for tracking?

**Comment by etanshaul** [comment]
I _could_ file a feature request with JB to make this configurable. wdyt?

**Comment by patflynn** [comment]
no. let's just close this.
