### ISSUE TITLE
Using the plugin w/  2017.2 EAP rolls back :(

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/google-cloud-intellij#1453]
It is suggesting I roll back to 16.11.6 for some reason.  :(

![screen shot 2017-05-15 at 4 38 21 pm](https://cloud.githubusercontent.com/assets/1136014/26118948/7174fd92-3a20-11e7-82a8-fbda03db439c.png)

**Comment by etanshaul** [comment]
fixed via #1452 to be released in version 17.2.6_2017
