### ISSUE TITLE
Google Account login popup remains visible on top of all windows after sign-in/add account

### ISSUE THREAD

**Issue by nkibler** [GoogleCloudPlatform/google-cloud-intellij#1461]
**As of hash:** 355fe25a55bc40af9ba1dca8ed174d4010d3725d

**Steps to reproduce:**
1. Open IDEA.
1. Click the profile image button to open the Google Account popup.
1. Click the "Sign In" button or the "Add Account" button, whichever is appropriate for your account state.
1. Observe the Google Account popup remains visible on top of the opened browser login window. See the picture below.
![screen shot 2017-05-17 at 12 07 44 pm](https://cloud.githubusercontent.com/assets/14352762/26171869/574302f8-3afb-11e7-8de8-5baa02174de9.png)

**Environment details:**
- macOS Sierra 10.12.4

**Comment by etanshaul** [comment]
@nkibler this is fixed right?

**Comment by nkibler** [comment]
So I didn't explicitly fix it, but now it's not reproducible on my Mac, which was the only platform I saw it on.
