### ISSUE TITLE
Support Jetbrains Rider

### ISSUE THREAD

**Issue by dtretyakov** [GoogleCloudPlatform/google-cloud-intellij#1472]
The is a cross-platform IDE for .NET developers called JetBrains Rider: https://www.jetbrains.com/rider/

It's based on Intellij platform and thus Rider supports plugins from Intellij plugin gallery.

It would be great to support in this plugin Rider IDE as well and add some .NET specific features which are available in Google Cloud Tools for Visual Studio.

**Comment by patflynn** [comment]
Hi Dmitry,

Thanks for the input.  We are looking at ways we can expand our plugin
compatibility to support more Jetbrains IDEs.

Are there any features from Cloud Tools for VS in particular that you would
like to see?

**Comment by dtretyakov** [comment]
@patflynn, you could ask your colleagues from [Cloud Tools for Visual Studio](https://github.com/GoogleCloudPlatform/google-cloud-visualstudio) team about available features. As for me it should allow to control available resources and deploy projects from Rider IDE.

**Comment by mbalsam-refind** [comment]
Any progress on this. Its been 4 years!

**Comment by etanshaul** [comment]
Hey @mbalsam-refind. Which features are you interested in?

Cloud Code does have some Rider support, including:
- Kubernetes explorer (lets you dig into your clusters from the IDE)
- Cloud Run explorer (lets view your Cloud Run services from the IDE)
- Kubernetes and Cloud Run deployment 

Missing is
- Kubernetes debugging support
- App Engine
- Kubernetes and Cloud Run Sample app creation

The above isn't exhaustive, but just trying to give you a better idea. We do need to brush up our docs and messaging to make the support matrix clearer.

**Comment by mbalsam-refind** [comment]
Thanks for the response.

We're looking for
live debugging and the ability to look at stack-traces inside of a k8 container.

The App Engine in not a must have but it would be nice.

If the code sample were just a project in git rather than a template that would suffice.

There are lots of C# developers who dont want to work in vscode.

Thanks for supporting us.
Mitch

**Comment by etanshaul** [comment]
That helps. Debugging is one of those things we are in the early phases of investigation.

> the ability to look at stack-traces inside of a k8 container

With the Kubernetes explorer feature, you can grab logs of your running pod in the cluster, which would contain any stacktraces. Does this capture the need or is there more to it? 

To get logs in Rider for a running pod:
<img width="1318" alt="Screen Shot 2021-03-25 at 6 25 33 PM" src="https://user-images.githubusercontent.com/1735744/112551523-8243ed80-8d97-11eb-8885-f6b6f2b9d199.png">
(Notice on the right panel, the right-click menu on the pod in the explorer tree to stream logs).

Also in the above screenshot you can see our sample Cloud Code .NET app being run on Kubernetes with the plugin. You are correct that it is just a GitHub backed sample which you can access directly here: https://github.com/GoogleCloudPlatform/cloud-code-samples/tree/master/dotnet

**Comment by mbalsam-refind** [comment]
Very nice. Cant wait until its out. Im happy to beta is.
