### ISSUE TITLE
Upgrade from 17.2.6_2017  to latest release 17.6.2, old run configuration cannot be recognised.

### ISSUE THREAD

**Issue by xmeng1** [GoogleCloudPlatform/google-cloud-intellij#1534]
Upgrade from 17.2.6_2017  to latest release 17.6.2, the old run configuration cannot be recognised.

After I upgrade to the new plugin by the balloon of IntelliJ, I found the previous run configuration cannot work. Meanwhile, I got an suggest to enable the old App Engine plugin.

By the way, I find the there is confliction between the Google Cloud Tool with [the ignore plugin.](https://plugins.jetbrains.com/plugin/7495--ignore)

**Comment by etanshaul** [comment]
@xmeng1 thanks for the report. Could you please provide as much detail as possible so I can help with the issue?

What run configuration isn't working? Is it deployment (or local dev server run, etc.)? We made a few changes to the run configurations which may require minor re-configuration. Did you try opening the run configuration and correcting whatever errors are mentioned?

Do you have a screenshot of the suggestion you got to enable the old App Engine plugin? Lastly, I'm not sure what conflicts you got with the ignore plugin, so any more detail you could provide would be great.

**Comment by xmeng1** [comment]
OK
Issue one confliction with git ignore plugin

![selection_034](https://user-images.githubusercontent.com/5753142/27872812-eda0dd98-61a1-11e7-99f6-6e07f416d25f.png)


[idea-plugin-conflict-issue.log.zip](https://github.com/GoogleCloudPlatform/google-cloud-intellij/files/1125252/idea-plugin-conflict-issue.log.zip)

**Comment by xmeng1** [comment]
Issue two the old configuration cannot be used
When open a previous project get this message:
![selection_035](https://user-images.githubusercontent.com/5753142/27872842-0e5138da-61a2-11e7-9bae-1c91cb3e118d.png)

After I click the enable, display the old plugin:
![selection_036](https://user-images.githubusercontent.com/5753142/27872883-2ead5794-61a2-11e7-95ce-016bcda8ca59.png)

And check the run configuration, previous run configuration become the Unkonwn
![selection_037](https://user-images.githubusercontent.com/5753142/27872893-37c43438-61a2-11e7-898e-d09de7e99c2e.png)

[log-old-run-configuration-cannot-be-used.zip](https://github.com/GoogleCloudPlatform/google-cloud-intellij/files/1125259/log-old-run-configuration-cannot-be-used.zip)

**Comment by etanshaul** [comment]
Thanks. I will look into the ignore plugin issue.

Regarding the old plugin and run configuration: from the screenshots you included, it looks like you only have the old plugin enabled (`Google App Engine Integration` is the old one). That run configuration you link to is the run configuration created by the old plugin - the new plugin has its own local dev server configuration. You should try to install the new plugin ("Google Cloud Tools") and disable the old plugin (once you install the new plugin, there should be a prompt asking you to disable the old one - or you can do it manually if you prefer).

If you already tried this, I'd suggest to try to install the new plugin again and make sure that the old one is not installed. If you still have issues around this, if you could list the exact steps you took then I can try and help more.

**Comment by etanshaul** [comment]
see https://github.com/GoogleCloudPlatform/google-cloud-intellij/issues/1535 regarding the conflict with the ignore plugin. Thanks for bringing this to our attention!

**Comment by xmeng1** [comment]
OK got it. Thanks.
