### ISSUE TITLE
After an update to the latest version, for App Engine deployment, deployment type "maven-build-source" doesn't show up in a drop down menu, and only "filesystem-war-jar-module" option is available

### ISSUE THREAD

**Issue by zavale** [GoogleCloudPlatform/google-cloud-intellij#1545]
Google Cloud Tools and Google Account plugin version are 17.6.2
Initelij Ultimate version 2017.1.5

**Comment by etanshaul** [comment]
@zavale. Are you deploying to App Engine flex? If so, with the latest update you need to add the App Engine flex framework support. (This should have auto prompted you to add if you have an app.yaml; but if not or you missed the prompt, follow the next step).

To do this, right click on the root of project in the explorer, then click 'add framework support'. Find the App Engine flexible support (separate from standard) and add it. The maven deployment source should now show up.

If not, or if I mischaracterized your problem, please provide a few more details about your setup.

**Comment by zavale** [comment]
Thanks, @etanshaul - that solved the problem.
