### ISSUE TITLE
Support do Gogland IDE

### ISSUE THREAD

**Issue by cicerocomp** [GoogleCloudPlatform/google-cloud-intellij#1552]
https://www.jetbrains.com/go/

**Comment by patflynn** [comment]
It's under consideration.

**Comment by dmmakita** [comment]
It would really be useful having plugin for jetbrains goland, in order to use google cloud platform. Goland ide is based on intellij, so adapting could be possible?

**Comment by dmmakita** [comment]
I think what I need is those agnostic features cited by @etanshaul, like Cloud Source Rep, Cloud Storage and App Engine

**Comment by patflynn** [comment]
@dmmakita thanks for the feedback.  The App Engine integration unfortunately requires some language level bindings that we won't have available right away.  GCS and CSR integration will work though.

**Comment by dmmakita** [comment]
@patflynn Thank you for the feedbacks. GCS and CSR would be enough for now, I believe. Do you think you will be releasing it soon?

**Comment by etanshaul** [comment]
Hi @dmmakita We don't have an exact timeframe to give at the moment. However we are aiming to make significant progress on this in Q1. I'll make sure to update this thread when we have something more concrete.
