### ISSUE TITLE
No Cloud SDK error in run config window needs to be more descriptive

### ISSUE THREAD

**Issue by nkibler** [GoogleCloudPlatform/google-cloud-intellij#1588]
Now that you can save an invalid Cloud SDK path and the deployment run config validates this path is valid before deploying, we should make it more clear where the problem is by updating the error language. Here's what it currently says:

![screenshot from 2017-08-07 12 55 53](https://user-images.githubusercontent.com/14352762/29037056-fb36e2bc-7b6f-11e7-8722-78adf859da25.png)

... and the problematic field is:

![screenshot from 2017-08-07 12 58 29](https://user-images.githubusercontent.com/14352762/29037104-37df10c2-7b70-11e7-8bcf-accb8f76896b.png)

Selecting the ellipses button on the right opens the following dialog:

![screenshot from 2017-08-07 12 59 05](https://user-images.githubusercontent.com/14352762/29037123-49606012-7b70-11e7-8574-513fca67e1b3.png)

We should improve the experience here to make it more clear from the run config window where the issue is and how to fix it.

**Comment by etanshaul** [comment]
Just a note that a convention we use is that the message should not include any positional references (e.g. click on the server field above) so that the messages are decoupled from the UI.
