### ISSUE TITLE
Crash when deploying with missing auth in the deploy configuration

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/google-cloud-intellij#1595]
Trying to run a deploy before signing into GCP causes this (not seen before by me) modal to show up:
<img width="427" alt="screen shot 2017-08-08 at 2 19 44 pm" src="https://user-images.githubusercontent.com/1735744/29087709-c7fac244-7c44-11e7-90cf-971b8e7c032b.png">

Any subsequent action leads to an IDE crash:
<img width="1101" alt="screen shot 2017-08-08 at 2 21 25 pm" src="https://user-images.githubusercontent.com/1735744/29087742-fa238904-7c44-11e7-898e-21e9a5a3b41a.png">

**Comment by etanshaul** [comment]
thanks to detective work by @nkibler:

1. Start fresh with everything (no user, no deployment config, etc.)
2. Create a deployment config and make it valid. (Type some nonsense into the project field but don't login)
3. Save the config and login via other means (like the widget in the top right)
4. Once logged in, press the run button

**Comment by nbashirbello** [comment]
@etanshaul I don't think this is a problem anymore since you can select an invalid GCP project with the new project selector. I tried to reproduce the bug but couldn't, which is a good thing :)
