### ISSUE TITLE
error stopping app engine deployment (after Google pushed a GAE update 158 to 163)

### ISSUE THREAD

**Issue by dthalsandiego** [GoogleCloudPlatform/google-cloud-intellij#1596]
(Please ensure you are running the latest version of Cloud Tools for IntelliJ with _Help > Check for Updates_.)

- Cloud Tools for IntelliJ version:  17.6.2
- Google Cloud SDK version _(run `gcloud version` on the command line)_:  163.0.0
- OS: Windows 10

**What did you do?**
allowed prompted upgrade from 158.0.0 to 163.0.0

**What did you expect to see?**
no problems / smooth upgrade

**What did you see instead?**
I could no longer deploy my app.  Deployment had worked fine for over a month and then broke immediately when the upgrade was pushed.  **A rollback to 158.0.0 fixed the problem, so it was definitely a breaking change from 158 to 163.**  It continued to work fine locally.  The exception is included in my StackOverflow link below.  Basically, it was a problem compiling JSPs I believe (_jsp.java..."error: package com.google.appengine.api.users does not exist").

(screenshots are helpful)

Here is a link to a StackOverflow question with more details on the bug (and replies from others):
"how fix new error that's stopping app engine deployment? (after Google pushed a GAE update today)"
https://stackoverflow.com/questions/45261960/how-fix-new-error-thats-stopping-app-engine-deployment-after-google-pushed-a

Here is a link to a bug report with JetBeans (they recommeded I file a report here):
https://intellij-support.jetbrains.com/hc/en-us/requests/1043978

**Comment by chanseokoh** [comment]
Sorry for the trouble. I believe you're hitting https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/2202. Please take a look into the link for workarounds.

I was told that this will be fixed in future gcloud releases (hopefully with the next release that should go out this week).

**Comment by dthalsandiego** [comment]
Excellent.  Thanks.  I confirmed my Google Cloud SDK path does indeed have a space ("C:\Cloud SDK\google-cloud-sdk").

**Comment by etanshaul** [comment]
thanks @chanseokoh

will close this issue as it will be fixed in the next gcloud release. @dthalsandiego feel free to re-open if you run into any more issues around this.

**Comment by dthalsandiego** [comment]
Thanks all!  Cheers.
