### ISSUE TITLE
OAUTH Scopes for Deployment have become invalid

### ISSUE THREAD

**Issue by veridian-labs** [GoogleCloudPlatform/google-cloud-intellij#1598]
(Please ensure you are running the latest version of Cloud Tools for IntelliJ with _Help > Check for Updates_)
- Cloud Tools for IntelliJ version: 17.8.1
- Google Cloud SDK version: 166.0.0
- OS: Windows 10 10.0

**What did you do?**
Try to sign-in to my account to select an application for deployment. 

**What did you expect to see?**
Acceptance of account and list of projects in my account

**What did you see instead?**
400. That’s an error.

Error: invalid_scope

Some requested scopes cannot be shown: [https://www.googleapis.com/auth/projecthosting, https://www.googleapis.com/auth/appengine.admin, https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/cloud_debugger]

Request Details

(screenshots are helpful)
_Feel free to deviate from this template as needed, especially if you are submitting a feature request._

**Comment by etanshaul** [comment]
Thanks for the report. We are looking into this.

**Comment by etanshaul** [comment]
@veridian-labs sorry for the inconvenience. If you update the plugin to version `17.8.2` it should be resolved. Closing the issue for now.

**Comment by developer91234** [comment]
![image](https://user-images.githubusercontent.com/43324854/45650570-5dd86d80-bad7-11e8-90b3-74cdd0bd923b.png)

Same issue. To be fair `gcloud init` produces the same result. Amazing job by google.

**Comment by etanshaul** [comment]
Thanks for reporting. We'll fix this asap.

**Comment by etanshaul** [comment]
I confirmed its happening with `gcloud init` and that this issue is beyond the intellij plugin. But it is being looked into and will be addressed. I'll update here when I know more.

**Comment by etanshaul** [comment]
hi @developer91234 the issue should be resolved. Could you please confirm? Thanks again.

**Comment by danielandersson** [comment]
Hi @etanshaul, I can confirm it now works again. Had the same problem as @developer91234 earlier.

**Comment by etanshaul** [comment]
great. thanks @danielandersson
