### ISSUE TITLE
region indicator in deployment UI shows error when project is not selected

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#1607]
The region should just be empty or NA when there's no project specified

![screenshot from 2017-08-11 10 29 38](https://user-images.githubusercontent.com/7862557/29217543-1cae64ac-7e80-11e7-89a6-bc9b47bf7577.png)

of note is that there's some weird position problem as well with the google cloud console link

**Comment by etanshaul** [comment]
fixed via #1682
