### ISSUE TITLE
Staged artifact name field missing placeholder text

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/google-cloud-intellij#1621]
<img width="844" alt="screen shot 2017-08-29 at 11 21 38 am" src="https://user-images.githubusercontent.com/1735744/29829038-610fdbdc-8cac-11e7-85e2-e2d561beae01.png">

This was for an existing run configuration. I expected to see some sort of placeholder text in the field indicating what the name of the artifact will be. Without it, its unclear if the user needs to set it or not.

**Comment by nkibler** [comment]
Can you show me what the selected artifact is?

**Comment by etanshaul** [comment]
<img width="712" alt="screen shot 2017-08-29 at 11 39 00 am" src="https://user-images.githubusercontent.com/1735744/29829915-acd9f46a-8cae-11e7-89a9-d164d87a357b.png">

Its the same regardless of which I select (native or maven). Only user specified fills in the placeholder text after I fill in a filesystem jar/war.
