### ISSUE TITLE
Can't deploy Spring Boot app using Maven artifact

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/google-cloud-intellij#1626]
I have an existing Spring Boot app and I add Flexible support to it.
In the generated run config, I select the Maven artifact, fill out the rest of the config and start it.

Fails with:
```
Deploying '[2017-09-01 15:12:36] Maven build: chatroom-springintegration. Project: sodium-gateway-790. Version: spring-test'...
Failed to deploy '[2017-09-01 15:12:36] Maven build: chatroom-springintegration. Project: sodium-gateway-790. Version: spring-test': Deployment source not found: /usr/local/google/home/joaomartins/workspaces/chatroom-springintegration/target/chatroom-springintegration-0.0.1-SNAPSHOT.
```

The file name is actually called `chatroom-springintegration-0.0.1-SNAPSHOT.jar`.

**Comment by joaoandremartins** [comment]
I understand the flow works with the Filesystem JAR or WAR artifact option, but feel like Maven should work just the same..

**Comment by etanshaul** [comment]
just wondering - are you running the release version of the plugin, or running off of whats in master?

**Comment by joaoandremartins** [comment]
17.8.2

**Comment by etanshaul** [comment]
weird - so that path in the failure log is actually correct? yet it still can't find it..

**Comment by joaoandremartins** [comment]
The path in the failure log is incorrect. It would be correct if `.jar` was appended to it.

**Comment by etanshaul** [comment]
ah I didn't notice that.

It should be getting the packaging type from https://github.com/GoogleCloudPlatform/google-cloud-intellij/blob/master/google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/appengine/cloud/MavenBuildDeploymentSource.java#L141

Hard to say whats happening without debugging more. Is this project on github by any chance so I can reproduce?

**Comment by joaoandremartins** [comment]
I'm using https://github.com/joaoandremartins/chatroom-springintegration

You might need to add an application.properties file to the resources folder and add in bits. Or else remove the spring dependencies and the code that depends on them...

**Comment by nkibler** [comment]
This was fixed by #1637.

**Comment by HunterAhlquist** [comment]
Hi, I believe this bug has resurfaced, I'm getting the exact error with my project when I try to deploy

**Comment by sripasg** [comment]
@HunterAhlquist  - Can you please help us with the following information ?

1. Which Jetbrains IDE do you see this issue in ? ( IDEA Community, IDEA Ultimate, PyCharm ... etc etc ??)
2. What is version of the IDE ?
3. What version of the cloud code plugin ? (Tools->CloudCode->Help/About->About Cloud Code?
