### ISSUE TITLE
Auto Rollback from 17.8.2 -> 16.11.6 in 2017.3 EAP

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/google-cloud-intellij#1631]
(Please ensure you are running the latest version of Cloud Tools for IntelliJ with _Help > Check for Updates_.)

- Cloud Tools for IntelliJ version:
- Google Cloud SDK version _(run `gcloud version` on the command line)_:
- OS:

**What did you do?**
Launched 2017.3 EAP

**What did you expect to see?**
Maybe a newer plugin.

**What did you see instead?**
Suggestion to roll back
![screen shot 2017-09-08 at 3 36 03 pm](https://user-images.githubusercontent.com/1136014/30233620-7c1810dc-94ab-11e7-9f52-49f65eb53412.png)

**Comment by patflynn** [comment]
@etanshaul @nkibler We need to update our EAP build to target 2017.3.

I remember discussing with etan whether we should remove the upper bound since we have very old plugin versions without one.
