### ISSUE TITLE
Cannot sign in Google account for authorization for app engine deployment

### ISSUE THREAD

**Issue by chriszohno** [GoogleCloudPlatform/google-cloud-intellij#1632]
(Please ensure you are running the latest version of Cloud Tools for IntelliJ with _Help > Check for Updates_.)

- Cloud Tools for IntelliJ version: **17.8.2**
- Google Cloud SDK version _(run `gcloud version` on the command line)_:
Google Cloud SDK 159.0.0
app-engine-java 1.9.53
app-engine-python 1.9.54
bq 2.0.24
core 2017.06.09
gcloud 
gsutil 4.26

- OS: Mac OS Sierra 10.12.5

**What did you do?**
Trying to deploy to app engine. Need to sign in to Google account to select a project.

**What did you expect to see?**
Successfully sign in and authorized.

**What did you see instead?**
I was prompted to authorize the tool to access Google resources. Then it tries to go a callback URL of something like:
http://localhost:49599/Callback?code=4/1nEfi7W2qqV3k4vpOowOmy-Ks5z5eUND6iqcrPvvg08#
But it does not work, getting this error:
This site can’t be reached

localhost refused to connect.
Search Google for localhost 49599 Callback
ERR_CONNECTION_REFUSED

(screenshots are helpful)

I have been using this tool for a long time. It has been working well, but now I cannot use it because it cannot communicate with Google resources. It seems the tool should run a local HTTP server to get oauth authorization.

_Feel free to deviate from this template as needed, especially if you are submitting a feature request._

**Comment by patflynn** [comment]
@chriszohno Thank you for your report! 

Is it possible your firewall settings have been changed recently?

**Comment by patflynn** [comment]
out of curiosity: Does` gcloud  auth login` work?

**Comment by chriszohno** [comment]
gcloud auth login does not work either. It has the same problem. It should not be a firewall issue because the issue is on my MacBook only, it works on my desktop Windows. Any idea why?

**Comment by chanseokoh** [comment]
Let's do some diagnosis.

Run `gcloud auth login`, but ignore the browser that pops up. (Don't proceed to log in. Leave the command running in a terminal). Then run `sudo lsof -i -n -P | grep TCP | grep python`. What's the output of `lsof`? It should show a server is listening on `127.0.0.1`.
```
python2   101715 chanseok    5u  IPv4 8419338      0t0  TCP 127.0.0.1:8085 (LISTEN)
```
If a server is listening, try `wget 127.0.0.1:<port>` in a terminal. It will download `index.html` if successful. If it works, repeat the process to try `wget localhost:<port>`. If it works, repeat the process to try hitting the local server in your browser.

You should be able to do a similar diagnosis with the IntelliJ plugin. (The IntelliJ plugin doesn't use a python server, so you will need to change the `lsof` command. Perhaps `| grep java` might do the trick.)

**Comment by chriszohno** [comment]
Thanks! That helped me fix my issue.  Oauth works now.

**Comment by chanseokoh** [comment]
Glad to hear. I'm curious. What was the cause?

**Comment by chriszohno** [comment]
Ended up I removed localhost from hosts file for a different project. I forgot to put it back.
