### ISSUE TITLE
How do we manage wiring up collaborators for our classes

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#165]
IntelliJ proviodes injection of registered services for application and project components, however we don't have a solution for DI for all other cases.  We need to specify how objects wire up their dependencies.

**Comment by elharo** [comment]
Does IntelliJ provide injection? How does one specify different instances for a particular class, e.g. for mocking in a test? IntelliJ's registry seems to create a lot of global state that can't be easily replaced on an instance-by-instance basis.

**Comment by etanshaul** [comment]
no longer relevant
