### ISSUE TITLE
text size is not consistent in the app engine application creation dialog

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#1664]
![screenshot from 2017-09-26 16 36 44](https://user-images.githubusercontent.com/7862557/30883029-ef0c7bb0-a2d8-11e7-89b5-79575a8e3234.png)

**Comment by patflynn** [comment]
I'm on 2017.1.5/linux.

Will test on mac in a bit.

**Comment by nbashirbello** [comment]
Error exists also on mac.

<img width="1070" alt="screen shot 2017-10-03 at 5 13 20 pm" src="https://user-images.githubusercontent.com/6805942/31150068-4ab6f44a-a860-11e7-9f43-303f2aebb148.png">

**Comment by patflynn** [comment]
You need a high-dpi screen probably to reproduce.
