### ISSUE TITLE
add 'app engine standard' framework support not available for spring-boot based java 8 project

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#1666]
I'm using the instructions here to convert a spring boot flex project to standard java 8:
https://github.com/GoogleCloudPlatform/getting-started-java/tree/master/appengine-standard-java8/springboot-appengine-standard

my project is here:
https://github.com/patflynn/spring-boot-with-cloud-libraries

When I try to add framework support: appengine-standard isn't listed.
![screenshot from 2017-09-26 17 02 07](https://user-images.githubusercontent.com/7862557/30884139-71d8a99e-a2dc-11e7-807d-eb04b655d93c.png)

**Comment by etanshaul** [comment]
dup of https://github.com/GoogleCloudPlatform/google-cloud-intellij/issues/1203 I believe. See the Jetbrains bug I filed in that issue.

**Comment by etanshaul** [comment]
https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000073610-Cannot-add-child-framework-support-when-parent-is-already-added
