### ISSUE TITLE
GCS info won't load

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#1673]
IJ: 2017.2 UE
OS X: 10.12.6
IJ: GCS Alpha release

Problem:
All the GCS releated actions seem to fail.  "Error loading buckets"

Step to reproduce:
really not sure.  I just came back to my laptop after the project had been open over the weekend and I couldn't use the GCS stuff anymore

<img width="1043" alt="screen shot 2017-10-02 at 2 40 04 pm" src="https://user-images.githubusercontent.com/7862557/31093460-ce6f7d84-a77f-11e7-8abd-79ef50ca761f.png">

**Comment by patflynn** [comment]
FYI logs appear empty so perhaps there's an opportunity to add some debug logging here.

**Comment by etanshaul** [comment]
I suspect your auth expired. I still need to make the auth management more robust

**Comment by etanshaul** [comment]
Could try re-authenticating and see if it fixes it? Just to help narrow it down.

**Comment by patflynn** [comment]
you mean logout and log back in?

**Comment by etanshaul** [comment]
yes

**Comment by patflynn** [comment]
an interesting addendum to this bug.

The project selector state does not match the login state.  If I logout the project selector still has the old accounts displayed.

**Comment by patflynn** [comment]
If I close and re-open the tab the state gets sycned.  Unfortunately the same errors are still happening.

**Comment by etanshaul** [comment]
just documenting that I'm unable to reproduce this on my laptop. I suspect it has something to do with the expiration on the credentials that are setup for GCS operations -> if you close the ide and reopen I suspect it will start working again. I'll look at it more closely

**Comment by etanshaul** [comment]
This is why this is happening:

- For GCS operations via the client library, I am creating a new credential object from the existing credentials (obtained from logging in at the plugin level)
- For these new credentials I am creating a new access token who's expiration matches the expiration of the plugin's credentials (which appears to be 1 hour)
- When the token expires, GCS operations stop working. Other plugin operations (like deploy) continue working - presumably because a new access token is automatically created
- DefaultGoogleApiClientFactory#getCloudStorageApiClient

**Comment by chanseokoh** [comment]
FYI.

> Other plugin operations (like deploy) continue working - presumably because a new access token is automatically created

FWIW, gcloud doesn't make use of an access token but cares only about a refresh token.

Refresh tokens may expire but they often don’t, or have very long expiration times relative to access tokens. Actually, accordingly to [this](https://stackoverflow.com/questions/8953983/do-google-refresh-tokens-expire), Google refresh tokens seem to never expire until owners explicitly revoke them.

In fact, CT4E completely ignores the access token field and writes only the refresh token for gcloud usage:
https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/v1.3.1C/plugins/com.google.cloud.tools.eclipse.login/src/com/google/cloud/tools/eclipse/login/CredentialHelper.java#L40

**Comment by etanshaul** [comment]
I just noticed that too for IntelliJ. Thanks for the details! Based on this, I think the solution will simply be to use the refresh token instead of the access token like I was doing.

**Comment by chanseokoh** [comment]
Hmm, something good to know about refresh tokens: https://stackoverflow.com/a/46186270/1701388
