### ISSUE TITLE
Provide a way to add appengine framework support outside of the 'add framework support' flow.

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#1685]
As a workaround to the bug mentioned in #1666, and to improve discoverability of app engine framework file generation, we should see how else we can help users convert their projects to app engine.  Either through a contextual action or something in the toolbar.

**Comment by etanshaul** [comment]
A toolbar action is not a bad idea. We could programmatically add the facet when clicked.

**Comment by etanshaul** [comment]
@nbashirbello this just came to me when looking at the update on the JetBrains bug:

If, with these new actions, we just add the facet then we may be missing out on all of the other things that go along with adding framework support: like automatically creating the appropriate run configs.

Could you possibly check if:
1) There is a way programmitically trigger the addition of framework support (e.g. Flexible support, and Standard support).
2) and if so, does this do all of the other things typically done when this support is added like auto-creating the run configs.

If possible, I think this is better than what we discussed about adding the facet directly. If its not possible, then adding the facet is ok. WDYT? Sorry for throwing this in after agreeing to a different approach.

**Comment by etanshaul** [comment]
Actually maybe I'm wrong here - like we discussed be there probably isn't a way to do this without a new UI since framework support is scoped to a specific module. If this is the case, then just adding the facet is probably better.

**Comment by etanshaul** [comment]
Posted this in the wrong place before..

But I was able to resuse internal classes to open up a module picker. Its worth seeing if we can use this to add framework support instead of adding the facet directly (ideally showing the framework support dialog so that the user can generate files etc.). This should then take care of adding the run configurations automatically.

![image](https://user-images.githubusercontent.com/1735744/31520304-6a1116b2-af73-11e7-877e-11dd18941421.png)

```
List<Module> modules = Lists.newArrayList(ModuleManager.getInstance(project).getModules());
 ChooseModulesDialog dialog = new ChooseModulesDialog(event.getProject(), modules, "blah", "blah");
 dialog.show();
```
