### ISSUE TITLE
Typing in project selector to open the tree view

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/google-cloud-intellij#1689]
@nkibler, now that we have substring matching do you think it would be useful to automatically open up the tree view when the user starts typing?

Now, if you place the cursor in the selector and start typing, the project tree will remain collapsed - but it would be great to be able to see the tree get filtered as you type/

**Comment by etanshaul** [comment]
on second look - the click even does open up the tree.

However you can still close it and continue typing. Perhaps we should bind on keypress instead of on click.

**Comment by nkibler** [comment]
Yeah I noticed that too, I can take care of that no problem.
