### ISSUE TITLE
spurious app engine flexible detections

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#1698]
Any project with an app.yml or app.yaml in the source will cause the user to get an 'App Engine Flexible detected' notification.

Unfortunately this is not an unusual filename for users of Docker swarm and/or jhipster who aren't using Flex at all.  Ideally we'd inspect the file contents to validate that it's a app engine config file.

**Comment by etanshaul** [comment]
just wondering if these the recommended names for these other frameworks? a quick google search for app.yaml / app.yml with docker swarm / jhipster doesn't result in anything relevant. Also searching for just app.yaml alone results in only GAE stuff.

**Comment by patflynn** [comment]
I don't think it's a recommended name, but it's a likely name.  For
instance jhipster generates a compose file named app.yml when you generate
a microservice based app.

Anybody using swarm, kubernetes, compose, or some paas that's yaml based
would hit this if they called the yml app.(yaml|yml)

**Comment by etanshaul** [comment]
We can do a simple check for the presence of `runtime: *` in the app.yaml since this line [is required](https://cloud.google.com/appengine/docs/flexible/nodejs/configuring-your-app-with-app-yaml#general).
