### ISSUE TITLE
Same Cloud Project displays multiple times in project selector

### ISSUE THREAD

**Issue by parkjam4** [GoogleCloudPlatform/google-cloud-intellij#1709]
(Please ensure you are running the latest version of Cloud Tools for IntelliJ with _Help > Check for Updates_.)

- Cloud Tools for IntelliJ version: 17.GCS-RC2
- Google Cloud SDK version _(run `gcloud version` on the command line)_: 176.0.0
- OS: Linux

**What did you do?**
I wanted to select a different GCS bucket for my app. When I clicked the drop-down menu, I saw the same project listed 3 times.

**What did you expect to see?**
I expected to see the project that I selected and then a list of the available GCP projects.
**What did you see instead?**

(screenshots are helpful)

(https://user-images.githubusercontent.com/11820506/31950228-26e829b8-b8a9-11e7-99d5-9ed18acd8686.png)

**Comment by etanshaul** [comment]
Since this appears to be an issue in the project selector, could you please check the state of the project selector from other views after you notice this issue again in GCS?

For example:
- Tools -> Google Cloud Tools -> Setup on Cloud Source Repositories
- The first field is a project selector. Is it also in an incorrect state here?

-

**Comment by parkjam4** [comment]
Yeah, I'm seeing the same thing in the CSR project selector: 
<img width="746" alt="cg3pl2n6y2d" src="https://user-images.githubusercontent.com/11820506/31952851-95374592-b8af-11e7-813f-ea621c782ca4.png">

**Comment by etanshaul** [comment]
Thanks for testing that out.

Are you only signed into one account? (click on the login widget on the top right of the IDE)

@nkibler do you think this could be a regression from the project selector work?

**Comment by parkjam4** [comment]
Yeah, only one account. I only have one account.

**Comment by nkibler** [comment]
Ah yeah, it's likely a regression; I can reproduce it too. Let me dig into this now to figure out what's going on, my gut reaction is that it's a simple thing that was only noticed because we're now retaining the panel.
