### ISSUE TITLE
Change Cloud Debugger to Stackdriver Debugger

### ISSUE THREAD

**Issue by parkjam4** [GoogleCloudPlatform/google-cloud-intellij#1710]
Using the latest version of IntelliJ and the plugin. I signed into my account and saw that we ask for permission to manager Cloud Debugger. Should we change that to Stackdriver Debugger?

https://screenshot.googleplex.com/0FkHgqo6O0x

**Comment by etanshaul** [comment]
Yes, but I think this need to be filed internally. Let me find the correct place.

**Comment by etanshaul** [comment]
filed issue internally. closing since it is not part of this plugin.
