### ISSUE TITLE
The Select An App Engine Region dialog reopens once closed

### ISSUE THREAD

**Issue by nbashirbello** [GoogleCloudPlatform/google-cloud-intellij#1714]
**What did you do?**
In the App Engine Run/Debug configuration wizard
1. select a GCP project that does not have an App Engine application
2. The Region field would show an error message with a link to a dialog to create an App Engine application
3. Select that link and the Select An App Engine Region dialog would open up
4. In the  Select An App Engine Region dialog, click the Cancel button

**What did you expect to see?**
The Select An App Engine Region dialog should close and the  Run/Debug configuration wizard should be in focus

**What did you see instead?**
The Select An App Engine Region dialog closes and opens again. If you click the "Cancel" button again, it closes and does not reopen

<img width="794" alt="screen shot 2017-10-26 at 11 26 52 am" src="https://user-images.githubusercontent.com/6805942/32061789-9ae3fdd6-ba40-11e7-8c3e-1732174ead83.png">

**Comment by nbashirbello** [comment]
This bugs seems to occur only the first time you open the Run/Debug configuration wizard in an IDE session

**Comment by etanshaul** [comment]
that makes it even stranger

**Comment by nkibler** [comment]
Fixed by #1718.
