### ISSUE TITLE
Could not find or load main class when debugging

### ISSUE THREAD

**Issue by Elrhino** [GoogleCloudPlatform/google-cloud-intellij#1716]
- Cloud Tools for IntelliJ version: 17.9.2
- Google Cloud SDK version: 170.0.1
- OS: MacOS Sierra 10.12.6

**What did you do?**

I tried to debug an AppEngine project but I get a `Could not find or load main class` error. When I start the project using the run configuration instead, everything works fine.

**What did you see instead?**

![screen shot 2017-10-27 at 10 02 53 am](https://user-images.githubusercontent.com/5719366/32107913-06802106-bafe-11e7-95c3-8fa9267ef327.png)

**Comment by patflynn** [comment]
@Elrhino how are you starting the debugger session?

**Comment by etanshaul** [comment]
also just to rule it out, could you update to the latest Cloud SDK by running:

`gcloud components update`

**Comment by Elrhino** [comment]
@etanshaul I updated to version 177.0.0, but I still have the same problem.
@patflynn I'm using the Intellij's debug button and this application server in my run configuration:
<img width="642" alt="screen shot 2017-10-30 at 8 14 42 pm" src="https://user-images.githubusercontent.com/5719366/32201759-180f355c-bdaf-11e7-8191-9a17ff10bf11.png">

**Comment by Elrhino** [comment]
@etanshaul I update to Google Cloud SDK 177.0.0. I'm still having the same issue.
@patflynn I use the Intellij's debug tool. I use AppEngine Dev 1.9.54 as my application server could this be it?

**Comment by patflynn** [comment]
@Elrhino 
Could you show me a screenshot of your local dev server run configuration?

**Comment by Elrhino** [comment]
@patflynn Here you go:

<img width="915" alt="screen shot 2017-10-30 at 8 09 22 pm" src="https://user-images.githubusercontent.com/5719366/32253634-5e6472ce-be72-11e7-878c-115db8d6e54d.png">

**Comment by etanshaul** [comment]
@Elrhino what version of Java (including minor version) is your project configured to? Project Structure -> Project Settings -> Project -> Project SDK

Also, if you happen to have a sample project that reproduces the issue somewhere that we could clone (like Github) or if its not to much work to make one, that would be helpful too.

**Comment by Elrhino** [comment]
@etanshaul I don't know how this happened, but the issue is fixed now. I reimported the project in IntelliJ, created the same run configuration and now the debugger works as expected. Maybe the problem was with IntelliJ itself? Thanks for the quick response though!
