### ISSUE TITLE
Dialog to add App Engine support to modules is misleading

### ISSUE THREAD

**Issue by nkibler** [GoogleCloudPlatform/google-cloud-intellij#1725]
The dialog to add App Engine support to modules looks like:

![screenshot from 2017-11-02 14 13 41](https://user-images.githubusercontent.com/14352762/32342858-1d8aa73e-bfd8-11e7-9e29-dd790ed716e4.png)

It's confusing to users because you can click "OK" even though no module is selected and nothing will happen. We should make it clear that the user must act here, like graying out the "OK" button until they select a module.

**Comment by etanshaul** [comment]
just noticed the missing word in the message too:

> Google App Engine standard framework support will be added to [the] selected module

I'll fix that here too
