### ISSUE TITLE
Out of memory error when typing and searching multiple projects in Project Selector

### ISSUE THREAD

**Issue by ivanporty** [GoogleCloudPlatform/google-cloud-intellij#1742]
Cloud Tools for IntelliJ version: 17.11.2-SNAPSHOT
Google Cloud SDK version: 179.0.0
OS: Linux 4.4.0-97-generic

**What did you do?**
Run -> Edit Configuration, open App Engine Flex deployment configuration (from gs-spring-boot sample code).
Edit project name - type something partial (not a complete project name).
Open project selector drop down to see the accounts/projects tree.
It helps if you have multiple accounts (2 in this scenario) and many available projects in selector tree.

Keep typing and deleting project name. It seems to happen faster if many project names matches the phrase (i.e. "test" in this scenario matched 10+ projects).

**What did you expect to see?**
Filtered list of matching projects.

**What did you see instead?**
Projects match the typed phrase, list expands and collapses as phrase changes for some time.
Then, UI freezes, keys are not accepted.

Memory exceptions are printed to console and continue to be printed when attempting to use the application.

Nov 14, 2017 1:38:51 PM sun.awt.X11.XToolkit processException
WARNING: Exception on Toolkit thread
java.lang.OutOfMemoryError: GC overhead limit exceeded

Exception in thread "JobScheduler FJ pool 8/12" Exception in thread "JobScheduler FJ pool 2/12" java.lang.OutOfMemoryError: Java heap space

**Comment by etanshaul** [comment]
@ivanporty do you mind looking into this to see if anything jumps out at you?

This is definitely something we need to fix for the next release (or perhaps for a patch release).
