### ISSUE TITLE
Extend App Engine deployment configuration

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/google-cloud-intellij#1743]
Certain flags, such as `enable_jar_classes` that are currently not exposed in the UI are potentially useful to users. See https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/1658

Need to investigate which flags to expose (do we expose them all? custom fields vs generic flag field?).

**Comment by etanshaul** [comment]
@ivanporty do you want to investigate adding these fields to our configuration?

**Comment by ivanporty** [comment]
@etanshaul sounds good, I'll design quick doc with suggestions on that.

**Comment by nbashirbello** [comment]
@ivanporty Are you working on this?

**Comment by ivanporty** [comment]
@nbashirbello Not yet, busy with Cloud SDK downloader.

**Comment by nbashirbello** [comment]
Looking into what jars to support, thinking we could start by support the flags the core plugin currently supports:

1. enable_quickstart
2. disable_update_check
3. enable_jar_splitting
4. jar_splitting_excludes
5. compile_encoding
6. delete_jsps
7. enable_jar_classes
8. disable_jar_jsps

(https://github.com/GoogleCloudPlatform/appengine-plugins-core/blob/v0.2.11/src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineStandardStaging.java#L63)

**Comment by nbashirbello** [comment]
Below are the proposed UI changes to add the flags to the App Engine deployment configuration. The main change is to add a tab to the center of the config. First tab would show the current properties and the second tab would show the new flags.

![gae_deployconfig_deploytab](https://user-images.githubusercontent.com/6805942/35246184-d1bb398a-ff93-11e7-9fd0-a821c80f0e10.png)

![gae_deployconfig_stagingflagstab](https://user-images.githubusercontent.com/6805942/35246186-d6947a16-ff93-11e7-9afe-c9ef281d73de.png)

**Comment by patflynn** [comment]
Seems odd to move away from checkboxes for the 'additional staging
params'.  Also I guess I would call them 'advanced' since 'additional' kind
of just begs the question why they're in a different tab.

**Comment by nbashirbello** [comment]
Not all the flags expect a boolean e.g. jar_splitting_excludes

**Comment by ivanporty** [comment]
Another option would be something familiar for IJ users - take a look at traditional application run configuration for example. It has standard control to add an arbitrary number of environment variables and it takes very little space:

<img width="730" alt="screen shot 2018-01-23 at 1 03 33 pm" src="https://user-images.githubusercontent.com/11686100/35292256-f39803f8-003d-11e8-9e5e-d3fa736e6903.png">

It opens into something like this:

<img width="588" alt="screen shot 2018-01-23 at 1 03 44 pm" src="https://user-images.githubusercontent.com/11686100/35292271-fb1581aa-003d-11e8-9ec6-2644acaa72ac.png">

It's not ideal but very familiar for IDEA users.

**Comment by nbashirbello** [comment]
@ivanporty That's a nice suggestion. The tabbed panels are also pretty common in IJ. Not sure which is better though cause I have seen both.

**Comment by etanshaul** [comment]
+1 on @ivanporty suggestion. I think it ultimately keeps the UI simpler and that control in the popup seems to fit what we need well.

**Comment by nbashirbello** [comment]
Cool, will implement the pop-up version.

**Comment by nbashirbello** [comment]
Should the table be preconfigured with the flags we support (as in the mocks) so that
- users would know the options available to them
- we don't have to worry about the user inputting invalid flags
Fyi 
- the staging process utilizes the default values if the flags are not set
- the table can be sorted to make it easy to find flags

**Comment by ivanporty** [comment]
Great suggestions from @etanshaul, we should definitely pre-populate the flags with available options, possibly leaving them with empty values initially.

**Comment by nbashirbello** [comment]
I think prepopulating with the default values will probably be helpful since they are used if nothing is changed.

**Comment by nbashirbello** [comment]
Updated mocks -> added the Staging Properties field in the Deployment Parameters group box that pop-ups a dialog with a table:

![gae_deploy_config_stagingpropertiespopout bmpr](https://user-images.githubusercontent.com/6805942/35399911-6f5749fa-01c3-11e8-997e-2a3b2d67210a.png)

![stagingflagspopup](https://user-images.githubusercontent.com/6805942/35399922-7798a1e0-01c3-11e8-820a-973563019fa9.png)

**Comment by patflynn** [comment]
couldn't you mix input widget types so that you can still use checkboxes
for boolean and input appropriate widgets for other flag types?

**Comment by nbashirbello** [comment]
The rows for the boolean flags will show a dropdown (showing true and false) in the value column. I didn't know how to show that in the mock.

The image below (the Horizontal Align field) shows a dropdown in a row. I will implement this for the boolean flags.

<img width="640" alt="screen shot 2018-01-26 at 2 53 53 pm" src="https://user-images.githubusercontent.com/6805942/35458044-dccc4892-02a8-11e8-9213-89118981ab4a.png">

**Comment by nbashirbello** [comment]
I could do it the other way and mix checkboxes and fields too. It would look very similar to the Deployment Parameters groupbox which is a good thing. Which do you prefer?

**Comment by elharo** [comment]
Nit: "Stop Previous version" should probably be below "Promote deployed version" rather than to its right.
