### ISSUE TITLE
Unable to create App Engine Standard project in Intellij Idea.

### ISSUE THREAD

**Issue by AxeemHaider** [GoogleCloudPlatform/google-cloud-intellij#1749]
I'm working on App Engine Standard and I install Intellij Idea unlimited edition. And install new Google Cloud Tool Plugin but whenever I create new project the src folder is always empty and there is no pom.xml file also.

![](https://lh3.googleusercontent.com/-cn95VDVIMYs/Wg2p-MPu-1I/AAAAAAAABC8/PTPfQWpkVQ0s1uYq3UWDU42YpaA6Y1V3QCLcBGAs/s1600/Capture.PNG)

**Comment by patflynn** [comment]
@AxeemHaider this is actually working as intended.  This project template was just ported over from the jetbrains App Engine plugin and does not include a Maven pom and just serves a single JSP.

For a maven based template checkout the instructions on our `https://cloud.google.com/appengine/docs/standard/java/quickstart-java8`.  

You can also use our [Maven archetypes](https://cloud.google.com/appengine/docs/standard/java/tools/using-maven).

**Comment by AxeemHaider** [comment]
I know how to create project using Maven manually. But then what's the benefit of Google Cloud Tool Plugin in IJ ? Previously I'm working in Eclipse there you can easily create project just by clicking on new project using Google Cloud Tool Plugin. But I don't like eclipse editor.  Can I do same thing in IJ

**Comment by patflynn** [comment]
We may eventually have new module wizards in Cloud Tools, in the mean time if  you'd like to generate the project from witthin the IDE you can generate a maven archetype based project  rom the Maven section of the new project wizard.

The benefit of the plugin at the moment are the local run and debug and deploy actions for App Engine, as well as the source repo, stackdriver debugger, and GCS integration.

**Comment by AxeemHaider** [comment]
You are telling me Google Documentation is wrong [Here](https://cloud.google.com/tools/intellij/docs/deploy-std) 
Ok, Anyway I download app engine sample codes from gitHub and make a little bit changes to test it and run maven commands 
`mvn clean package`
`mvn appengine:run` it successfully run

Then I open IJ and import project as Maven it successfully import But there is no configuration to run this project I created the new one But it always said **artifact isn't specified**
![capture2](https://user-images.githubusercontent.com/27768863/32956010-6f8f78bc-cb6c-11e7-8faf-301778510157.PNG)

I searched about this and I found there is artifacts for my project see image
![capture3](https://user-images.githubusercontent.com/27768863/32956071-a55338a8-cb6c-11e7-8cc9-24e7a3669353.PNG)

What I'm missing can you please let me know. Same thing happen when I create App Engine project using maven archetype in IJ Idea.

**Comment by AxeemHaider** [comment]
In first picture there is nothing in Artifact deploy options 
![capture4](https://user-images.githubusercontent.com/27768863/32956307-4534817e-cb6d-11e7-8a68-53ccbe6c9c74.PNG)

**Comment by patflynn** [comment]
@etanshaul perhaps related to #1625

**Comment by AxeemHaider** [comment]
Yes, I already read this one But how I can select Artifact if nothing is shown in selection option. 
I didn't understand anything.

**Comment by etanshaul** [comment]
@AxeemHaider did you clone this project: https://cloud.google.com/appengine/docs/standard/java/quickstart-java8 ?

I just tried it here:

1. git clone https://cloud.google.com/appengine/docs/standard/java/quickstart-java8
2. in intellij open the project folder under: `getting-started-java/appengine-standard-java8/helloworld`
3. IntelliJ detects that its a maven / gradle project (I sync with maven)
4. IntelliJ detects that its an App Engine standard project: I accept the dialog and click to add App Engine framework support:
<img width="715" alt="screen shot 2017-11-17 at 11 07 42 am" src="https://user-images.githubusercontent.com/1735744/32956719-8e686440-cb87-11e7-8052-43c02e591884.png">
5. After opening up the automatically created local dev server run config, I see this:
<img width="717" alt="screen shot 2017-11-17 at 11 08 26 am" src="https://user-images.githubusercontent.com/1735744/32956744-a7882a78-cb87-11e7-8e72-7b04aa478b77.png">

Do you mind checking to see if/how you deviated from this so we can help debug the issue?

**Comment by AxeemHaider** [comment]
Same issue..

I get clone and open project in intelliJ Idea 
![capture5](https://user-images.githubusercontent.com/27768863/32957428-83b67f30-cb70-11e7-83ad-e7f8f56eb789.PNG)

after that I open edit configuration Here is under default one

![capture6](https://user-images.githubusercontent.com/27768863/32957444-901b292e-cb70-11e7-9d8e-9cf3fe17da62.PNG)

If I created new config then it say artifact isn't specified
![capture7](https://user-images.githubusercontent.com/27768863/32957506-b531effe-cb70-11e7-91ab-af2281822fc6.PNG)

Now what I do ???

**Comment by AxeemHaider** [comment]
It only work if I create App Engine project using GCP Tool plugin 
see below images but here problem is that src folder is always empty and there is no pom.xml file as described [Here](https://cloud.google.com/tools/intellij/docs/deploy-std)

![capture8](https://user-images.githubusercontent.com/27768863/32957765-7eeab844-cb71-11e7-91ec-f988dd20f9ab.PNG)

![capture9](https://user-images.githubusercontent.com/27768863/32957777-8294d222-cb71-11e7-81c9-04fdd09cf711.PNG)

Can you please check through TeamViewer Please ?

**Comment by etanshaul** [comment]
@AxeemHaider just to make sure were not missing it, did you perform step #4 from my previous post?

Specifically, you need to make sure you have App Engine framework support enabled on your project.

One way to verify is to go to 'Project Settings` again and look at your facets tab: Do you see the 'Google App Engine standard' facet on the `helloworld` module?

If not, you can still add it:
`Tools -> Google Cloud Tools -> Add App Engine Support -> Google App Engine Standard`

**Comment by AxeemHaider** [comment]
Thanks @etanshaul Now it's working. I missed the step #4 I show the dialog and I think it's automatically configured because it's not showing as dialog instead of this showing like popup message :P

**Comment by etanshaul** [comment]
@AxeemHaider thats great. If you run into anything else don't hesitate to re-open or file new issues.

**Comment by AxeemHaider** [comment]
@etanshaul I only recommend that GCP Team to update GCT Plugin to add functionality as they described in [Documentation](https://cloud.google.com/tools/intellij/docs/deploy-std) To avoid user to confuse.  
 GCT Plugin not work same as describe there I think this can lead to confusion

**Comment by etanshaul** [comment]
@AxeemHaider fair point - we can probably do a better job outlining the current limitations of the AE standard project wizard. Thanks for the feedback.
