### ISSUE TITLE
Changes not apply until restart server App Engine Standard 

### ISSUE THREAD

**Issue by AxeemHaider** [GoogleCloudPlatform/google-cloud-intellij#1754]
I'm using intellij Idea for App Engine Standard.  
I create a project using maven archetype and then open it in IJ Idea. It automatically check project and configure as App Engine standard environment . It's work fine But there is one problem if I make any changes in files this will not appear until I restart my server

![capture](https://user-images.githubusercontent.com/27768863/33086335-17fe7426-ce9c-11e7-8cbb-1bb667a8ea1f.PNG)

I tried first two options but not work only third option work Restart server again. 

I used eclipse before this change apply automatically there. Is it not possible in intelliJ Idea. If Yes How can I configure.
Thanks.

**Comment by patflynn** [comment]
@AxeemHaider have you tried in debug mode?  Run mode does not support hotswap as far as I know.  

A way to optimize the workflow is to configure the run config to update classses and resources on frame deactivation.

**Comment by AxeemHaider** [comment]
Yes it work in debug mode But why it's not work in Run mode

**Comment by etanshaul** [comment]
@AxeemHaider I wish I could help more but it is simply because hotswap is built into the debugger.

**Comment by etanshaul** [comment]
I'll close for now since its working as intended, but feel free to reopen if you run into any issues.

**Comment by AxeemHaider** [comment]
@etanshaul After spending sometime on it I discovered that it's also not working very good in debug mode.  Sometime it work and sometime not. 
But If you create new file it never identify until you restart service. 
It only good when you make little bit changes in single file. If you make changes in multiple files most it ignore. 
This behavior is frustrating me.

**Comment by etanshaul** [comment]
@AxeemHaider, what you are running into are the limitations of HotSwap class reloading that is built into the JVM. This hot swapping is limited to modifying method bodies. So adding new methods (including new classes like you were trying), signature changes, etc. won’t work unfortunately. There are more sophisticated tools out there, like JRebel, which try and address this problem.
