### ISSUE TITLE
Not all configured artifacts are available for deployment

### ISSUE THREAD

**Issue by sgolubov** [GoogleCloudPlatform/google-cloud-intellij#1758]
(Please ensure you are running the latest version of Cloud Tools for IntelliJ with _Help > Check for Updates_)
- Cloud Tools for IntelliJ version: 17.11.1
- Google Cloud SDK version: 177.0.0
- OS: Windows 10 10.0

**What did you do?**
I'm running Google Appengine Standard Local Server configuration. I have in my project more than 8 artifacts.

**What did you expect to see?**
I want to have whole list of artifacts configured in my project in "Artifact to deploy:" dropdown.

**What did you see instead?**
Unpredictable behavior. Sometimes there is only one artifact to choose. Sometimes there is no artifacts at all. As a result I'm not able to deploy local server with desired artifact.

(screenshots are helpful)
![1](https://user-images.githubusercontent.com/11709689/33184716-46bda352-d07e-11e7-872f-fec57da5a487.png)
![2](https://user-images.githubusercontent.com/11709689/33184749-87c25460-d07e-11e7-9adb-a7758f7ae2f3.png)

_Feel free to deviate from this template as needed, especially if you are submitting a feature request._

**Comment by etanshaul** [comment]
thanks for the report @sgolubov 

This may be a dup of https://github.com/GoogleCloudPlatform/google-cloud-intellij/issues/1625

We are looking into this issue and will report back as soon as we have a resolution. I apologize in advance for any delays due to the holiday.

**Comment by etanshaul** [comment]
In the meantime, to unblock you if you cannot get the artifacts to appear using the plugin, you can try configuring the [maven plugin](https://github.com/GoogleCloudPlatform/app-maven-plugin) (or the [gradle plugin](https://github.com/GoogleCloudPlatform/app-gradle-plugin), if your project uses that). These build plugins contains goals to run the the local dev server.

**Comment by sgolubov** [comment]
Thanks @etanshaul!

**Comment by etanshaul** [comment]
@sgolubov, to assist with getting to the bottom of this, could you please confirm if your project was using Gradle or Maven (or neither)?

**Comment by etanshaul** [comment]
@sgolubov please see my comment on this thread: https://github.com/GoogleCloudPlatform/google-cloud-intellij/issues/1625#issuecomment-346840314 to see if it helps. Thanks.

**Comment by sgolubov** [comment]
@etanshaul, I'm using Maven in my project.
