### ISSUE TITLE
Clean up gradle warnings

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/google-cloud-intellij#1778]
![image](https://user-images.githubusercontent.com/1735744/33909866-f943cf16-df5a-11e7-906a-3af8f79915cc.png)

**Comment by patflynn** [comment]
I would avoid tackling this until we've finished modularization and upgraded to the latest intellij-gradle-plugin... maybe.

ATM we depend on applying the plugin to add the idea sdk to the classpath of the modules even though they don't have plugin.xmls.  Although I seem to recall that some of the sdk is deployed to maven central now so it may be possible to resolve those dependencies through normal mechanisms.

**Comment by etanshaul** [comment]
yeah. I just came to a similar conclusion. At first I thought this may be related to https://github.com/GoogleCloudPlatform/google-cloud-intellij/pull/1772 but I don't think it is.

**Comment by etanshaul** [comment]
fixed via #1779
