### ISSUE TITLE
From SO: Idea doesn't upgrade sources while in local debug for appEngine app

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/google-cloud-intellij#1785]
https://stackoverflow.com/questions/47788738/idea-doesnt-upgrade-sources-while-in-local-debug-for-appengine-app

**Comment by Deathangel908** [comment]
I just installed IntelJIi Idea on windows, and added google cloud tools, by default 'Before launch` only has  [Build](https://static.pychat.org/photo/s1jLYR4H_.png) but it should be `build exposed app` as I noted in the  stackoverflow response

**Comment by etanshaul** [comment]
hi @Deathangel908.  Im having a hard time reproducing this as every app engine standard project that I test has its local server run configuration already populated as follows:
<img width="484" alt="screen shot 2017-12-14 at 4 16 36 pm" src="https://user-images.githubusercontent.com/1735744/34014709-2f2c6db4-e0ea-11e7-88c4-faf5c9c0b495.png">

If the artifact is not yet selected, then indeed, the build task for the exploded war artifact is missing:
<img width="446" alt="screen shot 2017-12-14 at 4 21 48 pm" src="https://user-images.githubusercontent.com/1735744/34014944-ea6b1ea4-e0ea-11e7-87c6-024593464f2e.png">

But, as soon as I select my target artifact, IntelliJ automatically adds the appropriate build task to the 'before launch tasks':
<img width="452" alt="screen shot 2017-12-14 at 4 17 55 pm" src="https://user-images.githubusercontent.com/1735744/34014770-5c0cbe2e-e0ea-11e7-8e5b-31e7bd8c1e6a.png">

Perhaps you could provide some more information so I can reproduce this:
- Are you importing an existing project? Maven project?
- Did IntelliJ automatically detect that it is an App Engine standard project and create the `Google App Engine Standard Local Server` run configuration, or did you create the run configuration yourself (it shouldn't affect this, but I'm curious)?
- Could you try creating a new local server run configuration, select your artifact, and report back if the exploded war build task is automatically added:
<img width="371" alt="screen shot 2017-12-14 at 4 20 45 pm" src="https://user-images.githubusercontent.com/1735744/34014899-c443bc7c-e0ea-11e7-8fad-3115c6638c3e.png">

Sorry for the trouble

**Comment by etanshaul** [comment]
closing for now as not reproducible
