### ISSUE TITLE
adding App Engine support wipes out existing appengine-web.xml

### ISSUE THREAD

**Issue by eschultink** [GoogleCloudPlatform/google-cloud-intellij#1788]
(Please ensure you are running the latest version of Cloud Tools for IntelliJ with _Help > Check for Updates_.)

- Cloud Tools for IntelliJ version: 17.12.2 
- Google Cloud SDK version _(run `gcloud version` on the command line)_:
Google Cloud SDK 182.0.0
app-engine-java 1.9.59
app-engine-python 1.9.63
bq 2.0.27
core 2017.12.01
gcloud 
gsutil 4.28
- OS: OSX 10.13.1

**What did you do?**

1. **Tools** --> **Google Cloud Tools** --> **Add App Engine Support** --> **Google App Engine Standard**
2. select Maven module I wish to add GAE support to
3. Maven module already had src/main/webapp/appengine-web.xml

**What did you expect to see?**
Some sort of warning at least of any destructive changes it would make. 

**What did you see instead?**
Maven module already had `src/main/webapp/WEB-INF/appengine-web.xml`, local db, etc. Without any feedback, it removed / overwrote `appengine-web.xml` and the local db (`appengine-generated/` files I think). It did not overwrite other GAE config files: `cron.xml`, `datastore-indexes.xml`, `dispatch.xml`, `queue.xml`, etc.

`appengine-web.xml` was replaced with: 
```xml
<?xml version="1.0" encoding="utf-8"?>
<appengine-web-app xmlns="http://appengine.google.com/ns/1.0">
  <threadsafe>true</threadsafe>
  <runtime>java8</runtime>
</appengine-web-app>
```

I understand logic in doing that if no `appengine-web.xml` exists, but not overwriting an existing one; it should either warn or leave it. In my case, my `appengine-web.xml` already had both those params, so it was effectively just removing the rest of the configuration.

This is most problematic due to #1625 and the repeated need to add/remove GAE support, and re-import the project, to try to keep the GAE Run Configuration working. It adds recovering the old `appengine-web.xml` as an extra step to do whenever you re-import.

**Comment by nbashirbello** [comment]
@eschultink

Hey, can you verify that the plugin did not create another appengine-web.xml in proj/web/WEB-INF/appengine-web.xml as opposed to overwriting the one in proj/src/main/webapp/WEB-INF/appengine-web.xml

**Comment by nbashirbello** [comment]
@etanshaul Did we ever discuss having a property that holds the location of the appengine-web.xml  that gcloud will utilize so that if a project have more than one appengine-web.xml, the user and the plugin will know which to use for gcloud actions?

**Comment by patflynn** [comment]
I think appengine-web.xml has to be in the WEB-INF directory, so I don't
think that use-case could be supported without extra staging on our side
(which we probably don't want to do).

**Comment by nbashirbello** [comment]
When I duplicated the scenario above, there were 2 WEB-INF folders
- proj/src/main/webapp/WEB-INF/appengine-web.xml (the original one)
- proj/web/WEB-INF/appengine-web.xml (the one created during the conversion step)

**Comment by patflynn** [comment]
@nbashirbello then I guess it's another bug?  We should find the web framework facet for the module (location of webapp directory) and make sure that's where we're inserting the WEB-INF/appengine-web.xml.  If it already exists we should probably prompt whether the user wants to overwrite.

I think @etanshaul has looked at this as well way back.

**Comment by etanshaul** [comment]
@nbashirbello is there anything to do here based on your findings?

**Comment by eschultink** [comment]
this is what happens - starting from a clean import of the project, when I use Tools --> Google Cloud --> Add App Engine Support:
![module-ingest -bash 2018-01-25 16-41-48](https://user-images.githubusercontent.com/102831/35419766-b5e9595a-01ee-11e8-8d1f-c1402a3a9ffd.png)

@nbashirbello - as you can see, there is no `web/` directory in our project layout.  just `src/main/webapp`

**Comment by nbashirbello** [comment]
I am guessing your web module descriptor was proj/src/main/webapp/WEB-INF/web.xml. Will add a fix to prevent overwriting of the appengine-web.xml

**Comment by eschultink** [comment]
yes, exactly
