### ISSUE TITLE
Project selector should select account after sign in

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/google-cloud-intellij#1791]
1) start logged out of all google accounts
2) load up the new project selector and click to open a dialog
3) sign into your account

-> I would have expected the account I just signed into to be selected now. Instead, no account is selected  (it _is_ in the dropdown, I just need to manually choose it):

![image](https://user-images.githubusercontent.com/1735744/34128367-6eef16fa-e40e-11e7-86fa-2dd936251925.png)

![image](https://user-images.githubusercontent.com/1735744/34128390-854a932a-e40e-11e7-9926-49c6bbafd4f4.png)

**Comment by patflynn** [comment]
+1
