### ISSUE TITLE
Old loading icon in project selector needs to be removed

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/google-cloud-intellij#1792]
I can't catch the screenshot fast enough (without modifying the code), but there are now 2 loader icons. The new big one in the center, and the old small one in the top right corner (I think you just forgot to remove it). Or was it intentional?

**Comment by ivanporty** [comment]
It's kind of a 'free' perk since it's built-in into IDEA table, but it's really not necessary as we have large one showing. I'll take it out.

**Comment by etanshaul** [comment]
ah. I didn't realize it was automatically added.

**Comment by ivanporty** [comment]
Fixed.
