### ISSUE TITLE
Sign in with Google account ends up at localhost with 403 result

### ISSUE THREAD

**Issue by rcgroot** [GoogleCloudPlatform/google-cloud-intellij#1803]
(Please ensure you are running the latest version of Cloud Tools for IntelliJ with _Help > Check for Updates_.)

- Cloud Tools for IntelliJ version: 17.12.2
- Google Cloud SDK version _(run `gcloud version` on the command line)_: 183.0.0
- OS: Linux - Fedora 27  

**What did you do?**
Install Cloud Tools, restart IntelliJ and click "Sign in with Google account". Gave permission on the resulting website.

**What did you expect to see?**
See the granted permission be picked up by IntelliJ. 

**What did you see instead?**
http://localhost:40085/Callback?code=XXXXXXX# with HTTP ERROR 413 and idle progress bar in IntelliJ 

I've tried the same with a Google Core plugin in Android Studio 3.0.1 and the localhost URL also does not reach the IDE.

**Comment by etanshaul** [comment]
hi @rcgroot. do you mind trying again? It seems to be working now, so I just want to check to see if it was some intermittent failure you ran into. Thanks.

**Comment by rcgroot** [comment]
Hi @etanshaul still happening

**Comment by rcgroot** [comment]
Workaround: copy/paste the url and from commandline 
`# curl <url>`
and it connects my account

**Comment by etanshaul** [comment]
hi @rcgroot. sorry for the delay in following up. I'll close this for now since it doesn't seem to be an issue directly with the plugin, but feel free to reopen if you run into any other problems.

**Comment by patflynn** [comment]
@rcgroot are you on a corp machine?  I think we've seen errors like this before due to proxy configurations or security restrictions.

**Comment by rcgroot** [comment]
No proxy, direct ethernet to the ISP router/modem.
