### ISSUE TITLE
Add every possible setting to generated app.yaml

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/google-cloud-intellij#1805]
The generated app.yaml contains very little.

```
runtime: custom
env: flex
```

We should probably add [every possible setting](https://cloud.google.com/appengine/docs/flexible/java/configuring-your-app-with-app-yaml) to the file, commented out, to make lives easier for users.

**Comment by patflynn** [comment]
It's unlikely we'd choose to maintain such a file from the IJ plugin.  Feel free to open this with @lesv against an archetype project.
