### ISSUE TITLE
Keep the last selected project for project selector

### ISSUE THREAD

**Issue by ivanporty** [GoogleCloudPlatform/google-cloud-intellij#1812]
Current project selector is stateless and does not keep the last selected project.
Most of the activities in the GCP plugin require project and might use the same active project user selected last.
Some of them keep the state (deployment, run configuration), however many do not (GCS browser, source control support, API selection etc.)

Let's persist the last selected project in project selector and pre-populate it whenever it's used in UI.

**Comment by patflynn** [comment]
+1.  Caveat being that once a project has been selected in a specific part of the UI, it should remain selected even when it gets changed in the project selector somewhere else.

**Comment by etanshaul** [comment]
good point - we should already get that in some cases, like the deployment config, where the state is saved to the form-specific persistence. For other cases, we should ensure that we are doing that.

**Comment by patflynn** [comment]
another consideration is the scope of the state.  Is it at the IDE application level so that different open projects share the default?

**Comment by ivanporty** [comment]
Good question. Probably this should be project level default. New project will have none initially and then save first choice for later use.

**Comment by patflynn** [comment]
+1
