### ISSUE TITLE
Add application/version in appengine-web.xml support

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/google-cloud-intellij#1814]
The values in the deployment config will take precedence, but we should support users that choose to configure their application by including these values in appengine-web.xml

**Comment by patflynn** [comment]
So I'm not sure that there's anything for us to do here.  We don't want people to be putting their config in the appengine-web.xml, but we don't want to break them either.  As it is I think the change should hopefully be confined to the core staging logic and not have an impact on our plugin

**Comment by etanshaul** [comment]
Oh ok. I misunderstood. I thought the idea was to essentially bootstrap our deployment config from the values in appengine-web.xml (if set). That way, our plugin can help make it clear which values are actually being used.

**Comment by patflynn** [comment]
hmm. I see setting the defaults from the appengine-web.xml if there are
values there doesn't sound crazy.

**Comment by etanshaul** [comment]
[go/add-appenginewebxml-config](go/add-appenginewebxml-config)

**Comment by etanshaul** [comment]
as @patflynn said, nothing to do here
