### ISSUE TITLE
Make it possible to opt project out from adding GAE support

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/google-cloud-intellij#1815]
Every time I check out a project that has a sample GAE app, I'm always prompted if I want to add GAE support to the project.

Since the project isn't a GAE project, I'd like to disable the prompt forever.

**Comment by etanshaul** [comment]
Sure, but you said that you opened a sample GAE app and then later that it isn't a GAE project so I'm a little confused. Is it GAE? If so, for now, you could just accept the prompt with no harm. In terms of permanently dismissing the prompt, I can see if this is something that is possible with other framework support prompts.

**Comment by joaoandremartins** [comment]
The example is the [spring-cloud-gcp](https://github.com/spring-cloud/spring-cloud-gcp) project. There's a ton of code and then the code samples module, which contains a GAE app sample.

The project itself isn't a GAE app, it just contains a sample one. I don't want to add GAE support to it because that will alter the state of the project, e.g., add run configurations.
The same issue will happen for projects like [java-docs-samples](https://github.com/GoogleCloudPlatform/java-docs-samples/). It contains many GAE apps and I don't know how google-cloud-intellij handles it. But the 1 project-1 GAE app mapping is broken for similar projects, and I think muting the notification would make sense there.

There could be a boolean in the GAE Standard/Flex facet that determines if the notification is muted. If a user changes their mind, they could revert the setting in the project's GAE facet.

**Comment by etanshaul** [comment]
Have you seen this:

<img width="713" alt="screen shot 2018-01-09 at 11 31 09 am" src="https://user-images.githubusercontent.com/1735744/34731551-a0dd241c-f530-11e7-9c01-b3a0f75a7212.png">

If you click on the little settings icon on the notification bubble, it looks like you can control the notification. I'm not sure if it is exactly what you want, but its worth a shot.

**Comment by joaoandremartins** [comment]
Yes, I'm aware of the IJ notifications system. That would disable google-cloud-intellij notifications across the board, which would not be OK in case of a legit GAE app project.
The feature I'm advocating for is to disable the notifications on a per-project basis, if that's feasible.

**Comment by etanshaul** [comment]
If this is something that is controllable it would have to be through something like that above to fit in with the way the platform behaves.

I wouldn't want to bake in a 1-off like you suggested. Besides being a 1-off, this could lead to other problems (like having to ensure that there is a good way to re-enable it later etc.).

**Comment by etanshaul** [comment]
ok. I'll check if theres an alternative here.

**Comment by etanshaul** [comment]
you may have noticed this one too, but if you click on the framework support and get this:

<img width="559" alt="screen shot 2018-01-09 at 11 37 33 am" src="https://user-images.githubusercontent.com/1735744/34731853-8d3c22b8-f531-11e7-9486-9af2657ac076.png">

If you uncheck the framework support checkbox, it looks like it will permanently disable the detection (at the project level, I believe).

**Comment by joaoandremartins** [comment]
That's a good workaround. It solves my issue, but has a few issues.
- If I don't want to add support, I'll probably never click on the "Configure" button. A "Disable notification for this project" button would be the correct solution.
- I don't know how to re-enable notifications for a project, if I disabled them by accident.
- Not documented anywhere, but on this issue.

In any case, this solves my issue so feel free to use your best judgement on this issue going forward. Thanks!

**Comment by etanshaul** [comment]
Glad it worked. Agree with those issues too, but I don't think there is anything further to do here (aside from perhaps filing an issue with JB for improved docs / discoverability). Closing. Thanks.
