### ISSUE TITLE
Add Cloud Libraries: secondary dialog windows hide in background on Mac

### ISSUE THREAD

**Issue by ivanporty** [GoogleCloudPlatform/google-cloud-intellij#1832]
On Mac, open 'Add Libraries' from the GCP window, select some libraries, click 'Add...'.
Result: Dialog window blinks (becomes inactive), but nothing else can be seen.
Expected: See confirmation dialog with APIs to be added and enabled.

<img width="988" alt="screen shot 2018-01-16 at 3 16 11 pm" src="https://user-images.githubusercontent.com/11686100/35010265-58b21c10-fad0-11e7-8315-02405d974931.png">

This screenshot is taken *after*  "Add Client Library" button. Notice inactive window border.
Workaround: can open list of windows for IDEA and find confirmation dialog or click around on 'Add Libraries' dialog and eventually confirmation dialog shows up. 
Note: same happens with project selection dialog if called from this window.

<img width="1618" alt="screen shot 2018-01-16 at 3 17 09 pm" src="https://user-images.githubusercontent.com/11686100/35010582-56e4d930-fad1-11e7-9f30-29db20e316db.png">

This doesn't reproduce on Ubuntu.

**Comment by etanshaul** [comment]
thanks. will look into it.

**Comment by etanshaul** [comment]
@ivanporty i'm not able to reproduce this on my mac. When I click the "add" button, the confirmation dialog immediately pops up on top and in focus. Is this consistent for you?

**Comment by ivanporty** [comment]
Looks consistent for me.
I have MacOs Sierra 10.12.6, IDEA 2017.2. What are your system versions, maybe I need to upgrade?

**Comment by etanshaul** [comment]
I'm on 10.13.2. same version of intellij

**Comment by ivanporty** [comment]
Updated to 10.13.2, IntelliJ 2017.3.1, JDK 1.8.0_151, still see the same issue. What is your JDK version, maybe that's the difference?

**Comment by etanshaul** [comment]
1.8.0_101. I can try a newer version and see.

**Comment by etanshaul** [comment]
actually, how are you running this? you are building the plugin from sources and running the IDE using the gradle-intellij-plugin (the normal way we run things during dev)?

In that case, our numbers should be identical (pulled from gradle.properties: 2017.2 with whatever bundled JRE it uses).

**Comment by ivanporty** [comment]
Right, should be the same then. Yes, I run it the usual way: `gradlew runIde`

**Comment by etanshaul** [comment]
yeah so i was confused when you said you upgraded the IDE version and JDK since this shouldn't make a difference right (based on the way we are running it)?

In any case, since I can't reproduce, I'll table this until we can check yours out in person.

**Comment by etanshaul** [comment]
I was just able to reproduce this on OSX. Also the progress dialog wasn't shown for some reason.

Added to the next milestone

**Comment by etanshaul** [comment]
On second look, the progress dialog _is_ shown..its just also hidden behind the main client library panel
