### ISSUE TITLE
Project selector display wrapping issue

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/google-cloud-intellij#1838]
Noticed this in the CSR clone dialog in its initial state:
<img width="430" alt="screen shot 2018-01-21 at 4 39 50 pm" src="https://user-images.githubusercontent.com/1735744/35199257-ce809316-fec9-11e7-9401-8cb5cb73d77a.png">

making the window wider then fixes the problem

**Comment by ivanporty** [comment]
Did it happen in master or, if in a branch, did it include the latest fix for #1833?

**Comment by etanshaul** [comment]
I'm pretty sure I tested it on the nightly build. So it should have included that fix. Are you seeing otherwise?

**Comment by ivanporty** [comment]
Got it, I tested and I think I see it when it's small enough initially, then it could happen with longer name (vs. opening with already pre-populated project.) I'll take a look, seems my last fix not always applies.

**Comment by etanshaul** [comment]
@ivanporty have you started on this? if not I can take a look so we can try and knock it off for the release

**Comment by ivanporty** [comment]
I already tried a few different ways of doing this, should finish today

**Comment by etanshaul** [comment]
great! thanks
