### ISSUE TITLE
Sending the wrong credentials to the Console

### ISSUE THREAD

**Issue by parkjam4** [GoogleCloudPlatform/google-cloud-intellij#1877]
NOTE: This is an extreme edge case, so it may not be worth pursuing, but I thought I should file the issue anyway.
I wanted to import from source control.  In the Set up on Google Cloud Source Repositories dialog, I changed accounts to one that did not have a Cloud repo. When I click Create a new cloud repo button, I get to the Console and see an error: "You do not have sufficient permissions to view this page." In the top right corner, I see the incorrect account displayed. The first account I signed into IntelliJ. See the attached screenshot.

![edge2](https://user-images.githubusercontent.com/11820506/35644240-6b671bfe-0696-11e8-85c2-e5dbc99f460a.png)

Steps to reproduce:
1. Sign into IntelliJ
2. Select VCS > Import into Version Control > Set up on Cloud Source Repositories
3. In the Set up on Google Cloud Source Repositories dialog, click the ellipse and click add account
4. Select a new account.
5. Return to Set up on Google Cloud Source Repositories dialog
6. Click the Create a new Cloud Repository button
7. See error in Console.

Looks like IntelliJ is sending the first account and not the one I selected because it does not happen if I run through these steps again but in reverse order.

**Comment by etanshaul** [comment]
I actually don't think this is an issue with the plugin:

Clicking the "create a new cloud repository" button is agnostic as to the account you are signed into on pantheon. It simply constructs and opens a URL in this form:

https://pantheon.corp.google.com/code/develop/repo?project=test-metrics

It would be up to the user to switch accounts on pantheon. I don't think there is a way to send this information as part of the get request (I don't know this 100% though).

Am I correct that the user can get around this by then just selecting the correct project in the web console?

**Comment by etanshaul** [comment]
I may have spoke to soon. Looks like if we add:

`authuser=[user_name]`

to the url, it will direct the user to the correct account on the console.

I'll test this out. Thanks!
