### ISSUE TITLE
Switching accounts doesn't update project selector (in GCS view)

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/google-cloud-intellij#1883]
1) Sign in to 2 different accounts
2) open the GCS browser
3) swap between the 2 accounts (in the top right widget)

notice that the project selector stays on the original accont

**Comment by etanshaul** [comment]
actually on second thought. this is probably correct behavior. @ivanporty wdyt?

**Comment by etanshaul** [comment]
While I think the original scenario desribed is correct behavior, there are some weird things:

1) sign in to 2 accounts
2) on the project selector in GCS, select a project from account A
3) log out of all accounts using the widget
4) sign back into account B only
5) notice the state of the project selector: it shows the project from account A and looks like you are still signed in

**Comment by ivanporty** [comment]
Looks like the same dilemma - we designed project selector to keep current selection of {project ID, account}. It shows what's selected. For now we show sign in request when no one is signed in, that's straightforward, but how do we request sign for a specific account? I.e. if we open sign in page, it will only show whatever is available in browser and account we need may not even be there.

**Comment by etanshaul** [comment]
yeah. but for the sake of discussion, disregarding implementation (and what is possible with the way we designed the selector etc.), I think the ideal outcome for the scenario I descibed is that it shows the last selected project from account A but with the sign in message:

![image](https://user-images.githubusercontent.com/1735744/35691616-edb6c004-0746-11e8-930c-d4b9b3ede5da.png)

Its a bit strange that after step 3, when signed out of everything, we show this:

![image](https://user-images.githubusercontent.com/1735744/35691688-21402348-0747-11e8-8dcd-727a6bcca5c4.png)

then after signing into account B we show account A on the selector as if that was the account we signed into (the email shown below is account A, not account B):

![image](https://user-images.githubusercontent.com/1735744/35691718-3b86793c-0747-11e8-8b57-7cb9c4c95489.png)

**Comment by ivanporty** [comment]
How about we show the actual account name? So it will show something like:
`Sign in with you test@google.com account`

**Comment by etanshaul** [comment]
do you mean showing that after step 4? I'm ok with that, but I think just showing "sign in with your Google account" is already an improvement.

**Comment by ivanporty** [comment]
I mean exactly for type of cases you describe - if account selected is not signed in, we show a prompt to sign in and show it even if another account is already signed in?

**Comment by etanshaul** [comment]
yea that would be great

just as a side note, I don't think any of this is a huge problem or release blocking since its fairly easy to figure out whats going. But it would nice to make it perfect :)

**Comment by ivanporty** [comment]
Cool I like it, we'll just make sure it's visible which account needs signing in, perfect for cases with a few different accounts.
