### ISSUE TITLE
Local debug is not working

### ISSUE THREAD

**Issue by Ajk2rxKamehameha** [GoogleCloudPlatform/google-cloud-intellij#1888]
Hi, 
I am using IntelliJ community addition and building an app engine standard environment application with Gradle. I was using Android Studio before migrating to IntelliJ and endpoint framework. I am not able to debug my localhost. I added jvmFlags as explained here:
https://cloud.google.com/appengine/docs/standard/java/tools/gradle

appengine {
      run {
        jvmFlags = ['-Xdebug', '-Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=8080']
      }
    }

And deployed my app to local with debug button. But the app didn't deploy and stuck in 
**Listening for transport dt_socket at address: 8080**

Thanks.

**Comment by patflynn** [comment]
@Ajk2rxKamehameha  8080 is usually the devappserver http port.  You porbably want to use 5005 for the remote debugger as I think that's what the IJ remote debug run config defaults to.

**Comment by Ajk2rxKamehameha** [comment]
Hi, I actually want to debug localhost. I tried with 5005 also and I am still stuck at  Listening for transport dt_socket at address: 8080. 

My Gradle configuration look like this:

```
group 'io.xyz.backend'
version '1.0-SNAPSHOT'

buildscript {
    repositories {
        mavenCentral()
        jcenter()
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath 'com.google.cloud.tools:appengine-gradle-plugin:1.3.3'
        classpath "net.ltgt.gradle:gradle-apt-plugin:0.12"
        classpath 'com.google.cloud.tools:endpoints-framework-gradle-plugin:1.0.2'
    }
}

repositories {   // repositories for Jar's you access in your code
    mavenCentral()
    jcenter()
}

apply plugin: 'java'
apply plugin: 'war'
apply plugin: 'com.google.cloud.tools.appengine'
apply plugin: 'com.google.cloud.tools.endpoints-framework-server'


sourceCompatibility = JavaVersion.VERSION_1_7
targetCompatibility = JavaVersion.VERSION_1_7

dependencies {
    compile group: 'com.google.appengine', name: 'appengine-api-1.0-sdk', version: '+'
    compile group: 'com.google.endpoints', name: 'endpoints-framework', version: '2.0.8'
    compile 'javax.servlet:servlet-api:2.5'
    compile 'com.google.guava:guava:19.0'//add this
    compile 'com.googlecode.objectify:objectify:5.1.12'  //works with ObjectifyFilter in web.xml
    compile 'com.squareup.retrofit2:retrofit:2.0.2'
    compile 'com.squareup.retrofit2:converter-gson:2.0.2'
    compile 'com.squareup.okhttp3:okhttp-urlconnection:3.1.2'
    compile 'com.squareup.okhttp:okhttp:2.4.0'
    compile 'org.apache.commons:commons-lang3:3.5'
    compile 'com.googlecode.json-simple:json-simple:1.1.1'
    compile 'org.json:json:20160212'
    compile 'com.google.http-client:google-http-client:1.20.0'
    compile 'com.google.appengine.tools:appengine-gcs-client:0.6'
    compile 'com.google.gcm:gcm-server:1.0.0'
    compile group: 'commons-io', name: 'commons-io', version: '2.0.1'
    compile group: 'org.jsoup', name: 'jsoup', version: '1.10.1'
    compile 'com.google.code.gson:gson:2.6.1'
    compile group: 'org.springframework', name: 'spring-beans', version: '4.3.11.RELEASE'
    compileOnly 'javax.annotation:javax.annotation-api:1.2'
    compileOnly "org.projectlombok:lombok:1.16.18"
    compile 'com.google.cloud:google-cloud-storage:1.8.0'
    compile group: 'com.fasterxml.jackson.core', name: 'jackson-databind', version: '2.0.1'
    compile 'com.google.firebase:firebase-admin:5.8.0'
    compile 'com.google.endpoints:endpoints-management-control-appengine:1.0.5'
    compile 'com.google.endpoints:endpoints-framework-auth:1.0.5'
}

appengine {

    run {
        host = "0.0.0.0"
        port = 8080
        jvmFlags = ['-Xdebug', '-Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=5005']
    }

    deploy {   // deploy configuration
        version = findProperty("appengine.deploy.version")

        def promoteProp = findProperty("appengine.deploy.promote")
        if (promoteProp != null) {
            promote = new Boolean(promoteProp)
        }

    }

}

endpointsServer {
    hostname = "xyz.appspot.com"
}

```

**Comment by patflynn** [comment]
How are you trying to connect?  Once you see the message that it's listening on 5005 you need to connect to it with your debugger (using a remote debug configuration from your IDE) for it to proceed.

**Comment by etanshaul** [comment]
hi @Ajk2rxKamehameha. To elaborate on what @patflynn:

1) greate a new gradle run-config:
<img width="317" alt="screen shot 2018-02-08 at 1 33 06 pm" src="https://user-images.githubusercontent.com/1735744/35991260-a07e51a6-0cd4-11e8-85d8-2146dd6980ae.png">

2) Configure it to run the `appengineRun` task of the `appengine-gradle-plugin`. For `Gradle Project` choose the module in which you configured the `appengine-gradle-plugin`:
<img width="752" alt="screen shot 2018-02-08 at 1 33 33 pm" src="https://user-images.githubusercontent.com/1735744/35991296-c598fc3e-0cd4-11e8-8693-8465541ad3be.png">

3) Create a remote debug run config;
<img width="306" alt="screen shot 2018-02-08 at 1 34 37 pm" src="https://user-images.githubusercontent.com/1735744/35991308-d490c85c-0cd4-11e8-8d91-525aeec0b8b1.png">

4) Configure it with a `Before Launch` task: click the `+` choose `Run another configuration`, and select the run-config you created in step one:
<img width="395" alt="screen shot 2018-02-08 at 1 35 03 pm" src="https://user-images.githubusercontent.com/1735744/35991362-feaaa9be-0cd4-11e8-9f8f-5a34a814f05b.png">

Debug using the remote debug config created in step 3 (by selecting it in the drop down and clicking debug, as usual):
<img width="235" alt="screen shot 2018-02-08 at 1 36 37 pm" src="https://user-images.githubusercontent.com/1735744/35991409-1a08905e-0cd5-11e8-9f54-f67b1d5a22f0.png">

**Comment by Ajk2rxKamehameha** [comment]
@patflynn @etanshaul Thank you, guys. It worked like charm. 👍

**Comment by etanshaul** [comment]
@Ajk2rxKamehameha thats great! thanks for the update.
