### ISSUE TITLE
Creating a new AE standard Java app using the new module wizard (non EE) creates an app with no appengine-web.xml

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#1903]
this is in master.

steps to reproduce:
1. start IDE
1. new project
1. Java -> web application -> Google App Engien Standard (w/ a java 8 JDK)
1. set cloud sdk to something valid
1. next
1. observe in the src tree that there is no appengine-web.xml
1. observe you get a notification that your app engine module doesn't support java 8 and should be java 7 (odd right?)
1. observe that the run configuration seem to be OK about everything 
1. try to run locally and observe:
`Error running 'Google App Engine Standard Local Server': Error running Google App Engine Dev Server. Exception occurred : com.google.cloud.tools.appengine.api.AppEngineException Exception message : java.nio.file.NoSuchFileException: /usr/local/google/home/paflynn/IdeaProjects/delete2/out/artifacts/delete2_war_exploded/WEB-INF/appengine-web.xm`

**Comment by patflynn** [comment]
this seems to be happening for Java EE module wizard too.

**Comment by etanshaul** [comment]
Just a guess: but is it also not creating a web.xml (since it’s now using
servlet 3+)? This might be causing the logic that generates the app
engine-web.xml to fail since it can’t find the web.xml.

**Comment by etanshaul** [comment]
@nbashirbello mind looking into this since its related to resent work you were doing?

**Comment by nbashirbello** [comment]
@etanshaul is right.

web.xml is not getting generated so IntelliJ's WebFacetImpl#getWebXmlDescriptor returns null when we call it to determine the parent for the appengine-web.xml.

**Comment by etanshaul** [comment]
closed via 1927
