### ISSUE TITLE
Sign in from CSR checkout doesn't complete

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#1904]
- Cloud Tools for IntelliJ version: master
- OS: linux

**What did you do?**
1. run gradlew runIde
1. make sure all projects are closed
1. make sure all your are fully google logged out from the IDE.
1. from welcome dialog select 'checkout from version control'
1. pick google cloud 
1. try to login from the  login widget
1. go through the browser song and dance until you see the successful login landing page
1. observe:
![screenshot from 2018-02-14 10-10-46](https://user-images.githubusercontent.com/7862557/36211490-5ef36e02-116f-11e8-9ae8-b02f36616396.png)
 is still there waiting for login to complete.
1. I had to restart the process to find that the user was logged in. 
1. adding a new second logged completes except the logged in user does not appear in the project selector until you restart the process as well.

**Comment by etanshaul** [comment]
I wonder if this has something to do with missing project context
