### ISSUE TITLE
Auto-update App Engine Run config with Cloud Client Lib env vars

### ISSUE THREAD

**Issue by nbashirbello** [GoogleCloudPlatform/google-cloud-intellij#1917]
Add functionality to allow the user to easily update an existing/or create a new App Engine Standard Local Server by specifying the 
- GOOGLE_APPLICATION_CREDENTIALS
- GOOGLE_CLOUD_PROJECT

from the Service Account Key Created confirmation dialog

<img width="716" alt="screen shot 2018-02-15 at 3 37 45 pm" src="https://user-images.githubusercontent.com/6805942/36280212-8f29c7e4-1267-11e8-8115-f72b70b0e6a3.png">

This option should only be visible is the project is an App Engine Standard project.

**Comment by etanshaul** [comment]
note to self: fix the background color of that text pane on OSX

**Comment by etanshaul** [comment]
@nbashirbello check out: https://github.com/GoogleCloudPlatform/google-cloud-java#specifying-a-project-id

specifically:

> When using google-cloud libraries from within Compute/App Engine, there's no need to specify a project ID. It is automatically inferred from the production environment.

Does that conflict with your findings?

**Comment by etanshaul** [comment]
oops never mind - I was rereading the readme and that clearly states "projects running **from within** compute/AE". so not applicable necessarily to running locally.

**Comment by nbashirbello** [comment]
2 options to auto update the GAE config with the environment variables:

![new mockup 4](https://user-images.githubusercontent.com/6805942/36805255-ef169c04-1c8a-11e8-957a-ee7279e1270f.png)

Move the "Name" into a new dialog, that will update the combobox with the newly created local server

![new mockup 5](https://user-images.githubusercontent.com/6805942/36805335-1ec25010-1c8b-11e8-9de9-d492b68a9244.png)

**Comment by etanshaul** [comment]
Regarding the ability to create a new run configuration:

The option of automatically adding the env vars to the run config should only appear if its already an App Engine standard app right? In that case (where it is already AE standard), then the run configuration _should_ already exist. So I'm wondering if we really need the ability to create a new one from this UI.

**Comment by etanshaul** [comment]
nit (not sure if this is better, but just a suggestion):

> Automatically add environment variables to Google App Engine Local Server

->

> Update existing Google App Engine Standard Local Server with these environment variables

**Comment by patflynn** [comment]
You'd want to be able to apply them to multiple run configs.

The 'print to console' button is interesting.  Is that because you can't
copy text from the UI?

**Comment by nbashirbello** [comment]
In regards to the 'print to console', the current implementation actually has a button to copy the GOOGLE_APPLICATION_CREDENTIALS but when you have 2 environment variables, you will need to enter each on a different line in the run config dialog. But by the time you copy the first var, you would have to close the "Service Account Key Created' dialog to open the run config dialog and then you can't see the 2nd var. If the vars are in the console, its easier to copy and paste when the run config dialog is open.

**Comment by etanshaul** [comment]
I do like the print to console idea. But just to clarify: 

>  If the vars are in the console, its easier to copy and paste when the run config dialog is open.

Is this true? I thought that if the run configuration is open you can't access things outside of the dialog (including the console).

**Comment by nbashirbello** [comment]
That is true. They can't access the console when the config dialog is open but they would be able to see the values no matter what dialog is opened.

**Comment by etanshaul** [comment]
I like it. Copying the whole env var string was only useful for certain situations (setting it from the command line for example; less so when using it in a structured UI).

**Comment by patflynn** [comment]
What about clipboard history?  Is that accessible while copy/pasting in the
IDEA menus?

**Comment by etanshaul** [comment]
looks like paste from history is not accessible from the dialog. too bad, I was about to suggest we change the action to "copy and print to console" or something like that.

**Comment by etanshaul** [comment]
actually... its still available via the shortcut (alt+shit+v). so maybe my suggestion is valid?

**Comment by patflynn** [comment]
can we programmatically access the history?

**Comment by etanshaul** [comment]
> can we programmatically access the history?

I don't follow why we'd want this?

**Comment by patflynn** [comment]
Conceivably we could have a button that says 'copy environment variables to
clipboard history' and put them both in the history as separate elements.

granted the user would have to be educated about accessing the history
which might be too much to ask. (although it's a very useful feature to
learn about!)

**Comment by etanshaul** [comment]
Ah I see. Even if the history can't be accessed programmatically we could still just programmatically copy them individually one at a time.

Or, just copy the whole thing since the copy history UI still lets you select and copy parts of the entry (which is useful for the UI where you need each key and value individually). Admittedly I had forgotten about this history feature myself so I wouldn't have known what to do with it right away.

@nbashirbello wdyt?

**Comment by etanshaul** [comment]
update: I was referring to the "paste from history" feature in intellij. not any native OS clipboard history. so take my comments fwiw

**Comment by nbashirbello** [comment]
Updated mock to allow for selecting multiple App Engine Standard servers

![new mockup 0302](https://user-images.githubusercontent.com/6805942/36919827-a43df936-1e2c-11e8-80e3-2938767324cf.png)

**Comment by etanshaul** [comment]
nit: the wording above the run config selector should probably reference the selector. something like:

"Update [the following] Google App Engine..."

What are your thoughts on the default value of which is selected? I'm thinking all of them?

**Comment by nbashirbello** [comment]
All the configs would be enabled initially.

**Comment by etanshaul** [comment]
this has been merged. closing
