### ISSUE TITLE
Can't build the plugin with CE

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/google-cloud-intellij#1933]
I'm getting dependency resolution failures:

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':google-cloud-tools-plugin:compileClasspath'.
> Could not find plugins/Groovy/lib/duplicates-groovy.jar (org.jetbrains.plugins:Groovy:2017.3).
  Searched in the following locations:
      file:/Users/eshaul/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2017.3/6b687670c9f987e74932316665ef9b58823a177/ideaIC-2017.3/org.jetbrains.plugins/Groovy/2017.3/plugins/Groovy/lib/duplicates-groovy-2017.3.jar
      file:/Users/eshaul/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2017.3/6b687670c9f987e74932316665ef9b58823a177/ideaIC-2017.3/plugins/Groovy/lib/duplicates-groovy.jar
      file:/Users/eshaul/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2017.3/34457b330cf276e55fcadd96d7c8be3410866b19/plugins/Groovy/lib/duplicates-groovy-2017.3-[classifier].jar
```

**Comment by etanshaul** [comment]
@ivanporty do you mind confirming that you get this issue too? Just want to be 100% its not a local issue.

Just update gradle.properties to point to 'IC' instead of 'IU' and try running the plugin.

**Comment by ivanporty** [comment]
checking

**Comment by etanshaul** [comment]
its really weird and I can't yet explain it, but after messing around (deleting gradle caches, switching between ultimate and community, moving things around in the build.gradle to try and pinpoint this) it now works in Community (with no local code changes).

**Comment by etanshaul** [comment]
deleting the gradle caches previously didn't do anything so I don't understand why its working now

**Comment by ivanporty** [comment]
Confirmed in Linux - I see the same Groovy error. Trying Mac

**Comment by etanshaul** [comment]
ok thanks. thats kinda what I expected. do you mind trying again after deleting you gradle caches (under ~/.gradle/caches)? will take a bit of time to rebuild after doing that..sorry

**Comment by ivanporty** [comment]
Mac fails as well (google-cloud-tools-plugin:runIde target).

**Comment by ivanporty** [comment]
I think this could be fixed with properly specifying Ultimate edition for :ultimate module. There is a test glitch there though, looking at it.

**Comment by ivanporty** [comment]
Filed issue with Jetbrains:
https://github.com/JetBrains/gradle-intellij-plugin/issues/278

**Comment by etanshaul** [comment]
@ivanporty can we close this now?

**Comment by ivanporty** [comment]
Sure, good idea. PR is open with the fix pending IJ gradle plugin release.

**Comment by etanshaul** [comment]
@ivanporty ah right I forgot about that. In that case, I think it makes sense to keep open for tracking? I can move it off this next milestone though since we have it under control.
