### ISSUE TITLE
Create web root in canonical locations if missing for Maven and Gradle

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/google-cloud-intellij#1948]
This is a follow up to https://github.com/GoogleCloudPlatform/google-cloud-intellij/issues/1903

If no web root exists in the project (as could be common with frameworks like spring boot). We need to create one in order to properly place the `appengine-web.xml` when adding App Engine standard framework support.

The root should be created according to the standard directory layouts for Maven or Gradle. For example, if it is a Maven project:

`src/main/webapp`

**Comment by patflynn** [comment]
if the web facet is present we should use the web facet web resource location and create the directory if it doesn't exist. 

@saturnism found that mavne spring boot apps seem to get this facet automatically but with a pointer to the maven configured web resource folder even if it hasn't materialized yet.

**Comment by etanshaul** [comment]
agree. same thing happens for gradle

**Comment by etanshaul** [comment]
however, just to point out, if the user is using Community, the web facet will not be present. In this case it should still do the right thing for maven/gradle projects.

**Comment by patflynn** [comment]
+1. For community,  I wonder if if we can query the web resource root directly out of the gradle and/or maven integration? Presumably that's how ultimate configures the facet.

**Comment by etanshaul** [comment]
yeah, I don't know where Ultimate gets it from..whether its querying the maven/gradle build or if it just uses a well-known location. Ill check

**Comment by etanshaul** [comment]
Turns out IDEA does fetch the web resource directory directly from the maven/gradle integration. For maven the strategy is as follows:

1) Using `MavenProject`, get the `maven-war-plugin` config
2) With the war plugin config, find the "warSourceDirectory" value
3) a. if not null -> use this one
    b. if null -> use the default "src/main/webapp" folder

Gradle is similar (albeit the method for fetching info from Gradle is much different).

Approach for generating appengine-web.xml properly for Community maven/gradle projects (for Ultimate our job is simpler due to the web facet - already complete in #2203):
- Create a new `AppEngineWebXmlDirectoryProvider` extension point
- Create `MavenAppEngineWebXmlDirectoryProvider` and `GradleAppEngineWebXmlDirectoryProvider` extensions in their respective modules
- In each extension, use the same approach as described above for locating the web resource directory to for placing the `appengine-web.xml`

**Comment by patflynn** [comment]
nice!
