### ISSUE TITLE
Upgrade to 18.3.1: Fatal error initializing plugin com.google.gct.core

### ISSUE THREAD

**Issue by maohieng** [GoogleCloudPlatform/google-cloud-intellij#1972]
After I upgrade Google Cloud Tools plugin on my Ultimate 2017.2 to the latest version 18.3.1, I cannot open my project anymore. The message show as below:

    Cannot load project:
    com.intellij.ide.plugins.PluginManager$StartupAbortedException:
    Fatal error initializing plugin com.google.gct.core

What can I do to fix this?
Thanks,

**Comment by etanshaul** [comment]
hi @maohieng is there any more info from this error that you can find? Perhaps a stacktrace that was shown in the error dialog? If not, you could try:

Help -> Show Log in Files, and open the IDE log

and paste in some of the log statements here around when you get this error.

**Comment by etanshaul** [comment]
@maohieng we found the issue:

https://github.com/GoogleCloudPlatform/google-cloud-intellij/pull/1974

We will merge in this fix and release a new version of the plugin (**18.3.2**) ASAP (within an hour or two). I'll update here once its been released.

Sorry, and thanks for reporting this!

**Comment by etanshaul** [comment]
@maohieng release [18.3.2](https://plugins.jetbrains.com/plugin/8079-google-cloud-tools/update/44471) is now out. If you update the plugin to this version, this error should go away. Thanks again.

**Comment by maohieng** [comment]
The error is gone now. Thank you.
