### ISSUE TITLE
Fix errorprone warnings in CloudLibraryProjectStateTest.java

### ISSUE THREAD

**Issue by ivanporty** [GoogleCloudPlatform/google-cloud-intellij#1988]
google-cloud-intellij/google-cloud-tools-plugin/testSrc/com/google/cloud/tools/intellij/apis/CloudLibraryProjectStateTest.java:119: warning: [CatchFail] Ignoring exceptions and calling fail() is unnecessary, and makes test output less useful
                        try {
                        ^
    (see http://errorprone.info/bugpattern/CatchFail)
google-cloud-intellij/google-cloud-tools-plugin/testSrc/com/google/cloud/tools/intellij/apis/CloudLibraryProjectStateTest.java:120: warning: [DefaultCharset] Implicit use of the platform default charset, which can result in e.g. non-ASCII characters being silently replaced with '?' in many environments
                          mavenProject.getFile().setBinaryContent("not a valid pom.xml".getBytes());
                                                                                                ^
    (see http://errorprone.info/bugpattern/DefaultCharset)
  Did you mean 'mavenProject.getFile().setBinaryContent("not a valid pom.xml".getBytes(UTF_8));' or 'mavenProject.getFile().setBinaryContent("not a valid pom.xml".getBytes(Charset.defaultCharset()));'?

**Comment by etanshaul** [comment]
oops. thanks for catching this.
