### ISSUE TITLE
Error message about JRE whitelist while using java8 runtime

### ISSUE THREAD

**Issue by Trii** [GoogleCloudPlatform/google-cloud-intellij#2004]
- Cloud Tools for IntelliJ version: 18.3.2
- Google Cloud SDK version _(run `gcloud version` on the command line)_:
```
josh$ gcloud version
Google Cloud SDK 196.0.0
alpha 2017.09.15
app-engine-java 1.9.63
app-engine-python 1.9.67
beta 2017.09.15
bq 2.0.31
core 2018.03.30
datalab 20180213
gcloud
gsutil 4.30
kubectl
```

```
josh$ gcloud info
Google Cloud SDK [196.0.0]

Platform: [Mac OS X, x86_64] ('Darwin', 'JoshJ.lan', '17.4.0', 'Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64', 'x86_64', 'i386')
Python Version: [2.7.10 (default, Jul 15 2017, 17:16:57)  [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]]
Python Location: [/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python]
Site Packages: [Enabled]

Installation Root: [/Users/josh/Developer/Library/google-cloud-sdk]
```

- OS: macOS 10.13.3

**What did you do?**

Import and use `java.time.LocalDateTime`

**What did you expect to see?**

No red squiggles

**What did you see instead?**

![image](https://user-images.githubusercontent.com/638073/38370446-1bbeff50-38b8-11e8-826c-4c29daade60f.png)

This is a multi-module maven project. I see the error in a common utilities module that is not directly configured as an App Engine module. pom.xml below. 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>afl</groupId>
        <artifactId>application</artifactId>
        <version>3.6.0</version>
    </parent>
    <artifactId>afl-common</artifactId>
    <packaging>jar</packaging>
    <properties>
    </properties>
    <dependencies>
        <dependency>
            <groupId>afl</groupId>
            <artifactId>afl-test</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.google.apis</groupId>
            <artifactId>google-api-services-bigquery</artifactId>
            <version>v2-rev158-1.19.0</version>
            <exclusions>
                <!-- creates conflicts with another guava version in appengine-gcs-client -->
                <exclusion>
                    <groupId>com.google.guava</groupId>
                    <artifactId>guava-jdk5</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
    </dependencies>

    <build>
        <resources>
        </resources>
        <testResources>
            <testResource>
                <directory>src/test/resources</directory>
            </testResource>
            <testResource>
                <directory>src/int-test/resources</directory>
            </testResource>
        </testResources>
    </build>
</project>
```

**Comment by patflynn** [comment]
@Trii Thanks for the detailed report. 

Is it possible you somehow have added the App Engine Standard facet to this common module?  Does it have an appengine-web.xml?

**Comment by Trii** [comment]
@patflynn that's the other fun part. IntelliJ keeps adding the App Engine Standard facet to it automatically no matter now many times I delete it. It does not have an appengine-web.xml.

![image](https://user-images.githubusercontent.com/638073/38373792-0acfae8a-38c0-11e8-9785-c00f9f5b3319.png)

I'm wondering if half of this is a bug in IDEA. It also keeps resetting the language level to 7, even though my parent pom specifies 1.8

**Comment by etanshaul** [comment]
@Trii that is odd. If you try manually deleting the App Enging standard facet: 

Project Settings -> Facets -> Select and delete the App Engine standard facet

Does that at least solve the issue of marking your line of code as invalid (due to not being in the whitelist)?

**Comment by etanshaul** [comment]
Also, the plugin _shouldn't_ ever be adding the App Engine facet automatically to your project. There should always be a prompt (based on the presence of an `appengine-web.xml` in one of your modules) that you can either accept, or ignore. If you are seeing otherwise, then it could definitely be a bug.

**Comment by Trii** [comment]
@etanshaul when I manually delete the facet, the error clears. It seems every time I build with maven via IntelliJ the facet gets added to every module in my project. Now I am wondering if my parent pom is declaring a dependency that causes the facet to be added again.

**Comment by etanshaul** [comment]
@Trii 

Do you happen to have a dependency, in your `pom.xml` (maybe in the parent pom?), on the `appengine-maven-plugin`?

If so, this is what would be causing the facet to be added every time you sync with Maven (I forgot about this case originally). 

If you do have this dependency - you could either remove it, or migrate to the newer (CloudSdk toolchain based) [app-maven-plugin](https://github.com/GoogleCloudPlatform/app-maven-plugin).

**Comment by Trii** [comment]
@etanshaul blargh! I was hoping it wasn't that. Unfortunately we are using an older, no longer maintained framework for App Engine that specifies the old plugin in it's pom. We are going to migrate over to Spring Boot, but that will take a while. At least I know what it is now, I'll close this issue.

Thank you for all of the help you two.

**Comment by etanshaul** [comment]
sorry for the headache @Trii. I just opened up an issue on our side (#2005) to remove this automatic addition of the facet based on that dependency. It should go out in our next release sometime in April.
