### ISSUE TITLE
No JDK error message not resolving from bundle

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/google-cloud-intellij#2080]
![image](https://user-images.githubusercontent.com/1735744/39446268-ecb648fc-4c8b-11e8-8a5b-b0ccea72cdb1.png)

**Comment by patflynn** [comment]
nice catch. Usually these are caught as compile errors in IJ build. It
would be nice to have them caught by the gradle build too.

**Comment by etanshaul** [comment]
yeah had the same thought. will open an issue to investigate adding this
