### ISSUE TITLE
App Engine module needs access to the Gradle module

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/google-cloud-intellij#2106]
Due to limitation 2 described in #2100, we cannot simply include a depends on the gradle plugin from the app-engine module.

**Comment by etanshaul** [comment]
Similarly we cannot use the workaround used for yaml (of putting it in the root plugin.xml) since gradle is not available in all IDEs.

**Comment by patflynn** [comment]
We may have to split out the appengine gradle support into its own xml.

**Comment by etanshaul** [comment]
Do you recall how the maven module is available from the appengine module? I'm not seeing an explicit depends on maven in that chain.

**Comment by etanshaul** [comment]
yeah it is strange. I don't see maven included directly in com.intellij.modules.java

but I do know for sure that Gradle is not available since I ran into this issue on my branch (that adds gradle stuff to app engine) only after merging in the latest plugin.xml refactoring. I can unblock development by adding the gradle depends alongside the yaml depends (but of course this cannot be a permanent solution).

**Comment by patflynn** [comment]
right.

I think the only solution is for you to keep all your Gradle based features
in a separate app-engine-java-gradle.xml and optionally include it from the
google-cloud-tools-plugin plugin.xml keyed on gradle module.
