### ISSUE TITLE
Background tasks pops up on all App Engine tasks

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/google-cloud-intellij#2107]
This happens even if there are no long running Cloud SDK related background tasks:

![image](https://user-images.githubusercontent.com/1735744/40024612-ded55cfc-579c-11e8-8771-e9eed2b15cb9.png)

**Comment by etanshaul** [comment]
@ivanporty can we limit this to happen only when there is a Cloud SDK task to run?

**Comment by ivanporty** [comment]
Sure, we can do that. I think this is a duplicate of #2077?

**Comment by etanshaul** [comment]
oops. definitely a dup. closing
