### ISSUE TITLE
Consider postponing Managed SDK install until actual deploy/run if user cancelled it once

### ISSUE THREAD

**Issue by ivanporty** [GoogleCloudPlatform/google-cloud-intellij#2113]
According to the metrics, some users do not need or like having Managed Cloud SDK installed when they start IDE or install the plugin and cancel it. Some seems to cancel it multiple times if they restart/update IDE.

To accommodate for this, how about we keep a flag of "user cancelled installation", and do not attempt to install Managed SDK until actual SDK operation is needed (i.e. deploy or cancel). Users who do not cancel will still have Managed SDK installed at the point of plugin installation.

**Comment by patflynn** [comment]
Seems reasonable.

**Comment by etanshaul** [comment]
if we go with your suggestion, would we do the same thing for updates?

**Comment by ivanporty** [comment]
For updates, if SDK is not in installed state, it won't do anything so we should be good here.

**Comment by etanshaul** [comment]
oh. I meant if the SDK is already installed, but they keep cancelling the updates that occur on IDE load. I guess this is less of a nuisance since its less frequent.

**Comment by etanshaul** [comment]
but your original suggestion sgtm

**Comment by ivanporty** [comment]
Yes, update is once per week, and they can just disable it with quick popup action (`Disable updates`)

**Comment by etanshaul** [comment]
good point. lets follow the signals.
