### ISSUE TITLE
Google Cloud Tools menu group lost ordering

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#2123]
I believe  #2100 is the culprit.

![screenshot from 2018-05-21 09-27-32](https://user-images.githubusercontent.com/7862557/40310005-75916fd2-5cd9-11e8-834f-c4d13380e297.png)

**Comment by patflynn** [comment]
Another thing I'm noticing is that the local run action is missing.

**Comment by etanshaul** [comment]
I also noticed that the order is different in UE vs CE.

**Comment by etanshaul** [comment]
see this comment: https://github.com/GoogleCloudPlatform/google-cloud-intellij/pull/2126#issuecomment-390704039

I think a lot of these issues are stemming from the same root cause (in this cause, I think this explains why the local run action is missing)

**Comment by etanshaul** [comment]
for easier reference, here is what the order used to look like:
![image](https://user-images.githubusercontent.com/1735744/40384736-70b2190e-5dd2-11e8-9a91-1d625fa89e01.png)
