### ISSUE TITLE
Add feature matrix / IDE feature breakdown to README

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/google-cloud-intellij#2140]

**Comment by etanshaul** [comment]
ill add you to this repo

**Comment by etanshaul** [comment]
you might wanna still visit [github/](http://github/) and go through all that (and request to join the cloud platform org) so you don't get any CLA issues when submitting prs.

**Comment by parkjam4** [comment]
@etanshaul Looks like this is an old issue that can be closed?

**Comment by etanshaul** [comment]
thanks. closed.
