### ISSUE TITLE
need to clarify IDE support on jetbrains repo plugin details page

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#2150]
currently this is how we describe the plugin:
![screenshot from 2018-05-31 11-52-07](https://user-images.githubusercontent.com/7862557/40792963-219e3732-64c9-11e8-9823-74399b49a946.png)

Seems pretty high priority or people with app engine apps on python and other languages will download this expecting it to be useful to them.

**Comment by etanshaul** [comment]
will put out a patch release to update this soon. agreed that we should get it out quickly

**Comment by etanshaul** [comment]
@parkjam4 if you could help out with this that would be great

**Comment by etanshaul** [comment]
fixed via #2155
