### ISSUE TITLE
Update the feature matrix to include new functionality

### ISSUE THREAD

**Issue by parkjam4** [GoogleCloudPlatform/google-cloud-intellij#2245]
(Please ensure you are running the latest version of Cloud Tools for IntelliJ with _Help > Check for Updates_.)

- Cloud Tools for IntelliJ version:
- Google Cloud SDK version _(run `gcloud version` on the command line)_:
- OS:

**What did you do?**

**What did you expect to see?**

**What did you see instead?**

(screenshots are helpful)

_Feel free to deviate from this template as needed, especially if you are submitting a feature request._

**Comment by etanshaul** [comment]
@parkjam4 has this been fixed? Its unclear from the title exactly what features its referring to.

**Comment by parkjam4** [comment]
I think the work under PR #2247 was for this. I think we can close this.
