### ISSUE TITLE
Add support for Stackdriver Debugger with Kotlin 

### ISSUE THREAD

**Issue by hosswald** [GoogleCloudPlatform/google-cloud-intellij#2253]
(Please ensure you are running the latest version of Cloud Tools for IntelliJ with _Help > Check for Updates_.)

- Cloud Tools for IntelliJ version: 18.8.1
- IntelliJ version: IntelliJ IDEA 2018.2.3 (Ultimate Edition) Build #IU-182.4323.18, built on August 28, 2018
- Google Cloud SDK version _(run `gcloud version` on the command line)_: 179.0.0
- OS: Windows 10

**What did you do?**
Debugged a mixed Java/Kotlin Web App. I can add "Cloud Snapshot Locations" in Java files, but not in Kotlin.

**What did you expect to see?**
The Stackdriver debugger at https://console.cloud.google.com/debug has no problems with .kt files, so I expect that from the IntelliJ plugin as well.

**What did you see instead?**
I can only add normal (local) breakpoints to Kotlin files. I found no way to add Cloud Snapshot Locations to Kotlin files.

Popup opens in Java files when clicking the gutter:
![image](https://user-images.githubusercontent.com/32925139/44847531-12f3d480-ac54-11e8-8098-57dc41fdfbdc.png)

Breakpoint is added directly when clicking the gutter in Kotlin files:
![image](https://user-images.githubusercontent.com/32925139/44847580-3ae33800-ac54-11e8-8efd-4d35a3f7d2be.png)

**Comment by etanshaul** [comment]
Hi @hosswald. you are right that this is something that is currently not yet supported from within the IDE. We'd like to see this working too and will discuss internally to prioritize. Thanks for the request. Will leave this issue open.

**Comment by hosswald** [comment]
Great to hear that, @etanshaul !

**Comment by etanshaul** [comment]
hi @hosswald release **18.10.1** was published and should now allow you to set Stackdriver Debugger breakpoints on Kotlin sources
