### ISSUE TITLE
Callback after account auth request doesn't work

### ISSUE THREAD

**Issue by etcook** [GoogleCloudPlatform/google-cloud-intellij#2286]
- Cloud Tools for IntelliJ version: 18.10.1
- Google Cloud SDK version _(run `gcloud version` on the command line)_: Google Cloud SDK 220.0.0
- OS: OSX

When attempting to add another Google Cloud account, the callback after signing in doesn't seem to work. I get an error that the connection was reset.

<img width="963" alt="image 2018-10-15 at 15 36 06" src="https://user-images.githubusercontent.com/2329397/46976834-21753e80-d090-11e8-9eef-eb86c68f28f2.png">

**Comment by etanshaul** [comment]
Thanks for the report. A couple things to try and debug as I cannot reproduce this myself:

- What version of the IntelliJ are you using?
- Was this functionality working prior to updating to version 18.10.1 of the plugin?
  - If so, are you behind a company firewall that could be blocking this?

**Comment by etcook** [comment]
@etanshaul
- IntelliJ Ultimate: 2018.2.4
- Yes, I believe it was, although I can't seem to use existing accounts either. It shows the projects but it doesn't list out the buckets.
- No firewall, but it's a localhost call, so it likely wouldn't pass through a firewall rule

**Comment by etanshaul** [comment]
Hmm that is odd.

Do you see any exceptions in the IDE by any chance? They usually show up in the gutter in the bottom right of the IDE window - you can then click on them and view the stacktrace.

Also, could you possibly check the logs to see if anything stands out there (help -> show logs)? You could even paste in the latest contents after re-performing the unsuccessful login here if you prefer.

@ivanporty in case anything here stands out to you

**Comment by etanshaul** [comment]
on second look at your response:

You mentioned that you tried to list buckets - so you are signed into the IDE then? Is it just that the callback in the web browser didn't load (but the IDE logs in properly)?

If so, it could have just been an intermittent network error (although if you are still seeing happen then it rules this out). And just to rule it out, regarding the bucket listing - if you are indeed signed in properly, did you confirm in the GCP web console that the project has buckets to list?

**Comment by ivanporty** [comment]
@etcook also interesting to know how did you end up with that callback address in the browser? Did you get the initial landing page when you click `Add Account`, i.e. see the text `Choose an account
to continue to Cloud Tools For IntelliJ` and then you see this address in the browser instead of success message?

**Comment by etcook** [comment]
@etanshaul No exceptions in the event log and the idea.log doesn't seem to reference anything happening in relation to this plugin at all. I tried the login at least half a dozen times. I even tried uninstalling the plugin altogether and reinstalling it, plus restarting IntelliJ a few times to no avail. The behavior is exactly the same.

I can take a video of the event, but would rather email it to someone directly rather than post it in a public forum if possible, since it would have some identifiable information.

I'll try to answer all your questions, please let me know if I missed any:

1) It looks like I already have an account added, and it can list projects. I know this is working properly because I just added a project to this account and it's showing up. However, I am trying to add an additional account to the list. Regardless, neither is working properly.
2) Once I click on the project, the buckets are not listed. I am sure the project has a number of buckets, and I have Project Owner role.
3) The actual auth part works perfectly. It goes to Google, I sign it and tell it to give IntelliJ permissions, and then it forwards to the localhost callback. This is where it fails.
4) Since the failure is with the localhost listener, I don't believe it's a network or firewall issue.
5) Oddly, even with the account that is already added, the message in the bucket list box is that I will have to sign in to view the buckets. When I click on my name, presumably to sign in, it does the exact same thing. I log in and then it sends me to the localhost callback where the connection is reset.

**Comment by etanshaul** [comment]
Thanks for all those details. 

@chanseokoh I think any insight you have regarding the callback address failure would be great. It seems plausible that that is the root of these issues.

**Comment by chanseokoh** [comment]
> and then it forwards to the localhost callback. This is where it fails.

Yeah, what you said makes sense. For some unknown reason, you cannot connect to the server at `localhost`.

From the error "connection reset" (I am reasonably certain it refers to the [TCP/IP connection reset](https://stackoverflow.com/a/1434506/1701388)), I think whatever server at port 51372 (presumably at `localhost`, the port will change every time) was actually listening but shut down your incoming connection immediately for some reason. Previously, a possible cause included accidentally modifying the local `/etc/hosts` file or a machine having multiple Ethernet interfaces.

There are many ways to diagnose what's going on your machine, and since the issue is specific to your local environment, it's best for you to do some diagnosis. Basically, you need to check if there is a local server actually running and listening HTTP requests when the browser pops up, and trying to access the local server from various clients. The following may help:
https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/2148
https://github.com/GoogleCloudPlatform/google-cloud-intellij/issues/1632

**Comment by etcook** [comment]
I'll try to describe the process instead of recording the interaction:

1) I click on Google Cloud Storage on the right side toolbar (I apologize, I don't know the specific nomenclature for this bar)
2) I click on Add Account
3) It immediately opens up my browser, where I log in to Google and give it permissions
4) Once I accept those, it forwards me to the localhost callback, and I see the connection reset errors above. The port changes at random.
5) I go back to IntelliJ and I close the window. Behind it is a status window indicating I should be logging in in the browser. I end up canceling it because it's not working.

<img width="466" alt="image 2018-10-15 at 16 43 40" src="https://user-images.githubusercontent.com/2329397/46980288-bfb9d200-d099-11e8-933b-49a9c4da5638.png">

**Comment by etcook** [comment]
@chanseokoh This is actually for a Rails app, and I do a lot of development with localhost. I don't believe it's an etc/hosts issue.

I did a netstat, and it doesn't actually look like the port requested is open. I attempted the auth again, and it was using localhost:53700 as a callback url/port. I then tried to do a simple wget and got the following:

`:~ $ wget localhost:53700
--2018-10-15 16:50:59--  http://localhost:53700/
Resolving localhost (localhost)... ::1, fe80::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:53700... failed: Connection refused.
Connecting to localhost (localhost)|fe80::1|:53700... failed: Connection refused.
Connecting to localhost (localhost)|127.0.0.1|:53700... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-10-15 16:50:59 ERROR 404: Not Found.`

**Comment by etcook** [comment]
Actually, after reviewing those links, I amended my wget as a test:

`wget localhost:53700/Callback?error=whatever
--2018-10-15 16:54:53--  http://localhost:53700/Callback?error=whatever
Resolving localhost (localhost)... ::1, fe80::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:53700... failed: Connection refused.
Connecting to localhost (localhost)|fe80::1|:53700... failed: Connection refused.
Connecting to localhost (localhost)|127.0.0.1|:53700... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://cloud.google.com/tools/intellij/auth_failure [following]
--2018-10-15 16:54:53--  https://cloud.google.com/tools/intellij/auth_failure
Resolving cloud.google.com (cloud.google.com)... 216.58.193.142
Connecting to cloud.google.com (cloud.google.com)|216.58.193.142|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 64913 (63K) [text/html]
Saving to: ‘Callback?error=whatever’

Callback?error=whatever                              100%[====================================================================================================================>]  63.39K  --.-KB/s    in 0.04s

2018-10-15 16:54:54 (1.67 MB/s) - ‘Callback?error=whatever’ saved [64913/64913]`

So it seems to be listening properly, but gets reset with the key.

**Comment by etcook** [comment]
@etanshaul @chanseokoh I figured out what the issue was after tracking the redirects and following browser console errors. The forward was being blocked by uBlock Origins, likely because the Google reference triggered an ad rule. I logged in using an incognito window and it worked perfectly. Thank you for your assistance. I'm not sure if there's anything that can be done to mitigate issues like this in the future - I'm likely not the only one that is running an adblocker.

**Comment by chanseokoh** [comment]
Thank you very much for your feedback. It will help future users.

**Comment by etanshaul** [comment]
thanks @etcook for all of the details and the resolution. we'll keep this scenario in mind.

**Comment by patflynn** [comment]
Sounds like a good FAQ entry. I imagine adblockers might be a big
contributor to the errors we've seen.

**Comment by etcook** [comment]
@patflynn If you'd like, I can check out the FAQ, try to replicate the style and submit a PR.

**Comment by etanshaul** [comment]
@etcook we don't really have much of an FAQ on this repo (its really an empty placeholder on the README). But if you'd like to submit a PR to add the first entry that would be great!
