### ISSUE TITLE
DataFlow Future?

### ISSUE THREAD

**Issue by mts57017** [GoogleCloudPlatform/google-cloud-intellij#2288]
Is there any future track to add Dataflow Support?

**Comment by etanshaul** [comment]
hi @mts57017. While this wasn't in our near term plans, I'd be interested in hearing if there were specific features in mind that you would like to see? If so, we can add these into consideration.

**Comment by mts57017** [comment]
oh wow totally missed this message. At the time, eclipse had a dataflow plugin, but this is now somewhat pointless after Dataflow 2.5, as they got away from using gcp libs, and now use pure beam libs.

**Comment by etanshaul** [comment]
closing for now as this isn't on our roadmap
