### ISSUE TITLE
Migrate container-tools issues to this repo

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/google-cloud-intellij#2348]
with a new label for easier organization

**Comment by etanshaul** [comment]
Looks like we can't use [this process](https://help.github.com/en/articles/transferring-an-issue-to-another-repository) because the repos are in different orgs. So it will have to be manual (unless we use the API, which seems like it would be more work than just a manual transfer).

**Comment by ivanporty** [comment]
@etanshaul Migrated issues created by myself, I can also migrate your issues (~10 left) if you want or you can re-create them so we can keep the ownership.

**Comment by etanshaul** [comment]
thanks for getting this started. feel free to migrate them all. I'm not concerned about the ownership.
