### ISSUE TITLE
Skaffold detection doesn't work in windows

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/google-cloud-intellij#2386]
In windows the executable is `skaffold.exe`

**Comment by ivanporty** [comment]
Testing this on Windows laptop (not VM). Detection / configuration all seem to work as intended. Did you mean skaffold is not properly executed? tried it with custom path to skaffold and it's working, checking with system PATH and restart now.

**Comment by etanshaul** [comment]
yeah. it was with the system path. I haven't tested yet with the new custom path ui - good to know thats working.

**Comment by ivanporty** [comment]
Doesn't seem to work with skaffold present in Windows `Path`. Regardless of `.exe` suffix present.

**Comment by ivanporty** [comment]
The problem was in incomplete PATH and skaffold name based check before the run which prevented actual Skaffold to be executed. We decided to go with the original design to test-launch Skaffold in #2425 and now it works fine.
