### ISSUE TITLE
Skaffold executable not found on the IDE Path with running standalone on OSX

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/google-cloud-intellij#2388]
<img alt="screen shot 2019-02-01 at 3 27 03 pm" width="1037" src="https://user-images.githubusercontent.com/1735744/52156017-bc9c1f00-2653-11e9-9ef7-e2490ec730d3.png">

When the IDE is launched from the shell then it fixes the problem.

While the CLI installer will ultimately solve this, an intermediate solution is to check well known locations for the skaffold executable and use those if not found on the path, e.g. `/usr/local/bin/skaffold`

**Comment by ivanporty** [comment]
We can at least add install locations for Linux and Mac - those are the ones used for majority of installs: Mac and Linux: `/usr/local/bin`. Windows just says use PATH, so we need to test if it works when launched from the UI menu.

**Comment by etanshaul** [comment]
fixed via #2420
