### ISSUE TITLE
Add FAQ section in the Kubernetes README

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/google-cloud-intellij#2389]

**Comment by etanshaul** [comment]
a good first candidate is how to deal with this issue (https://github.com/GoogleCloudPlatform/google-cloud-intellij/issues/2394), specifically, when the docker credential helpers can't be found on the path

**Comment by etanshaul** [comment]
@ivanporty I can start this, unless you already have?

**Comment by ivanporty** [comment]
sounds great, go ahead, I'm fixing path issue on windows

**Comment by etanshaul** [comment]
fixed via #2414
