### ISSUE TITLE
Code analysis should send results to team for each PR.

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#240]
Currently findbugs and PMD are just storing the results on local travis and being ignored.  They should store the results somewhere accessible and possibly even break the build. Ideally we could get a nice setup where the PR would list the issues found during code analysis.  A presubmit would also be nice so that people can fix these issues prior to creating a PR.

**Comment by etanshaul** [comment]
obsolete. has been implemented in kokoro / findbugs
