### ISSUE TITLE
Add validation to skaffold override path selector

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/google-cloud-intellij#2404]
see #2397 - this adds a new settings field, but does not have any validation at the moment.

**Comment by sageprice** [comment]
It isn't immediately clear to me what validation is required. I'm reading this as "validate that the supplied override file exists", is this correct? or is there some other validation required?

**Comment by etanshaul** [comment]
If you notice right now in the UI, if you enter a random path - one that doesn't point to a valid Skaffold binary - there is no validation. The user can go ahead and save the panel and isn't aware of the problem until deployment.

This issue is to check the feasibility of adding validation in the Kubernetes setting panel so that the user is informed early. 

One thing to note, is that these panels have a mechanism for displaying errors which block the user from saving the panel (by throwing a `ConfigurationException` (or something like that) from one of the overridden methods). We don't want to use this - the user should still be able to save the panel if they really want to, but at least an error is shown to them.

We have validation that executes at deploy time - by running a simple `skaffold version` to see if that process completes successfully. This issue is around integrating a check like this into the UI panel (but would have to be done in a way that doesn't lock the UI thread causing it to freeze).
