### ISSUE TITLE
Support for IntelliJ 2019.1

### ISSUE THREAD

**Issue by psk-ixolit** [GoogleCloudPlatform/google-cloud-intellij#2471]
- Cloud Tools for IntelliJ version: It forces a downgrade to 16.11.6
- Google Cloud SDK version : 
```
Google Cloud SDK 240.0.0
alpha 2019.03.22
app-engine-java 1.9.72
app-engine-python 1.9.84
beta 2019.03.22
bq 2.0.42
cloud-datastore-emulator 2.1.0
core 2019.03.22
gsutil 4.37
kubectl 2019.03.22
pubsub-emulator 2019.03.22
```
- OS: Ubuntu 18.10

**What did you do?**
Update to Intellij 2019.1

**What did you expect to see?**
A working gcloud tools plugin in the latest version
**What did you see instead?**
A forced downgrade to 16.11.6 version of the plugin, which is no longer working.

**Comment by etanshaul** [comment]
Thanks for reporting. Fix is coming soon.

**Comment by etanshaul** [comment]
fixed with patch release 19.3.1. Please update the plugin and let us know if things don't work as expected in 2019.1. Thanks again for reporting.

**Comment by psk-ixolit** [comment]
Thanks, it works.

**Comment by etanshaul** [comment]
great. thank you for confirming!
