### ISSUE TITLE
Import sources to Google Cloud should not ask authentication

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/google-cloud-intellij#347]
I've cloned the sample idea project (https://github.com/GoogleCloudPlatform/cloud-debugger-idea-sample), imported into IDEA, then tried to upload to Google Cloud repository (VCS/Import into Version Control/Upload project to Google Cloud). After selecting the project, it asks for authentication and requests the passphrase for my github ssh key, which should not happen, I'd assume it should use the account I used to log into Google.

**Comment by patflynn** [comment]
I wonder if we're detecting this as a github project and trying to push to
github instead of importing to gcp.

**Comment by akerekes** [comment]
After giving my passphrase, first the push timed out and gave an error, but the second time it went through and successfully uploaded the project to the Google Cloud repository.
Does it maybe check with github if the local copy has any changes compared to origin/master?

**Comment by elharo** [comment]
I wonder if this might have anything to do with whether you cklone anonymously or not when you first checkout the repo from Github?

**Comment by etanshaul** [comment]
@akerekes do you remember what OS this was on?

**Comment by akerekes** [comment]
Most probably Linux.

**Comment by etanshaul** [comment]
Closing. Dup of #1011, #1174
