### ISSUE TITLE
Delete all breakpoints button should delete all IDE breakpoints

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/google-cloud-intellij#473]
If the user is in an active debug session, and sets a breakpoint and clicks on the "Delete All" button in the debug panel, all breakpoints are deleted from the debug panel, but in the editor, the gutter icon remains visible (in disabled state). If the user deletes all breakpoints, then all markers from the editor should also be deleted.

**Comment by akerekes** [comment]
If the user sends the debug session into the background and resumes it, clicking on "Delete all" won't change the icon of the gutter icon in the editor's margin, it'll be shown as a solid blue disc (won't be shown as disabled unlike in the case above)

**Comment by joaoandremartins** [comment]
This and #437 appear to be dupes.
