### ISSUE TITLE
Create a new project wording in the project selector is API dev console specific, and inappropriate for Cloud

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#613]
wording is currently 'Click here to create a new Google Developers Console project'.  This is appropriate for people creating a project to use an API, but not for GCP. 

This is a little tricky as depending on the use case, you might prefer one or the other.

**Comment by etanshaul** [comment]
If we update the wording to "...a new Google Cloud Platform project", wouldn't this cover all scenarios?

**Comment by patflynn** [comment]
Not for Android Studio users who are just creating a project for the purpose of being able to call an API. The underlying project is the same, but the messaging and landing pages are different.

**Comment by etanshaul** [comment]
obsolete (project selector has been completely redone)
