### ISSUE TITLE
Auto download cloud sdk if not installed

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/google-cloud-intellij#673]
If the user doesn't have the cloud sdk pre-installed it would reduce a lot of friction if we had an option (perhaps from within the cloud configuration) to download and install it for them.

**Comment by patflynn** [comment]
I would add that potentially you could completely hide the Cloud SDK dependency if you can resolve it entirely under the covers in the plugin.

**Comment by etanshaul** [comment]
@ivanporty using this as the overall issue to track this effort, unless there is a dup?

**Comment by ivanporty** [comment]
sounds good
