### ISSUE TITLE
Docker configuration should include entire directory

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/google-cloud-intellij#703]
When specifying a docker config - for flex etc. - its not only the Dockerfile that needs to be staged but the contents of the folder in which the docker file lives (e.g. src/main/docker) as these could be used by the docker build. 

This issue to is to track that we are correctly staging these files for all applicable deployment paths.

**Comment by etanshaul** [comment]
dup

**Comment by joaoandremartins** [comment]
dupe of #1304 I think
