### ISSUE TITLE
Git push should trigger the same checking as travis.

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#709]
When a user pushes, we should run the same tests as travis to notify the user if the CI is likely to fail.

**Comment by etanshaul** [comment]
Do you mean something like a client-side [git hook](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks) that runs gradle check (or whatever)? That could be cool.

**Comment by patflynn** [comment]
yeah!

**Comment by chanseokoh** [comment]
I could do something like below locally, if the purpose is to explicitly trigger a check locally and show a notification locally for the sake of convenience:

```bash
#!/bin/sh
git push @*
if [ $? == 0 ] && [ in a git repo directory ] && [ -e gradlew ]; then
  gradlew clean check # Perhaps we could do this in a background
  if [ $? != 0 ]; then
    notify-send -t 120000 "Check failed" "Hey, your check failed."
  fi
fi
```

**Comment by patflynn** [comment]
To which hook? pre-commit or pre-push?

**Comment by chanseokoh** [comment]
I wasn't specifically referring to the git hook. Not sure what it is. The above script is just a random stuff I could do locally for myself, to throw some random idea. Not really recommending it.

**Comment by patflynn** [comment]
I'd prefer a solution checked into .git/hooks so it runs for everybody by
default.
