### ISSUE TITLE
Investigate upgrading to the latest version of gradle-intellij-plugin

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#763]
https://github.com/JetBrains/gradle-intellij-plugin

The latest version of gradle-intellij-plugin is 0.1.9.  We are on 0.0.43.

@etanshaul tried it out and found some runtime issues that may be tricky to sort out.

**Comment by etanshaul** [comment]
@patflynn I tried too without much luck. See https://github.com/GoogleCloudPlatform/gcloud-intellij/pull/708 for more details on this.

**Comment by etanshaul** [comment]
fixed via #1779
