### ISSUE TITLE
Auto-suggest project names on Clone project dialog

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/google-cloud-intellij#778]
When checking out a Google repo from an account with many projects, it can be cumbersome to find the right project.
It's possible to start writing with the project dropdown open, but the projects stay static. I don't know if it's possible to auto-refresh the project list according to the string or regex entered by the user, but that would be cool.

**Comment by etanshaul** [comment]
completely agree. @lesv actually had the same feedback. For some reason I thought this was working at some point.

**Comment by etanshaul** [comment]
obsolete (project selector has been redone)
