### ISSUE TITLE
Locate a default JAR/WAR on deployments

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/google-cloud-intellij#779]
On the Create Deployment Configuration window, we should probably try to locate the app JAR/WAR for deployments we know where they are (such as Maven and Gradle) and present that as a default to the users, where they would be able to select different ones if they wanted.

**Comment by etanshaul** [comment]
we do this when the artifacts are available; and for maven we do this regardless.

see #645
