### ISSUE TITLE
Deploy config UI rendering bug

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-intellij#785]
Steps to reproduce:
1. Have at least one more deployment source (in addition to "Filesystem JAR or WAR").
2. Run --> Edit Configurations...
3. Expand "default" and select 'App Engine (BETA) deployment'
4. Select a server.

Now the problem: try switching deployment sources. You'll notice UI components are not re-drawn.

**Comment by etanshaul** [comment]
appears to no longer be a problem
