### ISSUE TITLE
Do we want a new project wizard for flex projects?

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/google-cloud-intellij#789]
@arouzrokh

With the integration work, we will have a new project wizard for standard apps. But since flex apps are just plain old web apps, I don't know if it makes sense. Users can always use the IJ wizard to create a basic web app and deploy that to flex.

**Comment by arouzrokh** [comment]
Agreed.

**Comment by patflynn** [comment]
I think the IJ wizard system supports integrating multiple tech/facet
options into the same new project flow.  If the user uses the IJ wizard to
create a Spring based project, it could be cool that they could choose to
have an app.yaml generated for them as well.

**Comment by etanshaul** [comment]
Good point. We could also use it to generate the template Dockerfile, placing both in the canonical directories.

The point about the facet is also interesting: earlier we discussed not using a facet for flex projects, but they could be used to manage the app.yaml / Dockerfile. This however would leave the difficulty of not having a facet for plain flex webapps that have no app.yaml or Dockerfile. In other words, we wouldn't be able to rely on the hypothetical flex facet for deployment.

**Comment by etanshaul** [comment]
outdated - we now have flex facet and flex framework support allowing the creation a web project with flex (app.yaml generation etc.)
