### ISSUE TITLE
Allow custom deployment configuration of app.yaml without a Dockerfile 

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/google-cloud-intellij#790]
Currently when doing a custom deployment, the user must specify both an app.yaml and a Dockerfile. Some users may want to specify a custom app.yaml without a Dockerfile.

**Comment by Eng-Fouad** [comment]
I had the same issue +1

**Comment by etanshaul** [comment]
Thanks for the feedback @Eng-Fouad! We'll consider re-prioritizing this.

**Comment by aslo** [comment]
We should probably still require that a Dockerfile exists if the provided app.yaml contains `runtime: custom`.

**Comment by etanshaul** [comment]
this is no longer applicable. all deployments are custom, and dockerfile selection is depending on the runtim selection. closing
