### ISSUE TITLE
Login widget widgets are not specific to the active user

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#796]
Steps to reproduce:

1) login two different users
2) follow the the 'developer console' link

observed result: the active user in the open tab will depend on the current active user in the browser, and not the active user in the IDE

desired result: the web console has the same active user as the active user in the IDE.

---

This may be difficult to achieve.  Low priority for now.

**Comment by etanshaul** [comment]
obsolete
