### ISSUE TITLE
We need to handle GCP projects that do not have App Engine applications

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#806]
Currently all GCP projects can be used for App Engine deployment.  Eventually this will no longer be the case. 

1) For cases where we are deploying to AE we will need to verify the project has an App Engine app
2) If not we need to present a UI to the user to create the app and select the Apps region.

**Comment by etanshaul** [comment]
fixed https://github.com/GoogleCloudPlatform/google-cloud-intellij/pull/1169
