### ISSUE TITLE
Race condition when running deploy/stop against the same project/module src. 

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#821]
Steps to reproduce:
1) Deploy a flex app to a project of your choice
2) Click 'undeploy' once deployment is complete
3) Redeploy the same project

observed result:
4) On completion of 'stop' it will overwrite the status of the deployment that's going on. 

expected result:
5) the new deployment should be a new version so conceptually different from the instance being stopped. I should continue to see the deployment happening even after my previous stop succeeds.

**Comment by patflynn** [comment]
This will happen for deployments of the same artifact to other projects as well since project is no longer part of the app server model. That should be fixed too.

**Comment by etanshaul** [comment]
@patflynn can you remind me where the race condition is? To reproduce, should step (3) happen while (2) is still in progress?

**Comment by patflynn** [comment]
the 'deployment' state visualized in the application servers panel is being shared by multiple deployments.

**Comment by etanshaul** [comment]
One complication with this is that when the user chooses a custom version, then the race condition is inevitable:

If the user stops a deployed version, and simultaneously redeploys, then both are competing against the same non-auto-incremented version.

**Comment by patflynn** [comment]
That might be OKish.  I would expect the second deployment to the same
version to overwrite the first.
