### ISSUE TITLE
Remove app engine standard new project wizard support from CE

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/google-cloud-intellij#824]
Currently, since our plugin is bundled in both editions, users can generate an app-engine standard project in CE. The project that is generated is not a full project though like in UE, just some bare directories with an appengine-web.xml.

We should remove this so that it doesn't show up in CE.

**Comment by etanshaul** [comment]
@patflynn @aslo @joaoandremartins - this can be closed now right? via https://github.com/GoogleCloudPlatform/google-cloud-intellij/commit/0716f5ace7db07f5eae5538188220178a670dc58

**Comment by joaoandremartins** [comment]
Yebo, though we should probably think about adding some hardcoded project structure, or even a Maven archetype as new projects in community edition. We can either close this and open a new issue or rename this one.

**Comment by etanshaul** [comment]
yea lets create new ones. I'll close this one.
