### ISSUE TITLE
App Engine Standard new project template should not include version and application elements

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#827]
Those are now passed as arguments to deployment rather than configured in the xml file.

**Comment by etanshaul** [comment]
still not supported in gcloud 129

**Comment by etanshaul** [comment]
@patflynn shall we move this to the next milestone as it is not yet supported?

**Comment by patflynn** [comment]
yeah.

**Comment by patflynn** [comment]
Although I think that once the new staging code goes out it'll actually
cause failures if they have these elements.

**Comment by patflynn** [comment]
dupe of #877
