### ISSUE TITLE
Investigate transient build failures

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/google-cloud-intellij#878]
We are seeing occasional build failures that correct themselves after restarting the job.

They usually occur for only one of the builds in the build matrix (one of the targeted versions of IJ). This makes me suspect that there is some issue running these builds in parallel.

**Comment by patflynn** [comment]
yeah this is the error I'm seeing:
```

* What went wrong:
Execution failed for task ':google-cloud-tools-plugin:ultimate:test'.
> Process 'Gradle Test Executor 9' finished with non-zero exit value 137
```

It seems like we're not outputting enough info to see the full cause info.
