### ISSUE TITLE
Why are our error bundles using intellij soft references?

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#89]
This is our pattern for initializing our error bundles:
  private synchronized static ResourceBundle getBundle() {
    ResourceBundle bundle = com.intellij.reference.SoftReference.dereference(ourBundle);
    if (bundle == null) {
      bundle = ResourceBundle.getBundle(BUNDLE_NAME);
      ourBundle = new SoftReference<ResourceBundle>(bundle);
    }
    return bundle;
  }

Why is this necessary? 

Elliotte dug up this that might have been a previous rationale: http://bugs.java.com/bugdatabase/view_bug.do?bug_id=4405807

**Comment by nkibler** [comment]
We would only need to do this if we wanted to maintain our own caching logic to prevent many long-running calls to reload the Bundle every time. But `ResourceBundle.getBundle()` has its own caching mechanism that will prevent a call to `.newBundle()` if it's already been created:

> During the resource bundle loading process above, this factory method looks up the cache before calling the control.newBundle method.
> ...
> All resource bundles loaded are cached by default.
- https://docs.oracle.com/javase/7/docs/api/java/util/ResourceBundle.html#getBundle(java.lang.String,%20java.util.Locale,%20java.lang.ClassLoader,%20java.util.ResourceBundle.Control)

So none of this is necessary; I'm sending a PR to remove this code.
