### ISSUE TITLE
Add metrics on "Disable Plugin" button

### ISSUE THREAD

**Issue by aslo** [GoogleCloudPlatform/google-cloud-intellij#892]
With the changes in https://github.com/GoogleCloudPlatform/google-cloud-intellij/pull/803, we want to get metrics on user interaction with the "Google Plugin Conflict" dialog (to disable the bundled app engine support plugin).

**Comment by chanseokoh** [comment]
It's probably good to also count the number of the notification pop-ups so that we know how much portion of people disable the old plugin.
