### ISSUE TITLE
Configuration deployment option appears for Compat Maven artifacts

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/google-cloud-intellij#907]
![maven_yesconf](https://cloud.githubusercontent.com/assets/3290856/18559665/46e21b9e-7b46-11e6-9495-ff26b650962f.png)
![explodedwar_noconf](https://cloud.githubusercontent.com/assets/3290856/18559666/46e3c502-7b46-11e6-871b-5a400d376a0a.png)

@etanshaul

**Comment by patflynn** [comment]
@etanshaul is this a regression or has this bug always been there?

**Comment by etanshaul** [comment]
I believe this was introduced when maven builds for AE standard-like projects (project with appengine-web.xml's) were introduced.

**Comment by etanshaul** [comment]
I found the source of the bug: flex compat determination is buggy for maven deployment sources. Will fix.
