### ISSUE TITLE
generated appengine-web.xml should not contain application and version nodes.

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#922]

**Comment by etanshaul** [comment]
dup of existing issue. heres a PR I have ready for this. Just waiting for gcloud to be updated:

https://github.com/GoogleCloudPlatform/google-cloud-intellij/pull/877

**Comment by patflynn** [comment]
woops. I thought I had filed it before, but my searches were coming up empty.  thx.
