### ISSUE TITLE
App Engine standard deployed apps no longer seem to successfully include src contxt

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#923]
to reproduce:

1) Generate an app engine standard app using the ij wizard
2) import the generated code into gcp source repos
3) Deploy the app
4) try to connect the cloud debugger to the version you just deployed

observer:
<img width="501" alt="screen shot 2016-09-22 at 8 06 02 am" src="https://cloud.githubusercontent.com/assets/7862557/18753847/77922da6-809b-11e6-894b-0cce67bc782a.png">

This is probably due to the fact we do staging outside of the project git workspace.

**Comment by joaoandremartins** [comment]
Can you check if there is a source-context.json file in {staging_dir}/WEB_INF/classes?

**Comment by patflynn** [comment]
I need to test this out.

**Comment by joaoandremartins** [comment]
@patflynn could this be because the projects generated by the IJ wizard don't contain any java code?

**Comment by patflynn** [comment]
@joaoandremartins If you look at [CloudSdkAppEngineHelper#184](https://github.com/GoogleCloudPlatform/google-cloud-intellij/blob/master/google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/appengine/cloud/CloudSdkAppEngineHelper.java#L184) you can see where the staging is taking place outside of the git workspace.

**Comment by joaoandremartins** [comment]
I verified that source-context.json is being correctly generated for standard apps, even with the staging directory outside of the repo directory.
The staging code seems to be taking into account the base dir rather than the staging one to generated source context. Look up appengine/tools/admin/Application.java l=263 in cs.

**Comment by patflynn** [comment]
That's great news.  I've just tested it out and it does work in the case where the code has a remote on GCR, just not when the repo is only local.  We can look into fixing that for the Nov release.
