### ISSUE TITLE
Cloud Debugger: Objects in the debugger view are not inspectable

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#929]
For some reason I can't see the values in the session any more:

<img width="1229" alt="screen shot 2016-09-22 at 12 19 25 pm" src="https://cloud.githubusercontent.com/assets/7862557/18762709/db698586-80be-11e6-969e-6795359cf01f.png">

**Comment by patflynn** [comment]
Steps:

1) checkout https://github.com/GoogleCloudPlatform/cloud-debugger-idea-sample
2) delete the .git dir
3) import into your personal cloud project repo on gcp
4) deploy the app to that same project
5) set a snapshot and trigger it using project.appspot.com/hellobrowser
6) see that the objects are missing lots of state

I know that CDB strips values from deeply nested objects for performance reasons. But I think we used to get more data than this.

**Comment by joaoandremartins** [comment]
Have we ever supported drilling down on composite objects in IJ?
I don't recall being able to drill down on them.
We don't seem to be getting this information from the server either. Take the following example with a composite, user, and simple object, guestbookName. Perhaps we need to make more calls to get the rest of the object detail?
Doesn't sound like a trivial change, I wouldn't block the Monday release on this one.

![screenshot from 2016-09-26 11 00 14](https://cloud.githubusercontent.com/assets/3290856/18839372/c174eebe-83d8-11e6-88fd-3fbb80cd9411.png)
![screenshot from 2016-09-26 11 00 34](https://cloud.githubusercontent.com/assets/3290856/18839398/e0763e08-83d8-11e6-90c2-0b2863030dbf.png)
![screenshot from 2016-09-26 11 00 51](https://cloud.githubusercontent.com/assets/3290856/18839401/e3084fe4-83d8-11e6-922a-8e3ed4d6da03.png)

**Comment by patflynn** [comment]
this definitely did work before.
