### ISSUE TITLE
Local server run isn't checking for app-engine-java in gcloud

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/google-cloud-intellij#931]
Following is logged if app-engine-java isn't installed:

4:24:53 PM Error running App Engine Local Server
           Error running Google App Engine Dev Server.
           Exception occurred : com.google.cloud.tools.appengine.cloudsdk.AppEngineJavaComponentsNotInstalledException
           Exception message : Validation Error: Java App Engine components not installed. Fix by running 'gcloud components install app-engine-java' on command-line.

**Comment by patflynn** [comment]
There is a fix coming in the common library that makes this unnecessary.
Talk to Mike.

**Comment by etanshaul** [comment]
I thought this was already fixed in gcloud? Isn't this just a matter of catching the exception and logging as is done in AppEngineStandardDeployTask?

**Comment by etanshaul** [comment]
https://github.com/GoogleCloudPlatform/google-cloud-intellij/pull/884

When I implemented this for deploy I didn't think about local run. I didn't think at the time that it depended on the app-engine-java component.

**Comment by joaoandremartins** [comment]
I'm thinking the run/debug window could probably prevent a local run from being launched if there is no app-engine-java installed. Currently, only the "new application servers" window does this, and it is letting me save that application server regardless.

**Comment by etanshaul** [comment]
We could take the same approach as deploy and just fail to start the local server but with a good message for the user in the console.

**Comment by patflynn** [comment]
plugin core lib is going to make a change that auto installs the java
component when starting a java app engine module.

**Comment by joaoandremartins** [comment]
@patflynn I think the change is pretty lightweight, and a good fall back in case anything goes awry.
@etanshaul the problem is that, unlike deployment, local run doesn't have a callback that we can use to write in the console. In fact, I don't know of a way to have access to it.

**Comment by etanshaul** [comment]
oh ok.

In any case, I talked to @meltsufin and there is an issue out there to auto download the component as mentioned. The exception should still be in place after that change, so like @joaoandremartins said we should probably still catch it and log a message to the user somewhere.
