### ISSUE TITLE
The different run configuration type titles are inconsistent

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#936]
cloud debugger = 'Cloud Debug'
AE deployment = 'App Engine (BETA) Deployment'
AE local run = 'Google AppEngine Dev Server'

My suggestion would be:
'Google Cloud Debugger'
'App Engine Deployment'
'App Engine Development Server'

@arouzrokh

**Comment by patflynn** [comment]
@elharo

**Comment by chanseokoh** [comment]
'Stackdriver Debugger', possibly without 'Google'?

**Comment by patflynn** [comment]
Yeah that's a good point.
