### ISSUE TITLE
Flex deployment fails for Windows 10 users.

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#937]
OS: Windows 10
Java: 1.8.0_112-release
IJ: 2016.2.4
plugin: 1.0-BETA-0.2

__NONE___
error.message	
null
error.stacktrace	
java.lang.UnsupportedOperationException
	at java.nio.file.Files.setPosixFilePermissions(Files.java:2044)
	at com.google.cloud.tools.intellij.appengine.cloud.AppEngineFlexibleStage.stage(AppEngineFlexibleStage.java:63)
	at com.google.cloud.tools.intellij.appengine.cloud.AppEngineFlexibleDeployTask.execute(AppEngineFlexibleDeployTask.java:68)
	at com.google.cloud.tools.intellij.appengine.cloud.AppEngineExecutor.run(AppEngineExecutor.java:37)
	at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:291)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:326)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:310)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:793)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:629)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by patflynn** [comment]
Alex can you take a look and check out the severity of this?

**Comment by aslo** [comment]
Sure, I can take a look this afternoon.

**Comment by loosebazooka** [comment]
This is coming from the common library though. Are we not detecting windows
correctly?

**Comment by joaoandremartins** [comment]
fyi, haven't been able to stage Flex successfully on Windows yet. tried on a gce instance and the test laptop.

**Comment by patflynn** [comment]
With this error?

**Comment by joaoandremartins** [comment]
Yes

**Comment by patflynn** [comment]
Do the maven and gradle plugins work on Windows 10?

**Comment by joaoandremartins** [comment]
Possibly, I doubt they're calling Files.setPosixFilePermissions().
https://github.com/GoogleCloudPlatform/google-cloud-intellij/blob/fa4eef8c8d2ffcb147c83c733533601b07784d19/google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/appengine/cloud/AppEngineFlexibleStage.java#L63

What's causing this on Windows is that we're trying to get a PosixFileAttributeView from WindowsFileSystemProvider, and it can't return it.
http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8-b132/sun/nio/fs/WindowsFileSystemProvider.java#156

I don't know of another way to set permissions on a file using Files. I might try to not set any permissions and see if that works.

**Comment by joaoandremartins** [comment]
In fact, this is failing for ALL windows users. Files.setPosixFilePermissions doesn't work in Windows, and I haven't been able to discover a way to modify file permissions on Windows, without having to run console commands..

I just verified that the copied file has owner and group read, which should be enough for our case, unless I'm missing anything?

**Comment by etanshaul** [comment]
What determines the default permissions? And is it system dependent?

**Comment by joaoandremartins** [comment]
As I understand, in java.nio there isn't a way to specify file permissions at copy time, you need to do it after copying, through Files.setPosixFilePermissions. However, this doesn't work on Windows, and I don't know of any other way other than running system commands.
Files.copy takes CopyOptions that don't seem to be what we need.

I removed the setPosixFilePermissions call on Windows and the whole deployment succeeded. Originally, I had only introduced the call to assure backwards compatibility with the previous call. However, unless there is an edge case that I can't see right now, we don't need this call.

**Comment by joaoandremartins** [comment]
FWIW, on Windows, after the file is copied, SYSTEM, Administrators and the current user are given full control of the file. I'm running as a machine administrator, but for any user that has similar permissions to run a deployment, the same should still apply.

**Comment by patflynn** [comment]
We did push this down:
https://github.com/GoogleCloudPlatform/appengine-plugins-core/blob/master/src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineFlexibleStaging.java

But doesn't that beg the question why it works for Maven/Gradle?

**Comment by etanshaul** [comment]
What I meant in my previous comment is that intellij isn't consuming this yet.

**Comment by patflynn** [comment]
Aha!  In any case, both codepaths would share the same problem.

**Comment by etanshaul** [comment]
Yeah, I'd be surprised if they didn't since the common lib is also using the posix permission setter mechanism.

**Comment by joaoandremartins** [comment]
It appears that someone on the library side was cunning enough to add a check:

if (!System.getProperty("os.name").contains("Windows")) {
          Set<PosixFilePermission> permissions = Sets.newHashSet();
          permissions.add(PosixFilePermission.OWNER_READ);
          permissions.add(PosixFilePermission.OWNER_WRITE);
          permissions.add(PosixFilePermission.GROUP_READ);
          permissions.add(PosixFilePermission.OTHERS_READ);

          Files.setPosixFilePermissions(destination, permissions);
        }

I can go ahead and replicate this on our side? Although I think I was just able to run Jetty without it

**Comment by etanshaul** [comment]
ah yes. I didn't notice that check. Perhaps in the interim, we should do the same thing in Intellij, and then get rid of this code once we defer to the common-lib for flex staging

**Comment by etanshaul** [comment]
I do have an issue to track that too: https://github.com/GoogleCloudPlatform/google-cloud-intellij/issues/717

**Comment by joaoandremartins** [comment]
I wasn't able to reproduce any issue without this piece of code, running the war on Jetty.
I would prefer to disable such unsightly code instead of adding it and YAGNI

**Comment by patflynn** [comment]
+1

**Comment by etanshaul** [comment]
Ok. @chanseokoh can you elaborate on your comment about jetty and the file persmissions relating to this to make sure we aren't missing something? is this still reproducible?

**Comment by joaoandremartins** [comment]
I was just able to reproduce the issue @chanseokoh was referring to. When the app is deployed to Flex, no instances will be spun up. Thanks @chanseokoh !

**Comment by joaoandremartins** [comment]
Actually, the version was stopped, which is why I couldn't reach the endpoint..
Deploying a pure Flex war artifact with -rw-r----- is allowing me to get good responses.

**Comment by joaoandremartins** [comment]
Unless @chanseokoh can still reproduce the issue with a different setup to mine, I suggest to go ahead with this code, and possibly delete the other one from the library.

**Comment by etanshaul** [comment]
STGM

**Comment by chanseokoh** [comment]
I just noticed that flex deploy works fine without the `others` read permission. I did some investigation and learned something funny:

This permission issue in the flex runtime image is more or less "fixed" by myself, _inadvertently_. When I was fixing the broken Cloud Debugger in the flex image, I decided to explicitly unpack a war (which is done by `root`) and change the owner of the unpacked contents to `jetty` ([PR here](https://github.com/GoogleCloudPlatform/appengine-java-vm-runtime/pull/222)). Never knew at that time this would also take care of the permission issue.

**Comment by patflynn** [comment]
But what about users of custom images? Couldn't they still have this issue?

**Comment by patflynn** [comment]
NM. I believe this fix: https://github.com/docker/docker/pull/13941, obviates the need for changing the permissions on the file.

**Comment by patflynn** [comment]
For posterity: https://github.com/GoogleCloudPlatform/appengine-plugins-core/pull/224 describes why this code change is safe.

**Comment by anhld4** [comment]
Hello, Can i fix this bug with plugin 1.0-BETA-0.3 ?

**Comment by patflynn** [comment]
@anhld4 unfortunately not.  We have a release planned tomorrow that'll include a fix for this.
