### ISSUE TITLE
Handle exception thrown by CloudSdk.Builder.build()

### ISSUE THREAD

**Issue by aslo** [GoogleCloudPlatform/google-cloud-intellij#944]
If called without providing the cloud sdk path, `CloudSdk.Builder.build()` attempts to [discover the path to the cloud sdk](https://github.com/GoogleCloudPlatform/appengine-plugins-core/blob/master/src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdk.java#L517-L539). If it is unable to locate one automatically, it throws an `AppEngineException`, which we are currently [not handling](https://github.com/GoogleCloudPlatform/google-cloud-intellij/blob/master/google-cloud-tools-plugin/ultimate/src/com/google/cloud/tools/intellij/appengine/server/instance/AppEngineServerModel.java#L169).

Ideally, the `build` and the `discoverSdkPath` methods should be using checked exceptions for this type of thing. There is an active PR to determine how best to categorize these exceptions (see https://github.com/GoogleCloudPlatform/appengine-plugins-core/pull/212). In any case, we can always just catch the (unchecked) AppEngineException if we have to.

**Comment by etanshaul** [comment]
obsolete (has since been refactored)
