### ISSUE TITLE
Support Java 8 standard runtime

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/google-cloud-intellij#946]
Java8 GAE standard runtime is coming in EA.
With the  latest GAE SDK, you can add `<runtime>java8</runtime>` in the appengine-web.xml, optionally update your web.xml to be servlet 3.1 based, and you'll be running on a Java8 runtime (when allowed), allowing all Java8 language features (lambdas) on a new security sandbox that does not require a whitelist.
Intellij (and Eclipse) plugins should be ready for the EA process. Deployment will still be whitelisted, but it would be nice to allow EA customers to use these plugins to get early feedback.

**Comment by patflynn** [comment]
Thanks Ludo.  Which version of the SDK includes this?  How do you specify
java8 in the appengine-web.xml?

**Comment by aslo** [comment]
Does this mean we should close https://github.com/GoogleCloudPlatform/google-cloud-intellij/issues/847 ?

**Comment by ludoch** [comment]
``<runtime>java8</runtime>``

Should start working on 1942 for both Flex and Standard, and even better with the coming (anyday now) 1944 or 1945.
Beta setting Quickstart will also be automatically inferred not before than 1946 (trick will be to have no web.xml or a web.xml declaring servlet 3.1 at the top, making it obsolete soon.

**Comment by ludoch** [comment]
Send me privately App Ids you want to be whitelisted.

**Comment by salamanders** [comment]
I think this is another symptom of the same root: I can't import javax.servlet.annotation.WebServlet; because eclipse project facet: Dynamic Web Module can't be set to 3.1.

Side question: @ludoch where should the rest of our web.xml settings go?  I found http://stackoverflow.com/questions/25552491/servlet-3-1-security-constraints-without-web-xml but it implies that not everything can move over 1:1.

**Comment by zmeggyesi** [comment]
@ludoch This is very exciting! Is there any way or channel to get an App ID to you for whitelisting? I would be eager to trial my code in the Java 8 runtime, if possible.

**Comment by patflynn** [comment]
@zmeggyesi sorry to have let your questions fall through the cracks.  I believe that Java 8 whitelisting is very restricted at the moment and should open up early next year.  I'll let @ludoch confirm/deny.

**Comment by zmeggyesi** [comment]
@patflynn That's fine, thank you. I'll keep my eyes open for the announcement, since I'm eager to try the J8 runtime.

**Comment by patflynn** [comment]
Looking at DefaultAppEngineProjectService it appears as though we're already tooled for this.

**Comment by yegle** [comment]
Finally :-) https://cloud.google.com/appengine/docs/standard/java/runtime-java8
