### ISSUE TITLE
Validate GWT super dev mode functionality

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/google-cloud-intellij#968]
make sure things still work properly

**Comment by etanshaul** [comment]
@patflynn I've confirmed that super dev mode still works. There is a minor point a friction though. We creating a new GWT / App Engine app from the wizard, if the user selects the Servlet API (which is selected by default), then the GWT code server fails to start due to invalid servlet API version on the classpath. The servlet api is provided by the gwt library. I am weary of adding logic to the managed library code to disable the servlet api when it is gwt project. Thoughts?

**Comment by patflynn** [comment]
what do you think about adding a warning to the label not to include it for
GWT projects?

**Comment by etanshaul** [comment]
hmm feels a bit arbitrary to me to be singling out GWT like that.

**Comment by etanshaul** [comment]
I am leaning towards this kind of thing being left up to the user to handle. Seems like this could lead us down a path of having to validate our managed dependencies against an ever increasing number of libraries.

**Comment by patflynn** [comment]
That's a good point.  Let's leave it out.

**Comment by etanshaul** [comment]
cool. closing this issue.

**Comment by branflake2267** [comment]
The servlet api isn't needed to run the server. What you do is use either DevMode or CodeServer main entry points to launch. Let's say you use DevMode, then you use the -war out/put/to/war, it compiles into that war. But then you turn off the embedded jetty server with -noserver, so it uses the app engine server. I've been wiring up better launcher support for CodeServer, but IntelliJ hasn't done it yet.

**Comment by branflake2267** [comment]
It looks like you're deploying from exploded war, so it doesn't look like I can modify the contents with SDM compiling. 

![screen shot 2016-10-10 at 9 26 23 am](https://cloud.githubusercontent.com/assets/1326504/19243241/a8300b8e-8ecb-11e6-89d7-a1fd1bfe95fd.png)

**Comment by branflake2267** [comment]
Are there any options to use a war directory path that would get used in the running app engine server?  Such as if I ran something like `DevMode ... -war /out/to/app/engine/war/directory -noserver com.example.Project`, then the browser launches, and starts the compile and adds those resources to the war/Project/Project.nocache.js.

**Comment by etanshaul** [comment]
@branflake2267 there indeed looks to be an issue with how we are disabling the embedded server when using the app engine server as a target. 

Re-opening this issue.

Regarding the war/exploded-war point: AE standard projects always deploy from an exploded war. I'm not sure I follow your question about pointing to the war directory path. When you choose the exploded-war artifact in that dropdown from your screenshot, your are pointing your deployment to the exploded war directly.

**Comment by branflake2267** [comment]
Ah, I get it, my mistake. If that's the case, the GWT Development (SDM or Super Dev Mode) can be started pointing to that directory. -war /exploded/war/directory would be the argument I would add. It could be nifty if that were available, reflected in the ui, for easy copy and paste into the program arguments of GWT launcher.

**Comment by branflake2267** [comment]
![screen shot 2016-10-10 at 10 11 14 am](https://cloud.githubusercontent.com/assets/1326504/19244703/6c0bdfe6-8ed2-11e6-9ccb-d703b24f7a78.png)

This is just a convenience opportunity. Starting app engine with GWT plugin, I'd suggest skipping the GWT compiler. There isn't a need to run a full compile on GWT if using GWT Development Mode (SDM) launcher to compile GWT App into the exploded war directory.

**Comment by branflake2267** [comment]
Another opportunity, add the default appengine-web.xml when it's missing. 

![screen shot 2016-10-10 at 10 16 18 am](https://cloud.githubusercontent.com/assets/1326504/19244805/ed9accd4-8ed2-11e6-90ac-355465f367c3.png)

**Comment by branflake2267** [comment]
Needing your project id right off the bat is a bit restrictive. :)

**Comment by branflake2267** [comment]
I hope I wasn't too noisy reporting. 

I can confirm that GWT SDM launching works good with  App Engine Dev Server. 

Validation could be had for the launcher. 
- super dev mode checked
- `-bindAddress` - match with dev server
- `-noserver` - required
- `-war` - required to be sent to output directory

`-bindAddress localhost -port 8080 -noserver -war /Users/branflake2267/git/gxt-testcases/GxtProject40/target/MyGxtProject40-1.0-SNAPSHOT`

Both processes ran together. Starting with app engine. 
- Skip gwt compile could be had
![screen shot 2016-10-10 at 10 37 47 am](https://cloud.githubusercontent.com/assets/1326504/19245476/3e097f32-8ed6-11e6-83c0-c6b4bdc27ee4.png)

GWT SDM Lancher
![screen shot 2016-10-10 at 10 38 03 am](https://cloud.githubusercontent.com/assets/1326504/19245486/45009b18-8ed6-11e6-814e-4cf840b1405f.png)

**Comment by patflynn** [comment]
Not at all! This is amazingly helpful feedback. We love this kind of
attention.

Thanks!

On Mon, Oct 10, 2016 at 1:42 PM, Brandon Donnelson <notifications@github.com

**Comment by etanshaul** [comment]
I can also confirm now that dev mode works properly with the app engine server target:

![image](https://cloud.githubusercontent.com/assets/1735744/19248558/c5f1203a-8efe-11e6-96fb-95ce8a96e286.png)

@branflake2267 thanks for all the helpful feedback. I'm going to close this issue for now, but will take all of your points into account and create new issues for them where appropriate. Feel free to re-open though if you encounter issues with gwt dev mode + app engine dev server.

**Comment by branflake2267** [comment]
Nice job! Thanks!
