### ISSUE TITLE
Usage tracking selection doesn't persist

### ISSUE THREAD

**Issue by branflake2267** [GoogleCloudPlatform/google-cloud-intellij#969]
I found I could not enable the usage tracking. The checkbox would not visually persist.

Replicate
- install plugin
- goto cloud preferences usage tracking dialog
- select usage tracking
- select ok, close preferences
- return to preferences, goto usage tracking

Screenshots of version below:

![screen shot 2016-10-10 at 7 37 32 am](https://cloud.githubusercontent.com/assets/1326504/19239889/e4207fd4-8ebc-11e6-81a7-b22c0bf1dd9d.png)
![screen shot 2016-10-10 at 7 39 01 am](https://cloud.githubusercontent.com/assets/1326504/19239890/e4263e56-8ebc-11e6-98f0-2aa26eb8a7e2.png)

**Comment by etanshaul** [comment]
@branflake2267 thanks for reporting this!

**Comment by etanshaul** [comment]
@patflynn we need to configure our CI to correctly set the analytics env var to fix this

**Comment by patflynn** [comment]
This shouldn't be related.

The latest release is Travis generated and if Analytics is not configured
the setting should be hidden.  I'll take a look and see if I can reproduce.

**Comment by patflynn** [comment]
I am able to repro this.  Going to take a look.
