### ISSUE TITLE
Old app engine icon

### ISSUE THREAD

**Issue by branflake2267** [GoogleCloudPlatform/google-cloud-intellij#970]
I'm not sure if this is an old launcher, but the new cloud icon with the old app engine icon below it. 

![screen shot 2016-10-10 at 9 46 04 am](https://cloud.githubusercontent.com/assets/1326504/19243887/7ec5b142-8ece-11e6-9e87-c0bd690d8796.png)

**Comment by branflake2267** [comment]
There are several app engine launcher options, which make it confusing. 

![screen shot 2016-10-10 at 9 49 19 am](https://cloud.githubusercontent.com/assets/1326504/19243962/f0ea7672-8ece-11e6-82bd-940e5b39ba0a.png)

**Comment by etanshaul** [comment]
Please check first to make sure you have disabled the bundled IntelliJ app engine plugin 'Google App Engine Integration':

![image](https://cloud.githubusercontent.com/assets/1735744/19244114/c84353b4-8ee8-11e6-9953-c8661de168e0.png)

This will ensure that you are only using the new google plugin tooling. You should have been notified by the IDE at some point with a [popup to disable it](https://github.com/GoogleCloudPlatform/google-cloud-intellij/pull/803) to avoid these kinds of conflicts. I know this is a bit inconvenient but we are working on a better solution.
