### ISSUE TITLE
App Engine (Beta) Launcher name only allows one character

### ISSUE THREAD

**Issue by branflake2267** [GoogleCloudPlatform/google-cloud-intellij#971]
The launcher is only allowing me to type in one character. 

![screen shot 2016-10-10 at 7 39 01 am](https://cloud.githubusercontent.com/assets/1326504/19244109/9fb489fe-8ecf-11e6-8b64-ef296b93e70f.png)

![screen shot 2016-10-10 at 9 54 01 am](https://cloud.githubusercontent.com/assets/1326504/19244099/97c59c06-8ecf-11e6-8f88-3ba87abb0b18.png)

**Comment by etanshaul** [comment]
Really weird. I'm not able to reproduce this. But I noticed that you have the old Jetbrains appengine plugin installed alongside the new Google ones. Try and disable those per [my comment](https://github.com/GoogleCloudPlatform/google-cloud-intellij/issues/970#issuecomment-252679312) and see if that helps.

**Comment by branflake2267** [comment]
That seem to fix it. That was weird. You can close this.
